README.md

For your consideration, adding some text from the install docs over on the data act core repo. I'd added this text before we decided to keep the web app directions in this repo. If you think it works, would like to get it merged in before we strike it from core.
Mostly just added some clarifying info about installing node and cloning the repo.

copy some setup directions from core

---

README.md

Based on feedback from a local install tester, better to instruct people to git clone using https.

replace ssh w/ https in git clone directions

---

src/js/components/addData/AddDataHeader.jsx
src/js/components/help/helpContent.jsx
src/js/components/landing/LandingContent.jsx
src/js/components/validateData/ValidateDataContent.jsx
src/js/components/validateData/ValidateDataFileComponent.jsx
src/js/components/validateData/ValidateDataOverlay.jsx
src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx
src/js/containers/validateData/ValidateDataContainer.jsx
src/js/containers/validateData/ValidateDataOverlayContainer.jsx
src/js/helpers/uploadHelper.js
src/js/helpers/util.js

* RSS links now point to the signed S3 URL
* Files currently in validation no longer appear semi-opaque
* Validation overlay lower-third bar no longer appears until all validations are complete (preventing user from accidentally uploading files before validation is done)
* Validation overlay upload button now remains disabled during period between file re-upload completion and `check_status` first returns new data, preventing possibility of user re-uploading reuploaded data

Signed RSS Spec URL, bug fixes

---

src/_scss/common.scss
src/js/components/SharedComponents/navigation/AdminButton.jsx
src/js/components/SharedComponents/navigation/NavigationComponent.jsx
src/js/components/SharedComponents/navigation/UserButton.jsx
src/js/components/addData/AddDataContent.jsx
src/js/components/addData/AddDataPage.jsx
src/js/components/reviewData/ReviewDataButton.jsx
src/js/components/reviewData/ReviewDataContent.jsx
src/js/components/reviewData/ReviewDataPage.jsx
src/js/components/validateData/ValidateDataContent.jsx
src/js/components/validateData/ValidateDataPage.jsx
src/js/components/validateData/validateValues/ValidateValuesContent.jsx
src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx
src/js/helpers/util.js

* After the initial Add Metadata page, page transitions to the upload, validate, and review data screens are accompanied by an automatic scroll down past the top header
* Autoscroll also occurs when the user stays on the same validation page, but uploads a new set of files
* Admin button was moved from the navbar to the top black bar next to the user name, per new designs
* Fixed a bug where the Upload Corrected CSVs button did not correctly disable during upload/`check_status` pending period if the user was uploading files after everything passed validation

Autoscroll to Validation Content

---

gulpfile.babel.js
index.html
src/js/helpers/util.js

* Gulp will now always output to `public/` and use the same folder structure, even in local dev environments
* This time merging into dev instead of master

Hotfix: Saner Gulp output

---

src/js/components/login/LoginPanel.jsx
src/js/containers/login/LoginContainer.jsx
src/js/helpers/loginHelper.js

* Display login error messages using the server's `message` value, when available
* Continue to display an error message if the browser doesn't write the session cookie

Display account expired/locked out error messages

---

src/js/components/addData/AddDataHeader.jsx
src/js/components/addData/AddDataPage.jsx
src/js/components/help/helpContent.jsx
src/js/components/landing/LandingContent.jsx
src/js/helpers/util.js

* Fixed a bug related to autoscrolling that caused a JS error on initial load of the Add New Data metadata page
* Fixed a bug where React would trigger a JS error if the user went to a page that called the `get_rss` API endpoint but navigated away before the API responded. Fixed by making the Promise API call cancelable and canceling on component unmount.

Misc. Bug Fixes

---

gulpfile.babel.js
package.json
src/help/changelog.md
src/js/components/help/helpContent.jsx
src/js/components/help/helpPage.jsx
src/js/components/help/helpSidebar.jsx
src/js/components/help/helpSidebarItem.jsx
src/js/helpers/helpHelper.js

* Help page "What's New" section is now populated from a Markdown file
* Help page side bar "What's New" links are now dynamically generated based on section headers in the Markdown file
* Customized Markdown parser to handle special metadata in the section headers
* Changes to the Gulp task:
* Local production mode no longer has live reloading (uses less memory, no more web sockets)
* Production mode (local and hosted) now use appended `?v=[git hash]` CSS and app.js URLs in index.html file to invalidate browser caches when a new build is available

Help Page Markdown

---

src/_scss/pages/addData.scss
src/js/components/SharedComponents/ProgressComponent.jsx
src/js/components/addData/AddDataContent.jsx
src/js/components/addData/AddDataHeader.jsx
src/js/components/addData/AddDataMeta.jsx
src/js/components/reviewData/ReviewDataPage.jsx
src/js/components/validateData/ValidateDataContent.jsx
src/js/components/validateData/ValidateDataFileComponent.jsx
src/js/components/validateData/ValidateDataFilePlaceholder.jsx
src/js/components/validateData/ValidateDataInProgressOverlay.jsx
src/js/components/validateData/ValidateDataPage.jsx
src/js/components/validateData/ValidateLoadingScreen.jsx
src/js/components/validateData/validateValues/ValidateValuesContent.jsx
src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx
src/js/containers/validateData/ValidateDataContainer.jsx

* Validation boxes now fade in and allow for a smooth transition from the upload screen
* Autoscroll behavior has been removed. During the "gathering data" phase, placeholder boxes approximate the validation layout.
* Bottom bar now appears throughout the entire validation process and now has new messages to indicate "gathering data" and "validation in progress" stages
* "Validating..." message inside file boxes now appears in black text instead of red
* Top bar updated to reflect four submission steps instead of three
* Fixed a bug where, if more than 5 minutes passed between validation completing and the start of either the next validation cycle or file upload, the "stuck in validation" message would erroneously appear

Validation Page Transitions

---

src/_scss/pages/addData.scss
src/_scss/pages/addMetaData.scss
src/js/components/validateData/ValidateDataFileComponent.jsx
src/js/components/validateData/ValidateDataInProgressOverlay.jsx
src/js/components/validateData/treemap/Treemap.jsx
src/js/components/validateData/treemap/TreemapCell.jsx
src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx
src/js/components/validateData/validateValues/ValidateValuesTreemap.jsx
src/js/components/validateData/validateValues/ValidateValuesTreemapHelp.jsx
src/js/components/validateData/validateValues/ValidateValuesTreemapHelpPlaceholder.jsx
src/js/containers/validateData/ValidateDataContainer.jsx

* New treemap color
* Treemap labels are now `original_label`, updated treemap sidebar text to show detailed rule failure information
* Fixes a bug where, if a file had header errors and was replaced with a file that did not _and_ the header error details were expanded, a half-populated header error details table would appear while the replacement file was in validation
* Removed "validation is stuck" message and replaced it with a new lower-third overlay that provides a URL that the user can use to return to the page at a later time

Updated Treemap

---

src/js/components/validateData/treemap/Treemap.jsx
src/js/components/validateData/validateValues/ValidateValuesTreemap.jsx
src/js/components/validateData/validateValues/ValidateValuesTreemapHelp.jsx

* Replaces `original_label` with `field_name`
* Hides Rule XXX header in sidebar
* Fixes a bug where treemap cells of the same value could reshuffle between render cycles by caching the treemap in the component's state

Remove original_label from treemap

---

src/_scss/pages/addMetaData.scss
src/js/components/addData/metadata/DateDropdown.jsx
src/js/components/addData/metadata/DateRangeField.jsx
src/js/components/addData/metadata/DateTypeField.jsx

* New submission metadata page now has only one date dropdown instead of accepting an arbitrary range of dates
* When a month is selected, a warning now appears that monthly submissions can only be validated, not submitted

DB-715: Single Date Dropdown

---

src/js/components/validateData/treemap/Treemap.jsx
src/js/components/validateData/treemap/TreemapCell.jsx
src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx
src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx
src/js/components/validateData/validateValues/ValidateValuesFileDetailBox.jsx
src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx
src/js/components/validateData/validateValues/ValidateValuesTreemap.jsx
src/js/components/validateData/validateValues/ValidateValuesTreemapHelp.jsx

* UI implementation only, no API integration
* Will currently always display 0 warnings until API is ready
* Refactors warnings/critical errors sections into a smaller, shared React component
* Restores `original_label` behavior in treemaps
* Fixes a bug where if the number of occurrences exceeds 9, strange treemap cell coloring occurs

File Warnings

---

src/js/components/validateData/ValidateDataContent.jsx
src/js/components/validateData/ValidateDataFileComponent.jsx
src/js/components/validateData/ValidateDataInProgressOverlay.jsx
src/js/containers/validateData/ValidateDataContainer.jsx
src/js/helpers/reviewHelper.js

* Display an error message when a validation job fails
* Display an error message when an invalid submission ID is provided
* Allow the page to reload when the submission ID in the URL changes
* Fixes a bug where unmounting the validation Redux container while a `check_status` API call was in-flight and the previous API call had not resulted in a fully complete set of validation jobs would cause the Redux submission object to be reset every 5 seconds
* Fixes a bug where "not yours" error message would never show up
* Page no longer constantly reloads `check_status` when validation job failures occur
* Refactored `check_status` response code to use fewer for loops

Handle Validation Errors

---

src/js/components/crossFile/CrossFileOverlay.jsx

* Fixes a bug where the upload button would be enabled even though no files were staged for upload after an initial upload had occurred

Hotfix: Cross File

---

src/help/changelog.md

under Beta release section, corrected the spelling of relevant and deleted a doubled "the"

editorial changes

---

src/help/changelog.md
src/js/components/help/helpContent.jsx
src/js/components/help/helpSidebar.jsx
src/js/containers/router/RouterRoutes.jsx
src/js/helpers/util.js

* Removed all API calls to `/get_rss`
* API integration with `/get_protected_files`
* Removed Resources section from `changelog.md`, implemented it with signed URLs in JS
* Added link to new Resources section in validation table
* Removed Submission Guide/Add Data Webpack chunk; these are now bundled into the initial `app.js` file to prevent the Submission Guide from appearing momentarily after the user has chosen to hide it
Merge approvals:

Help Links

---

src/js/components/crossFile/components/GeneratedErrorButton.jsx
src/js/components/crossFile/components/GeneratedFileModal.jsx
src/js/containers/crossFile/CrossFileGenerateModalContainer.jsx

* Fixes a bug where submission ID was not passed to the regeneration modal
* Disabled Generate button in regeneration modal while initial `check_dX_file` request is in flight

Hotfix: Cross-file D1/D2 regeneration

---

src/js/components/generateFiles/components/GenerateFileBox.jsx

* If D1/D2 generation routes return a URL of `#`, do not show the download link.

Hide hashed URLs

---

src/js/containers/generateFiles/GenerateFilesContainer.jsx

* Resulted in JS errors when month lengths differed from expected

Hotfix: Incorrect adjustment for zero-indexed months

---

src/js/containers/generateFiles/GenerateFilesContainer.jsx

* Displays an error message when an unformatted server error occurs
* Does not allow file generation to progress without successful files

Update: Handle D file server errors

---

src/js/components/help/helpContent.jsx

- Removing practices & procedures link from help page temporarily

Hotfix to remove link

---

src/js/components/generateEF/GenerateEFContent.jsx
src/js/components/help/helpContent.jsx

- Removing Practices & Procedures link on help page
- Updating text for E & F to read “Download functionality related to
Files E and F are not yet available.”

Hotfix updates

---

src/js/components/validateData/ValidateDataFileComponent.jsx

* Displays an error message when the header rows cannot be parsed rather than becoming stuck in validation

Handle unparseable header rows

---

src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx
src/js/helpers/generateFilesHelper.js

- Using `job_id` to look up generation status (which is returned as part of the response for `generate_detached_file`)

Switching check detached generation status to pass job_id instead of file_type

---

.eslintignore
.eslintrc
.travis.yml
src/js/helpers/reviewHelper.js
src/js/helpers/util.js

Rather than go without a linter (our current strategy), let's draw a line in
the sand and prevent future issues by adding a linter that matches our current
code base. We're breaking some pretty important rules (e.g. no-undef), so we
should revisit these to fix things ASAP.

Add eslintrc rules consistent w/ codebase + Travis

---

src/js/components/crossFile/components/ErrorBox.jsx
src/js/components/validateData/ValidateDataErrorReport.jsx
src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx
src/js/helpers/reviewHelper.js

This avoids creating the file name within JS for security and flexibility. It must be merged concurrently with fedspendingtransparency/data-act-broker-backend#489

Replace signErrorWarningReport w/ submissionReport

---

src/js/components/addData/AddDataHeader.jsx
src/js/components/crossFile/components/ErrorBox.jsx
src/js/components/validateData/ValidateDataErrorReport.jsx
src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx
src/js/containers/review/ReviewDataContainer.jsx
src/js/helpers/agencyHelper.js
src/js/helpers/reviewHelper.js

~~Depends on fedspendingtransparency/data-act-broker-backend#484~~. Adds the agency name and submission date to the floating submission context:

Include submission context in UI

---

src/js/components/validateData/ValidateDataFileComponent.jsx
src/js/containers/generateEF/GenerateEFContainer.jsx

Adding a flag to the state so that we can identify if it has not been generated (queuing the generation) or if it is an error. Instead of generating on componentDidMount, do fileStatusCheck instead.

EF autofile generation disabled

---

src/_scss/pages/reviewData/_content.scss
src/js/components/reviewData/ReviewDataContent.jsx

Prevents user from certifying monthly submissions and shows a banner explaining why beneath the buttons.

Db 1766 prevent monthly certification

---

src/js/components/dashboard/DashboardTable.jsx
src/js/components/landing/recentActivity/RecentActivityTable.jsx

End submission dates should now be the last day of that month on the recent activity table and the tables in the submission dashboard

Formatting the submission information

---

src/_scss/pages/uploadDetachedFiles/uploadDetachedFiles.scss
src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx
src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx
src/js/containers/validateData/ValidateValuesFileContainer.jsx
src/js/helpers/uploadHelper.js

Allow users to reupload files on the `/uploadDetachedFiles` route when there are errors.
Acceptance Criteria
- Users can upload a replacement file in a FABS submission

Db mk 1667 fabs reupload

---

src/js/components/reviewData/ReviewDataContent.jsx

By default, the certify button is disabled unless admin or submitter. It was non-readers before

DB 1805 Certify Button is disabled by default unless admin or submitter

---

src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx

As an agency user, I want to see the rule label in all of the error and warning descriptions
**Acceptance Criteria:**
- Rule label (i.e. A9) is present in the error messages on all validation pages
**Checklist:**

db-1700 Add the rule label for error and warning descriptions

---

src/js/components/help/helpContent.jsx
src/js/components/help/helpSidebar.jsx

Fixing the behaviour of the service desk link in the sidebar of the help page

DB 1476 MK Help Page Service Desk behaviour

---

src/_scss/pages/crossFile/crossFile.scss

Red exclamation was due to the warning class having a red background. overrode it for the crossFile

RED EXCLAMATION!

---

src/js/components/landing/recentActivity/SubmissionLink.jsx

Submission IDs in the view links weren't updating properly on page change. Updated the SubmissionLink component to re-check the route every time the submission_id changes

Hotfix: submission id table pagination

---

sampleGlobalConstants_dev.js
sampleGlobalConstants_local.js
sampleGlobalConstants_prod.js
src/_scss/abstract/variables/globalPositioning.scss
src/_scss/layouts/default/header/_warningBanner.scss
src/_scss/layouts/default/header/header.scss
src/_scss/layouts/login/login.scss
src/js/components/SharedComponents/banners/TestEnvironmentBanner.jsx
src/js/components/SharedComponents/navigation/NavigationComponent.jsx
src/js/components/login/AuthPage.jsx
src/js/components/login/LoginPage.jsx

Adding a banner to the staging environment (on login screen and when already logged in) to indicate that it is not a production environment.
Technical Release Notes:
- New global constant

Db 2043 staging banner

---

src/js/components/validateData/ValidateDataFileComponent.jsx

AC:
- Provide more accurate error code logic/text that fits the case of uploading a file with the wrong extension
- ~~Make sure the submitted file is downloadable from this screen~~
- Remove link to critical error/warning reports for this file level error

DB-2155 Cannot download files with file_type_errors

---

src/_scss/pages/uploadDetachedFiles/uploadDetachedFiles.scss
src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx
src/js/helpers/reviewHelper.js

Prevent duplicate transactions from being published if a different submission with the same new entries is published and provide a revalidate button for fabs submissions.

Db 2125 prevent duplicate fabs time

---

src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx
src/js/components/uploadDetachedFiles/UploadDetachedFilesError.jsx
src/js/helpers/generateFilesHelper.js

AC:
- Write published submission rows to a file, including derived fields
- Allow user to download the file from the published submission page

DB-2289 access raw agency fabs files

---

src/js/components/crossFile/CrossFileOverlay.jsx
src/js/components/crossFile/components/ErrorBox.jsx
src/js/components/crossFile/components/FileComponent.jsx
src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx
src/js/components/validateData/ValidateDataFileComponent.jsx
src/js/components/validateData/ValidationContent.jsx
src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx
src/js/containers/crossFile/CrossFileContentContainer.jsx
src/js/containers/validateData/ValidateDataContainer.jsx
src/js/helpers/reviewHelper.js

Lessening the number of check_status calls for single-file validations (DABS and FABS) and cross-file validations (DABS) pages.

Db 2206 prevent duplicate api calls

---

src/js/components/generateEF/GenerateEFContent.jsx

- Updates file generation text to reflect that Files E and F are based off of File D, not File C
Bug: https://federal-spending-transparency.atlassian.net/browse/DEV-451

Fix - File E and F Generation Text

---

src/help/validations.csv

Change BudgetAuthorityAvailableAmountTotal_CPE to TotalBudgetaryResources_CPE
[story link](https://federal-spending-transparency.atlassian.net/browse/DEV-875)

DEV: 875 Updating a2, a6, a24 due to column rename

---

src/help/fabs_validations.csv

1. Switch 24.1 and 24.2 in the Broker
2. Reassign these rules new code numbers (these should be reflected in the codes that appear in the error reports generated when these rule triggers) as follows:
FABS2.2 -> FABS2.2.1
FABS2.3 -> FABS2.2.2
FABS2.4 -> FABS2.2.3
[story link](https://federal-spending-transparency.atlassian.net/browse/DEV-888)

Updating SQL Rules to match backend

---

src/js/helpers/generateFilesHelper.js

Update `check_generation_status` and `check_detached_generation_status` from POST requests to GET.
Change the request for `check_generation_status` and `check_detached_generation_status` from POST to GET.
[DEV-1208](https://federal-spending-transparency.atlassian.net/browse/DEV-1208)

DEV-1208: Switch check_generation_status and check_detached_generation_status to GET

---

src/js/helpers/generateFilesHelper.js

Updating frontend so E/F generation isn't broken
Updating so we only pass start/end date for file generation if it's a D1/D2 file. We don't want to pass it for E/F files
[DEV-1211](https://federal-spending-transparency.atlassian.net/browse/DEV-1211)

Only pass start/end if they're given

---

src/js/helpers/uploadHelper.js

Cleaning up upload_detached_file route params.
Dates, cgac/frec codes, and quarter checks in upload_detached_file are useless because we don't do anything with any of them. Removed this metadata from the upload_detached_file calls
[DEV-1280](https://federal-spending-transparency.atlassian.net/browse/DEV-1280)

DEV-1280: Remove unnecessary params in upload_detached_file

---

src/js/helpers/uploadHelper.js

Renaming `submit_files` to `upload_dabs_files`.
Renaming `submit_files` to `upload_dabs_files` to reflect the changes on the backend
[DEV-1328](https://federal-spending-transparency.atlassian.net/browse/DEV-1328)

DEV-1328: rename submit files route

---

src/js/helpers/uploadHelper.js

Renaming `upload_detached_file` to `upload_fabs_file`.
Renaming `upload_detached_file` to `upload_fabs_file` to reflect the changes on the backend
[DEV-1329](https://federal-spending-transparency.atlassian.net/browse/DEV-1329)

DEV-1329: rename upload detached file route

---

src/js/helpers/uploadHelper.js

Firefox users cannot upload one or two corrected files on the `/#/validateData` page.
Firefox cannot handle attaching empty objects to the Request, and will throw an (unhandled) error. We must only attempt to attach these files to the Request if the file exists.
[DEV-1465](https://federal-spending-transparency.atlassian.net/browse/DEV-1465)
- Merged concurrently with Backend N/A
- Backend impact assessment completed N/A

DEV-1465: Firefox upload corrected files bugfix

---

src/help/validations.csv

Updating rule text to match the corrections on the backend
Updating C9 so it says AssistanceType of 07 and 08 rather than 08 and 09 (based on backend changes)
[DEV-1222](https://federal-spending-transparency.atlassian.net/browse/DEV-1222)

DEV-1222: c9 assistance type correction

---

src/_scss/components/typeahead/_typeahead.scss
src/_scss/pages/dashboard/_filters.scss
src/_scss/pages/dashboard/_textFilter.scss
src/_scss/pages/dashboard/_typeaheadFilter.scss
src/js/components/SharedComponents/Typeahead.jsx
src/js/components/dashboard/DashboardFilters.jsx
src/js/components/dashboard/filters/AgencyFilter.jsx
src/js/components/dashboard/filters/TagItem.jsx
src/js/containers/dashboard/AgencyFilterContainer.jsx
src/js/containers/dashboard/DashboardContainer.jsx
src/js/containers/dashboard/FilterBarContainer.jsx

Implements the submission dashboard agency filter. 
- `AgencyFilterContainer` (similar to the existing `AgencyListContainer`) makes a call to the `list_all_agencies` endpoint, removes agencies that are already staged as filters, and passes the remaining agency values to populate the dropdown of an [Awesomeplete](https://www.npmjs.com/package/awesomplete) Typeahead component. 
- Updates the Typeahead component to return the name of the agency in addition to the code upon selection
- Processes staged/applied Agency filter tags for display
- Processes applied agency filters and adds them to the `list_submissions` `filters` request param
- Overrides existing Typeahead styling within the Submission Dashboard  …

Feature dashboard agency filter

---

sampleGlobalConstants_dev.js
sampleGlobalConstants_local.js
sampleGlobalConstants_prod.js
src/js/components/addData/SubmissionGuideContent.jsx
src/js/components/landing/blocks/LandingRequirementsBody.jsx

There was a link to an S3 bucket in frontend that was missed during the initial exploration phase when creating DEV-1547. This replaces the S3 link with one that meets our requirements.
Created a global variable to handle the link to the static files in S3. Use that variable when linking to those files.
[DEV-1547](https://federal-spending-transparency.atlassian.net/browse/DEV-1547)

DEV-1547: Remove generic S3 links from frontend

---

src/_scss/abstract/mixins/buttons.scss
src/_scss/abstract/variables/typography.scss
src/_scss/components/tooltip/_arrow.scss
src/_scss/pages/generateDetachedFiles/_agencyToggle.scss
src/_scss/pages/generateDetachedFiles/_agencyToggleTooltip.scss
src/_scss/pages/generateDetachedFiles/generateDetachedFiles.scss
src/js/components/generateDetachedFiles/AgencyToggle.jsx
src/js/components/generateDetachedFiles/AgencyToggleTooltip.jsx
src/js/components/generateDetachedFiles/DateSelect.jsx
src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx
src/js/helpers/generateFilesHelper.js

Adds a toggle for awarding/funding agency to the DABS detached generation page.
- Adds the `agency_type` parameter to the `/v1/generate_detached_file` request. Documentation [here](https://github.com/fedspendingtransparency/data-act-broker-backend/blob/development/dataactbroker/README.md#post-v1generate_detached_file).
- Animates an svg slider element based on a state boolean
- Displays a tooltip on hover/focus of info icon
[DEV-1350](https://federal-spending-transparency.atlassian.net/browse/DEV-1350)

File D Agency Toggle

---

src/_scss/pages/generateFiles/generateFiles.scss
src/js/components/generateDetachedFiles/AgencyToggle.jsx
src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx
src/js/components/generateFiles/GenerateFilesContent.jsx
src/js/containers/generateFiles/GenerateFilesContainer.jsx
src/js/helpers/generateFilesHelper.js

Adds a toggle for awarding/funding agency to the generate D files page, during a submission.
- Adds the `agency_type` parameter to the `/v1/generate_file` request. Documentation [here](https://github.com/fedspendingtransparency/data-act-broker-backend/blob/development/dataactbroker/README.md#post-v1generate_file).
- Animates the svg slider element based on a state boolean
- Adds the info tooltip
[DEV-1350](https://federal-spending-transparency.atlassian.net/browse/DEV-1350)

File D agency toggle - submissions

---

src/_scss/pages/dashboard/_filters.scss
src/js/components/SharedComponents/CalendarRangeDatePicker.jsx
src/js/containers/dashboard/LastDateModifiedContainer.jsx

Dropdown now closes if you click away from the menu and properly calculates the min/max date
- Min/Max Dates now ignore any null `last_modified` dates in the response.
- Handles Clicks outside the active dropdown menu div
[DEV-1363](https://federal-spending-transparency.atlassian.net/browse/DEV-1363)

Last Date Modified Filter Dropdown

---

src/_scss/pages/generateDetachedFiles/_agencyToggleTooltip.scss
src/js/components/generateDetachedFiles/DateSelect.jsx
src/js/components/generateFiles/GenerateFilesContent.jsx

Fixes funding agency tooltip (see latest comments on [DEV-1350](https://federal-spending-transparency.atlassian.net/browse/DEV-1350))
In IE, the z-index property only applies to objects that have the position property set to `relative` or `absolute`. Changed the info icon holder to `position: relative;` to prevent overlap with another icon in IE and updated the right position of the tooltip. 
[DEV-1350](https://federal-spending-transparency.atlassian.net/browse/DEV-1350)

Fix agency toggle tooltip

---

src/_scss/pages/addData/uploadPage/_uploadDropzone.scss
src/js/components/SharedComponents/CalendarRangeDatePicker.jsx
src/js/components/addData/AddDataContent.jsx
src/js/components/addData/DropZone.jsx
src/js/components/addData/DropZoneDisplay.jsx
src/js/components/addData/SubmissionComponent.jsx
src/js/containers/addData/AddDataContainer.jsx
src/js/helpers/uploadHelper.js

Allows Frontend to correctly catch and display File upload errors from backend([DEV-1327](https://federal-spending-transparency.atlassian.net/browse/DEV-1327))
- Passes backend error messages from file upload API response into associated containers
- Before file is uploaded, checks to see if the file is a valid file type. If not, displays a preemptive error message
[DEV-1676](https://federal-spending-transparency.atlassian.net/browse/DEV-1676)

Handle file upload errors on Frontend

---

src/js/containers/dashboard/CreatedByContainer.jsx
src/js/helpers/createdByHelper.js

Fixes incorrect names issue with created by filter on FABS Table
Makes a dynamic API call to `list_submission_users` based on FABS/DABS table
[DEV-1366](https://federal-spending-transparency.atlassian.net/browse/DEV-1366)

Get created by user list by tablename

---

src/_scss/pages/uploadFabsFile/uploadFabsFile.scss
src/_scss/pages/validateData/fileItem/fileItem.scss
src/js/components/addData/DropZone.jsx
src/js/components/validateData/ValidateDataFileComponent.jsx
src/js/components/validateData/ValidationOverlay.jsx
src/js/containers/validateData/ValidationOverlayContainer.jsx
src/js/helpers/util.js

- Hotfix for windows machines,  which incorrectly view all `.csv` files as excel files.
- Also adds error messages for incorrect file types in upload verification
-  Created new helper for determining correct file types
-  Updates components to catch and react to all errors not just  `403 forbidden`
[DEV-1676](https://federal-spending-transparency.atlassian.net/browse/DEV-1676)

Hotfix for Upload file type error handling

---

src/js/components/SharedComponents/CalendarRangeDatePicker.jsx
src/js/containers/dashboard/LastDateModifiedContainer.jsx

Temporarily disable API call for last date modified min/max dates and hardcode dates until backend endpoint is ready
Disabled `this.loadData()` in `LastDateModifiedContainer` and the code to parse its api response
[DEV-1877](https://federal-spending-transparency.atlassian.net/browse/DEV-1877)

Temporarily hard code min/max dates for Date Modified Filter

---

src/js/helpers/lastDateModifiedHelper.js
src/js/helpers/submissionListHelper.js

Updating parameters to send to backend
Rename `d2_submission` param to `fabs` in `list_submissions` to match the backend
[DEV-1378](https://federal-spending-transparency.atlassian.net/browse/DEV-1378)

DEV-1378: Update list_submissions param names

---

src/js/components/uploadFabsFile/UploadFabsFileError.jsx
src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx

Fixes an issue with FABS upload that would simply display a red exclamation mark when there was an error, without any explanation/suggestion to fix the issue.
[DEV-2033](https://federal-spending-transparency.atlassian.net/browse/DEV-2033)

Fix for thrown upload error not showing up in frontend UI

---

src/js/components/generateDetachedFiles/DetachedFileA.jsx
src/js/components/generateDetachedFiles/PeriodPicker.jsx
src/js/helpers/periodPickerHelper.js
src/js/helpers/util.js
tests/helpers/periodPickerHelper-test.js

Fixed typo on months in period picker dropdown, updated copy and also limited selectable options to available fields. Also allowed FY 2017 to start on October and updated tests.
[DEV-2087](https://federal-spending-transparency.atlassian.net/browse/DEV-2087)

File A Generation Tweaks

---

src/js/components/validateData/treemap/Treemap.jsx

The Warnings & Errors report treemap was not rendering correctly because each cell did not always have a unique `key` value. 
- Caused by this change: https://github.com/fedspendingtransparency/data-act-broker-web-app/commit/915e1fbdb7d85f33510776fa1a6982447e716944#diff-fe05e4274626a200e56c89a4dd872f74R116
- Updated the `key` value to include the cell index to prevent duplicates when multiple cells have the same `description`.
[DEV-2097](https://federal-spending-transparency.atlassian.net/browse/DEV-2097)

Fix Validate Treemap Cells

---

src/js/components/generateFiles/GenerateFilesContent.jsx
src/js/components/generateFiles/components/GenerateFileBox.jsx
src/js/containers/generateFiles/GenerateFilesContainer.jsx

Updating how we get the file url for D file downloads.
Instead of generating the URL on page load or on completion of generation, we just query the backend for a URL every time someone clicks "download" so there's no chance of it expiring before it gets used.
[DEV-1308](https://federal-spending-transparency.atlassian.net/browse/DEV-1308)

DEV-1308: D File URL Generation On Click

---

src/js/containers/AppContainer.jsx

The [Redux Dev Tools Extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) window variable has been renamed in the latest version.
See https://github.com/zalmoxisus/redux-devtools-extension#usage
Removes this console warning:
> `window.devToolsExtension` is deprecated in favor of `window.__REDUX_DEVTOOLS_EXTENSION__`, and will be removed in next version of Redux DevTools: https://git.io/fpEJZ
**JIRA Ticket:**
N/A (technical improvement)
**Mockup:**
N/A

Update Redux dev tools

---

src/js/components/generateDetachedFiles/DateSelect.jsx
src/js/components/generateDetachedFiles/DetachedFileA.jsx
src/js/components/generateDetachedFiles/DownloadFile.jsx
src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx
src/js/containers/generateDetachedFiles/DetachedFileAContainer.jsx
src/js/helpers/generateFilesHelper.js
tests/containers/generateDetachedFiles/DetachedFileAContainer-test.jsx

Forgot to account for detached files in the file generation on click
Had to add a new endpoint to account for how both detached file D and detached file A generation work.
[DEV-1308](https://federal-spending-transparency.atlassian.net/browse/DEV-1308)

DEV-1308: detached file url generation

---

src/js/components/generateDetachedFiles/AgencyToggle.jsx
src/js/components/generateDetachedFiles/DateSelect.jsx
src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx
src/js/components/generateFiles/GenerateFilesContent.jsx
src/js/containers/generateFiles/GenerateFilesContainer.jsx

Add funding toggle to D1 and D2 file types.
`fundingAgency` state property is now part of `d1` and `d2` state properties.
[DEV-2329](https://federal-spending-transparency.atlassian.net/browse/DEV-2329)

DEV-2329 Update D1/D2 funding toggle within DABS

---

src/_scss/pages/help/_content.scss
src/_scss/pages/help/_topButton.scss
src/help/changelog.md
src/help/technical.md
src/help/technicalHistory.md
src/js/components/generateDetachedFiles/DateSelect.jsx
src/js/components/generateFiles/GenerateFilesContent.jsx
src/js/components/help/helpContent.jsx
src/js/components/help/helpPage.jsx
src/js/components/help/helpSidebar.jsx
src/js/components/help/historyPage.jsx
src/js/components/help/resourcesPage.jsx
src/js/components/reviewData/CertificationModal/RevalidateButtons.jsx

Implements styling updates to the Release Notes Archive and Technical Notes Archive without having to migrate from markdown to HTML.
- Re-introduces the markdown injection that was removed in #1005 
- Styling based on `h4`s for dates (`####` in markdown) and `h5` for nested headings
- Fixes the Back to Top button
- Also fixes linting errors
[DEV-2198](https://federal-spending-transparency.atlassian.net/browse/DEV-2198)
**Mockup**
https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/295997419_BFS_USAS_Broker_DABS-FABS_Help_02A

DEV-2198 help page styling

---

Dockerfile

Upgrade docker container used for local development to use node 6.16
Developers have been using node 6.16, and this container was still using 5.
N/A

Bringing frontend Docker in line with node 6.16

---

src/_scss/pages/validateData/headers/headers.scss
src/js/components/reviewData/ReviewDataContent.jsx
src/js/components/validateData/ValidateDataFileComponent.jsx
src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx

Changing the display on validation pages and the DABS review page to reflect that the number of rows now ignores the header.
See above
[DEV-2080](https://federal-spending-transparency.atlassian.net/browse/DEV-2080)
**Mockup**
N/A

DEV-2080: data rows text

---

src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx

Hotfix for staging where uploading new file in FABS, then going to "Upload and Validate New Submission" throws an error about the submission id.
1. Refactored `componentWillReceiveProps` to `componentDidUpdate`
2. Removed redundant `this.state.submissionID` in favor of just using `this.props.params.submissionID`
3. Added conditional to lifecycle method `componentDidUpdate` to only invoke class methods that depend on submission id when submissionID is truthy.
[DEV-2334](https://federal-spending-transparency.atlassian.net/browse/DEV-2334)

[DEV-2334] Fixing SubmissionID is not valid error

---

src/js/containers/submission/SubmissionContainer.jsx

Alisa found a bug in the broker submission page when refreshing the browser on a submission that is already completed will navigate the submission back to the first step.
Removed `validateCurrentStepAndRouteType` when getting a submission. This was useful in earlier iterations when I was still calling `getSubmission` when a user was making updates to the submission. However, once I added the `completedSteps` in state and the logic there is no reason to validate the current step in `getSubmission` considering it is only called on page load.
[DEV-3117](https://federal-spending-transparency.atlassian.net/browse/DEV-3117)

Hotfix Dev-3117 Broker Redirect

---

src/js/components/uploadFabsFile/UploadFabsFilePage.jsx

Fixes a bug that will not show an error message when a user navigates from and existing FABS submission to a non existent FABS submission.
move removeError method call to before getSubmission method call in component update when ids do not match
[DEV-2014](https://federal-spending-transparency.atlassian.net/browse/DEV-2014)

Dev-2014 FABS Error Messaging

---

src/js/GlobalConstants.js
webpack/webpack.dev.config.js
webpack/webpack.prod.config.js

Adds config for devs to use local api and bypass max.gov locally
Sets `GlobalConstants.IS_LOCAL` to env_var
**Mockup**

[local-dev-config] adding config to bypass max.gov locally

---

src/js/containers/addData/SubmissionGuideContainer.jsx
src/js/containers/help/HelpContainer.jsx

Refactored two components to no longer use the deprecated React lifecycle method `componentWillMount`.
- Also updated some imports to absolute paths
- Simplified some boolean logic
[DEV-3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339)
- N/A Design review (if applicable)
- N/A Merged concurrently with Backend
- N/A Unit tests added: working on unit tests for `SubmissionGuideContainer` in a separate branch, outside the scope of this story

Refactor to remove componentWillMount

---

.codeclimate.yml
.eslintrc
.gitignore
package-lock.json
package.json
pull_request_template.md
setup-jasmine-env.js
src/js/components/generateDetachedFiles/PeriodButtonWithTooltip.jsx

Most of the work for this ticket was accomplished by #1111. This cleans up remaining references to the obsolete `/test` directory and updates our linter.
Upgrades the lint rule `no-unused-prop-types` from warning to error and fixes the resulting error.
[DEV-2850](https://federal-spending-transparency.atlassian.net/browse/DEV-2850)
- N/A Unit tests added
- N/A Verified cross-browser compatibility

Dev-2850 clean up tests

---

package-lock.json
package.json
src/js/containers/submissionsTable/AgencyFilterContainer.jsx
src/js/containers/submissionsTable/CreatedByContainer.jsx
src/js/containers/submissionsTable/LastDateModifiedContainer.jsx
src/js/containers/submissionsTable/SubmissionsTableContainer.jsx
src/js/redux/actions/dashboard/appliedFilterActions.js
src/js/redux/actions/dashboard/dashboardFilterActions.js
src/js/redux/reducers/dashboard/appliedFiltersReducer.js
src/js/redux/reducers/dashboard/dashboardFiltersReducer.js
src/js/redux/reducers/index.js
src/js/redux/reducers/submissionsTable/appliedFiltersReducer.js
src/js/redux/reducers/submissionsTable/submissionsTableFiltersReducer.js
tests/redux/dashboard/appliedFiltersReducer-test.js
tests/redux/dashboard/dashboardFiltersReducer-test.js
tests/redux/submissionsTable/submissionsTableFiltersReducer-test.js

"Behind the scenes" setup for maintaining the current state of staged and applied dashboard filters. No impact to end user (yet). 
- Implements dashboard staged & applied filters Redux state, actions, and reducers
- Adds unit tests for the new reducers
- Renames Submissions Table files and functions (formerly called Submissions Dashboard) 
Tangential to [DEV-3609](https://federal-spending-transparency.atlassian.net/browse/DEV-3609) /  prep work for the filter stories [DEV-3657](https://federal-spending-transparency.atlassian.net/browse/DEV-3657) through [DEV-3661](https://federal-spending-transparency.atlassian.net/browse/DEV-3661)
- N/A Verified …

Dashboard redux

---

src/js/components/uploadFabsFile/PublishModal.jsx
src/js/components/uploadFabsFile/UploadFabsFilePage.jsx
src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx
tests/components/uploadFabsFilePage/UploadFabsFilePage-test.jsx

Fixes a bug that prevented error messages from displaying when users navigate to a FABS submission with an invalid ID. 
- The issue found during testing was that the error message would sometimes not be displayed on initial page load, but would show up if you refreshed the page. This PR simplifies the logic in the `UploadFabsFilePage` component and adds a loading state for while the application is fetching metadata for a specific submission. 
- Also includes formatting improvements in the `UploadFabsFileValidation` component
[DEV-2014](https://federal-spending-transparency.atlassian.net/browse/DEV-2014)
**Mockup**
N/A
- N/A Tagged Designer in `#br-frontend` …

DEV-2014 fix FABS submission error bug

---

src/help/changelog.md
src/help/technicalHistory.md

Fixing the underscore formatting in the staging release notes

Hotfix: Sprint 91 Release Notes (fixing underscores)

---

src/js/containers/submission/SubmissionContainer.jsx
tests/containers/dabsSubmissionContainer/SubmissionContainer-test.jsx
tests/containers/dabsSubmissionContainer/mockData.js

Fixes a bug that caused the step to change when refreshing during the DABS submission process. 
- We were making a new API call every time the component mounts, which automatically redirected to the last completed step. The solution was to check whether a step is already indicated in the url params when `componentDidMount` is invoked
- Also refactored the state property `completedSteps` into an array of booleans instead of an object keyed by indices
- Removed redundant `routeParams` prop
- Updated unit tests to prevent mutating the mocked state and props, and to account for the changes above
[DEV-3598](https://federal-spending-transparency.atlassian.net/browse/DEV-3598)
The following are ALL required for the PR to …

DEV-3598 Retain DABS submission step on refresh

---

src/_scss/pages/uploadFabsFile/uploadFabsFile.scss
src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx
src/js/containers/router/RouterRoutes.jsx
src/js/helpers/permissionsHelper.js
tests/helpers/permissionsHelper-test.js

Gives users with `editfabs` permissions the ability to do everything a `fabs` user can do, except publish. 
- Added a new helper to determine the status of the Publish button: `checkFabsPublishPermissions`, which checks for `fabs`
- Modified `checkFabsPermissions` and `checkFabsAgencyPermissions` to also accept `editfabs`
- Simplified some of the logic in the helpers by using [Array.prototype.find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)
[DEV-3525](https://federal-spending-transparency.atlassian.net/browse/DEV-3525)
- N/A All componentWillReceiveProps, componentWillMount, and componentWillUpdate in …

DEV-3525 Fix FABS permissions

---

src/_scss/pages/dashboard/_filterSidebar.scss
src/_scss/pages/dashboard/filters/_quarterPicker.scss
src/js/components/dashboard/DashboardPage.jsx
src/js/components/dashboard/FilterOption.jsx
src/js/components/dashboard/filters/QuarterButton.jsx
src/js/components/dashboard/filters/QuarterPicker.jsx
src/js/containers/dashboard/filters/QuarterFilterContainer.jsx
src/js/redux/actions/dashboard/dashboardFilterActions.js
tests/containers/dashboard/filters/QuarterFilterContainer-test.jsx
tests/containers/dashboard/filters/mockFilters.js

Adds quarter picker UI to the dashboard page.
I will implement the logic to disable some quarters based on the fiscal as part of the FY filter implementation (DEV-3658)
[DEV-3657](https://federal-spending-transparency.atlassian.net/browse/DEV-3657)
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/296021489_Historical-Search-Monthly-Single-Data
- N/A Scheduled Demo including Design/Testing/Front-end OR Provided Instructions for Local Testing above and in JIRA - will demo along with FY filter
- N/A All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future …

DEV-3657 dashboard quarter filter

---

src/_scss/pages/dashboard/_filterSidebar.scss
src/_scss/pages/dashboard/dashboard.scss
src/_scss/pages/dashboard/filters/_fiscalYears.scss
src/js/components/dashboard/DashboardPage.jsx
src/js/components/dashboard/FilterOption.jsx
src/js/components/dashboard/filters/FiscalYear.jsx
src/js/components/dashboard/filters/FiscalYearFilter.jsx
src/js/components/dashboard/filters/QuarterPicker.jsx
src/js/containers/dashboard/filters/FyFilterContainer.jsx
src/js/containers/dashboard/filters/QuarterFilterContainer.jsx
src/js/helpers/dashboardHelper.js
tests/containers/dashboard/filters/FyFilterContainer-test.jsx
tests/containers/dashboard/filters/QuarterFilterContainer-test.jsx
tests/containers/dashboard/filters/mockFilters.js

Adds a fiscal year filter to the dashboard page. 
- Makes an API call to `/latest_certification_period` endpoint from both quarter filter and fiscal year filter containers to determine how many FY checkboxes to render and to support the following logic: 
- Disable future quarters if the current fiscal year is the only FY selected
- Disable Q1 button if 2017 is the only FY selected
- Disable the current fiscal year checkbox if the only quarters selected are greater than the latest quarter that could have been certified for the current FY
- Disable FY 17 if Q1 is the only quarter currently selected
[DEV-3658](https://federal-spending-transparency.atlassian.net/browse/DEV-3658)
**Mockup** …

DEV-3658 dashboard fiscal year filter

---

src/js/components/dashboard/filters/FiscalYear.jsx
src/js/components/dashboard/filters/FiscalYearFilter.jsx
src/js/containers/dashboard/filters/FyFilterContainer.jsx
src/js/containers/dashboard/filters/QuarterFilterContainer.jsx
tests/containers/dashboard/filters/FyFilterContainer-test.jsx
tests/containers/dashboard/filters/QuarterFilterContainer-test.jsx

- Unchecks and clears fiscal years when they become disabled.
- Deselects and clears quarters when they become disabled.
- Disables the "All Fiscal Years" checkbox when any FY is disabled
[DEV-3658](https://federal-spending-transparency.atlassian.net/browse/DEV-3658) (Failed test)

Fix DEV-3658 de-select years & quarters when they become disabled

---

src/js/components/SharedComponents/Typeahead.jsx

When an agency is mistyped it doesn't break the page anymore
Surrounding the input with a div to stop it from confusing the DOM.
[DEV-3561](https://federal-spending-transparency.atlassian.net/browse/DEV-3561)
**Mockup**
N/A

DEV-3561: Agency typeahead mistype error

---

src/_scss/layouts/default/header/_titleBar.scss
src/_scss/layouts/default/header/header.scss
src/js/components/dashboard/DashboardPage.jsx
src/js/components/help/helpPage.jsx
src/js/components/help/resourcesPage.jsx
src/js/components/history/HistoryPage.jsx
src/js/components/submissionsTable/SubmissionsTablePage.jsx

Aligning the page titles with the top bar
Adding CSS to remove padding from the page title. Also adding the page title class to page titles that didn't have it
[DEV-3676](https://federal-spending-transparency.atlassian.net/browse/DEV-3676)
**Mockup**
N/A

DEV-3676: Page title alignment

---

src/_scss/sharedComponents/_radioGroup.scss
src/_scss/sharedComponents/sharedComponents.scss
src/js/components/SharedComponents/RadioGroup.jsx
src/js/components/dashboard/DashboardPage.jsx
src/js/containers/dashboard/filters/FileFilterContainer.jsx
src/js/redux/reducers/dashboard/dashboardFiltersReducer.js

Adds the file radio buttons to the dashboard page.
- JSX does not support `<radiogroup>` so I've implemented a reusable radio group component that accepts multiple columns of options, each option with a `value` and a `label`.
- When a new option is selected, the Redux `dashboardFilters.file` state is updated
- This PR also updates all filter labels to be plural (`Quarter` -> `Quarters`, `Fiscal Year` -> `Fiscal Years`)
[DEV-3659](https://federal-spending-transparency.atlassian.net/browse/DEV-3659)
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/296021489_Historical-Search-Monthly-Single-Data
- N/A All componentWillReceiveProps, …

DEV-3659 files filter

---

src/js/containers/SharedContainers/AgencyListContainer.jsx
src/js/containers/submissionsTable/AgencyFilterContainer.jsx

Fixing a bug where all agencies would sometimes be displayed instead of the permission-based list. Also removing all agencies from the filter list (per discussion) and only listing agencies the user has access to.
We were using the cached version of the agency list, which wasn't great because we called `list_all_agencies` in a couple places. This meant that when users went to make a submission after being on one of these pages they would see every agency instead of just the ones they had access to.
[DEV-3785](https://federal-spending-transparency.atlassian.net/browse/DEV-3785)
**Mockup**
N/A
- Scheduled Demo including Design/Testing/Front-end OR Provided …

DEV-3785: agency list api call

---

src/_scss/components/tooltip/_warningTooltip.scss
src/_scss/pages/dashboard/dashboard.scss
src/_scss/pages/dashboard/filters/_fiscalYears.scss
src/_scss/pages/dashboard/filters/_quarterPicker.scss
src/js/components/SharedComponents/WarningTooltip.jsx
src/js/components/dashboard/filters/FiscalYear.jsx
src/js/components/dashboard/filters/FiscalYearFilter.jsx
src/js/components/dashboard/filters/QuarterButton.jsx
src/js/components/dashboard/filters/QuarterPicker.jsx

Adds warning tooltips to the quarter selector for disabled quarters and fiscal years
- Adds a single warning tooltip instance to the quarter filter, and one to the fiscal year filter (this approach ensures only one tooltip will display at a time, even when there are multiple disabled quarters/years). 
- The message depends on which quarter/year triggered the tooltip (stored in state). `0` indicates that the tooltip should be hidden or has not yet been triggered. 
- The quarter buttons are pseudo-disabled, so they are still focusable, which allows keyboard users to trigger the warning tooltip  
[DEV-3757](https://federal-spending-transparency.atlassian.net/browse/DEV-3757)
**Mockup** …

DEV-3757 warning tooltips

---

src/js/components/crossFile/CrossFileOverlay.jsx
src/js/components/validateData/ValidateDataInProgressOverlay.jsx
src/js/containers/router/RouterRoutes.jsx

After running a burp scan, it was discovered open redirection issues were possible. This aims to fix that.
- When logging out, the redirect path that's provided via the URL is whitelisted against valid routes. If the path is invalid, it resets it to an empty string and the user would log back into the front page.
- Also removed a couple instances where we were basing our links off of `location.href`
[OPS-651](https://federal-spending-transparency.atlassian.net/browse/OPS-651)
**Mockup**
N/A
- Tagged Designer in `#br-frontend` Slack …

OPS-651: Resolving Open Redirection

---

src/_scss/abstract/variables/shame.scss
src/_scss/components/inputs/_generic.scss
src/_scss/pages/dashboard/_filterSidebar.scss
src/_scss/pages/dashboard/filters/_dashboardAgencyFilter.scss
src/js/components/dashboard/DashboardPage.jsx
src/js/components/dashboard/FilterOption.jsx
src/js/components/dashboard/filters/DashboardAgencyFilter.jsx
src/js/components/dashboard/filters/ShownValue.jsx
src/js/containers/dashboard/filters/DashboardAgencyFilterContainer.jsx
src/js/redux/actions/dashboard/dashboardFilterActions.js
src/js/redux/reducers/dashboard/dashboardFiltersReducer.js
tests/containers/dashboard/filters/DashboardAgencyFilterContainer-test.jsx
tests/containers/dashboard/filters/mockFilters.js
tests/redux/dashboard/dashboardFiltersReducer-test.js

Adding an agency filter to the dashboard
- If the user only has 1 agency, it defaults to it and prevents removing it
- If the user has access to multiple agencies, there's a bar that can be searched (same searching as all other agency searches on the site) and the agency can be removed
- Changed behavior from the ticket to 2 letters typed since that's the default for all other agency searches on the site
- Selecting an agency stages the filter and displays it below the dropdown
- Selecting a different agency overwrites the currently staged one
- The selected agency isn't listed in the dropdown
[DEV-3661](https://federal-spending-transparency.atlassian.net/browse/DEV-3661)
**Mockup** …

DEV-3661: Agency filter

---

src/_scss/pages/dashboard/_chooseFilters.scss
src/_scss/pages/dashboard/_filterSidebar.scss
src/_scss/pages/dashboard/dashboard.scss
src/_scss/pages/dashboard/filters/_submitButton.scss
src/js/components/dashboard/FilterSidebar.jsx
src/js/components/dashboard/filters/SubmitButton.jsx
src/js/containers/dashboard/filters/RulesFilterContainer.jsx
src/js/containers/dashboard/filters/SubmitButtonContainer.jsx
src/js/redux/actions/dashboard/appliedFilterActions.js
src/js/redux/reducers/dashboard/appliedFiltersReducer.js
tests/containers/dashboard/filters/RulesFilterContainer-test.jsx
tests/containers/dashboard/filters/SubmitButtonContainer-test.jsx
tests/containers/dashboard/filters/mockFilters.js
tests/redux/dashboard/appliedFiltersReducer-test.js

Adds the "Apply Filters" and "Reset Filters" buttons to the dashboard sidebar.
- Components are very similar to USAS [SearchSidebarSubmitContainer](https://github.com/fedspendingtransparency/usaspending-website/blob/dev/src/js/containers/search/SearchSidebarSubmitContainer.jsx) and [SearchSidebarSubmit](https://github.com/fedspendingtransparency/usaspending-website/blob/dev/src/js/components/search/SearchSidebarSubmit.jsx)
- Removed `setAppliedFilterCompletion` logic, since in this case the submit container itself isn't kicking off an API request (the visualizations will watch for changes to the applied filters) 
[DEV-3662](https://federal-spending-transparency.atlassian.net/browse/DEV-3662)
**Mockup** …

DEV-3662 dashboard apply & reset filters

---

src/_scss/pages/dashboard/dashboard.scss
src/js/components/dashboard/DashboardPage.jsx

Fixes a bug causing the main content of the dashboard to extend beyond the width of the header when changing the window size.
- Adds a new wrapper and overrides `@include flex-direction(column);` that applied to `usa-da-site_wrap`
N/A
- N/A Scheduled Demo including Design/Testing/Front-end OR Provided Instructions for Local Testing above and in JIRA 
- N/A Design review completed
- N/A All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item …

Fix dashboard responsive content width

---

src/_scss/sharedComponents/_limitSelector.scss
src/js/components/SharedComponents/table/TableLimit.jsx

Updating dropdown to just use the default select
The functionality was already there, this is styling and accessibility updates. These do NOT match the styling in the mockup but this was discussed and "as close as possible" was achieved.
[DEV-3896](https://federal-spending-transparency.atlassian.net/browse/DEV-3896)
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/screens/296021868
Author: 
Reviewer(s):

DEV-3896: Result limit dashboard table

---

src/js/containers/dashboard/graph/WarningsInfoGraphContainer.jsx
tests/containers/dashboard/graph/WarningsInfoGraphContainer-test.jsx

Fixes a bug that caused the legend to sometimes be generated incorrectly.
The previous implementation expected the rule label to be the first property in each rule object. The fix references the property name instead of using an index.
[DEV-3664](https://federal-spending-transparency.atlassian.net/browse/DEV-3664)
Reviewer(s):

Fix graph legend

---

src/js/components/dashboard/graph/BarChartStacked.jsx
src/js/dataMapping/dashboard/fileLabels.js

- Adds more colors to the legend to allow for up to 17 rules
- Centers the tooltip pointer on the vertical middle of each stack to avoid confusion for smaller stacks
[DEV-3664](https://federal-spending-transparency.atlassian.net/browse/DEV-3664)
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/296021489_Historical-Search-Monthly-Single-Data
Author: 
Reviewer(s):

Warmfix add graph colors

---

src/js/helpers/periodPickerHelper.js

Reporting period dates have changed slightly for FY 2020. This ensures periods become available in the period picker the day after the reporting window has closed. 
[DEV-4011](https://federal-spending-transparency.atlassian.net/browse/DEV-4011)
Author: 
Reviewer(s):

DEV-4011 Update reporting schedule

---

src/_scss/pages/dashboard/table/_dashboardPagination.scss
src/_scss/sharedComponents/_goTo.scss
src/js/components/SharedComponents/DropdownTypeahead.jsx
src/js/components/SharedComponents/Typeahead.jsx
src/js/components/SharedComponents/autocomplete/Autocomplete.jsx
src/js/components/SharedComponents/table/TableGoTo.jsx
src/js/components/dashboard/table/DashboardTablePagination.jsx
src/js/components/generateFiles/components/DatePicker.jsx
src/js/dataMapping/keyMappings.js

Adding a "go to" to the historical dashboard table
- Go button is disabled if a valid value isn't entered into the input
- Enter key works only if a valid value is entered
- Added key code mappings so we don't have to know the number to check for keys
[DEV-3666](https://federal-spending-transparency.atlassian.net/browse/DEV-3666)
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/screens/296021489
NOTE: After discussion with design team, the "Go to page" message and the input box are flipped, designer not available as of making this PR to update mocks
Author: 
Reviewer(s):

DEV-3666: historical dashboard table go to

---

src/_scss/layouts/default/header/_menuBar.scss
src/js/components/SharedComponents/navigation/NavbarTab.jsx

Read-only users can notice a disabled button in the NavBar that's inconsistent with the site's style. This fixes it to its intended disabled styling.
- It seems they were `buttons` even though the styling was based on `anchors`. Updating the style to include buttons.
- *Note*: This does contribute to the AXE issue ` Elements must have sufficient color contrast` by the disabled styling design. 
[DEV-3717](https://federal-spending-transparency.atlassian.net/browse/DEV-3717)
**Mockup**
N/A
Author: 
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible …

DEV-3717: Disabled/Coming Soon NavBar

---

src/_scss/pages/dashboard/filters/_quarterPicker.scss
src/_scss/pages/dashboard/table/_dashboardTable.scss
src/js/components/dashboard/table/DashboardTable.jsx

Fixes two Dashboard bugs in Internet Explorer.
- Sets each `<li>` element in the quarter picker to `display: flex`
- Lets the browser handle column widths in the table; prevent wrapping in the headers (and file buttons)
[DEV-4089](https://federal-spending-transparency.atlassian.net/browse/DEV-4089) and [DEV-4088](https://federal-spending-transparency.atlassian.net/browse/DEV-4088)
Author: 
Reviewer(s):

Warmfix DEV-4089  & DEV-4088

---

src/_scss/pages/validateData/fileItem/bottomSide/_table.scss
src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx

Updating the CSS for validation errors/warnings table so words don't break in the middle unless they're longer than the column
N/A
[DEV-2174](https://federal-spending-transparency.atlassian.net/browse/DEV-2174)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-2174: text break validation errors

---

src/_scss/components/tables/_scrollableTable.scss
src/_scss/pages/validateData/fileItem/bottomSide/_table.scss

Missed one of the scrollable tables in the last PR
No idea why we were always breaking the word, just removing that from the CSS for scrollable tables
[DEV-2174](https://federal-spending-transparency.atlassian.net/browse/DEV-2174)
**Mockup**
N/A
Author: 
- All componentWillReceiveProps in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339) …

DEV-2174: Text break cross file

---

src/js/components/submissionsTable/HistoryLink.jsx
src/js/containers/crossFile/CrossFileGenerateModalContainer.jsx

Removes a deprecated React pattern in preparation for upgrading to React v16.
Removes the last few instances of accessing `PropTypes` via the main React package.
[DEV-1755](https://federal-spending-transparency.atlassian.net/browse/DEV-1755)
Author: 
Reviewer(s):

DEV-1755 Complete migration to prop-types

---

src/js/components/SharedComponents/ErrorMessageOverlay.jsx
src/js/components/submissionsTable/SubmissionsTable.jsx
src/js/components/submissionsTable/SubmissionsTableContent.jsx
src/js/containers/submissionsTable/SubmissionsTableContainer.jsx
src/js/helpers/submissionListHelper.js
tests/containers/submissionsTable/SubmissionsTableContainer-test.jsx

Adding an error message to the submission tables when an error occurs on loading, this should cover any bad filters for IE as well.
- Added the ability to pass a specific message to the error overlay
[DEV-2123](https://federal-spending-transparency.atlassian.net/browse/DEV-2123)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-2123: submission filters decimals ie

---

package.json
src/js/helpers/periodPickerHelper.js
tests/helpers/periodPickerHelper-test.js

Updates the Generate Detached File A fiscal year and period dropdowns to correctly handle dates from 12/31 to 1/16
- We were attempting to use the inclusivity parameter with moment.js's `isBetween` function, but the version of moment.js we were using did not support it. See https://momentjscom.readthedocs.io/en/latest/moment/05-query/06-is-between/. 
- Period 2 before 1/1 and period 2 after 1/1 needed to be checked for in separate conditions
[DEV-4186](https://federal-spending-transparency.atlassian.net/browse/DEV-4186)
Author: 
Reviewer(s):

Warmfix DEV-4186 period picker inclusivity

---

package-lock.json
package.json

Changes the component library dependency to point to the latest release, [v0.2.0](https://github.com/fedspendingtransparency/data-transparency-ui/releases/tag/v0.2.0).

Changed data-transparency-ui to v0.2.0

---

src/js/components/reviewData/ReviewDataContent.jsx
src/js/components/reviewData/ReviewDataPage.jsx
src/js/components/uploadFabsFile/UploadFabsFilePage.jsx
src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx
src/js/containers/history/HistoryContainer.jsx
src/js/containers/review/ReviewDataContainer.jsx
src/js/containers/uploadFabsFile/UploadFabsFilePageContainer.jsx
tests/components/uploadFabsFilePage/UploadFabsFilePage-test.jsx
tests/components/uploadFabsFilePage/mockData.js

Fixes a bug causing the `/FABSAddData/{submission id}` route to load incorrectly.
- In the new router setup, url params are nested in the `computedMatch` object.
- Also fixes a similar bug for the DABS Review Data page
Relates to [DEV-3394](https://federal-spending-transparency.atlassian.net/browse/DEV-3394)
**Testing**
Go to https://broker-dev.usaspending.gov/#/FABSAddData/2125. The submission status for the previously uploaded file should display instead of the agency selector / upload component.
Author: 
Reviewer(s):

Fix FABS submission status

---

src/_scss/layouts/default/header/_titleBar.scss
src/_scss/pages/help/_topNav.scss
src/js/components/help/historyPage.jsx

Fixes a bug causing the help page sub-navigation to display inconsistently. 
- Places the `HelpNav` component nested under the `.display-2` div on the History page to match other help pages
- Removes unnecessarily repeated CSS 
- Moves to flex instead of float to position the help nav
[DEV-4270](https://federal-spending-transparency.atlassian.net/browse/DEV-4270)
Author: 
Reviewer(s):

DEV-4270 help nav styling

---

src/js/components/history/HistoryPage.jsx
src/js/components/reviewData/CertificationModal/ReviewDataCertifyModal.jsx
src/js/containers/history/HistoryContainer.jsx

- Fixes a bug that prevented users from being redirected to the Submission Table after certifying.
- Fixes a bug that prevented the Submission History page from loading the correct information.
DEV-4431
- Uses react-router `Redirect` 
- Corrects the url (`/submissionsTable` --> `/submissionsTable`)
DEV-4432
- Accesses the url param for submission ID via the method necessary for the updated router
- Passes the correct `activeTab` prop to the History Page
[DEV-4431](https://federal-spending-transparency.atlassian.net/browse/DEV-4431),
[DEV-4432](https://federal-spending-transparency.atlassian.net/browse/DEV-4432)
**Local Testing**
DEV-4431
- On the Review Data page, click the "Certify & Publish" button to open the …

Hotfix DEV-4431 & DEV-4432

---

src/js/components/history/HistoryTable.jsx

Fixes a bug preventing the download files from showing up on the history page. 
Correction to [this sprint 99 change](https://github.com/fedspendingtransparency/data-act-broker-web-app/commit/bf693ccf5855550e26585d1974041a2a6a1f065f#diff-bdbaf64e22e6aa83fac6d05502b2d726L98). I misread the if statement as `!this.isUnmounted`.
[DEV-4432](https://federal-spending-transparency.atlassian.net/browse/DEV-4432) (Download files are showing up in prod)
**Testing**
From the DABS Certified submission table, click the calendar icon to go to a Submission History page. Download links should be listed in the right-hand column. 
Author: 
- N/A (adding back previously existing …

Warmfix History Page Download Files

---

src/js/components/dashboard/DashboardPage.jsx

- Ensures dashboard sub-routes are case-insensitive (`dashboard/Active` redirects to `dashboard/active`)
- Redirects invalid urls params (e.g. `dashboard/something`) to the 'Page Not Found' screen
Follow up to [DEV-4413](https://federal-spending-transparency.atlassian.net/browse/DEV-4413)
Author: 
Reviewer(s):

Warmfix DEV-4413 handle invalid dashboard routes

---

src/js/containers/dashboard/filters/SubmitButtonContainer.jsx
tests/containers/dashboard/filters/SubmitButtonContainer-test.jsx

Allows users to apply active dashboard filters when required filters have been selected.
[DEV-4292](https://federal-spending-transparency.atlassian.net/browse/DEV-4292), [DEV-4301](https://federal-spending-transparency.atlassian.net/browse/DEV-4301)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/296030436_Active_-_MVP_-_Entry_5
Author: 
Reviewer(s):

DEV-4292 apply active filters

---

src/js/containers/dashboard/filters/CreatedByFilterContainer.jsx
tests/containers/dashboard/filters/CreatedByFilterContainer-test.jsx

Fixes a bug with the Created By filter in staging.
Displays the email address associated with the account when no name is available.
Follow up to [DEV-4288](https://federal-spending-transparency.atlassian.net/browse/DEV-4288)
Author: 
Reviewer(s):

DEV-4288 Fix Created By filter

---

src/js/containers/dashboard/filters/DashboardAgencyFilterContainer.jsx
tests/containers/dashboard/filters/DashboardAgencyFilterContainer-test.jsx

Fixes a bug that prevented the (single) agency a user is assigned to from showing up in the agency filter when switching between the active & historical dashboards.
[DEV-4287](https://federal-spending-transparency.atlassian.net/browse/DEV-4287)
**Testing:**
Login as a user with access to only one agency. Visit the DABS Dashboard, switch between Active and Historical dashboards. The agency tag for the agency to which you are assigned should be present in the agency filter (it might take a moment to load).
Author: 
Reviewer(s):

Fix DEV-4287 single agency filter

---

package-lock.json
package.json

Updating package.json and package-lock.json to new release of DT UI. No integration changes are necessary as @ebdabbs already is using v0.2.0 which has the new pagination styles and props.
Reviewer(s):
`N/A` Design review completed
`N/A` Merged concurrently with [Backend#1234](https://github.com/fedspendingtransparency/data-act-broker-backend/pull/1234)

[DEV-4254] Updating to Data Transparency UI Release 1.0.0

---

src/_scss/pages/dashboard/filters/_submissionIdFilter.scss

Prevents the `Add` button from getting cut off in IE.
[DEV-4290](https://federal-spending-transparency.atlassian.net/browse/DEV-4290)
Author: 
Reviewer(s):

DEV-4290 fix submission filter button IE

---

src/_scss/layouts/login/_topBanner.scss
src/js/components/SharedComponents/BannerRow.jsx
src/js/components/addData/AddDataMeta.jsx
src/js/components/reviewData/ReviewDataContent.jsx
src/js/components/reviewData/ReviewDataPage.jsx
src/js/components/submission/SubmissionHeader.jsx
src/js/components/submission/SubmissionPage.jsx
src/js/containers/review/ReviewDataContainer.jsx
src/js/containers/submission/SubmissionStepsContainer.jsx
src/js/helpers/agencyHelper.js
tests/containers/dabsSubmissionContainer/SubmissionStepsContainer-test.jsx

Adds a "test submission" banner to let users know when they are looking at a submission for an agency that already has a certified submission for the same fiscal quarter. 
[DEV-4519](https://federal-spending-transparency.atlassian.net/browse/DEV-4519)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/296030458_DEV_3800-_Test_Submission
Author: 
Reviewer(s):

DEV-4519 test submission banner

---

src/js/components/dashboard/SelectSubmissionTable.jsx
src/js/helpers/submissionPeriodHelper.js
tests/helpers/submissionPeriodHelper-test.js

Changes the time period column to display monthly submissions in the format `September 2019` instead of `09/2019`
Fix for [DEV-4303](https://federal-spending-transparency.atlassian.net/browse/DEV-4303)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/296030438_Active_-_MVP_-_Entry_7
Author: 
Reviewer(s):

DEV-4303 spell out months in time period column

---

src/js/components/reviewData/CertificationModal/RevalidateDataModal.jsx

Redirects the user to step one of the submission process after clicking the Revalidate button.  
- Uses react router Redirect component instead of `setStep`, which has been removed. 
- Switches the close modal button to a Font Awesome icon
[DEV-4784](https://federal-spending-transparency.atlassian.net/browse/DEV-4784)
Author: 
Reviewer(s):

DEV-4784 fix revalidate button redirect

---

src/_scss/layouts/default/header/_userMenu.scss
src/js/app.jsx
src/js/components/SharedComponents/navigation/NavigationComponent.jsx
src/js/components/SharedComponents/navigation/UserButton.jsx
src/js/helpers/permissionsHelper.js
tests/helpers/permissionsHelper-test.js

Adds the settings button to the dropdown when clicking on the user's name.
Button is only available to certifiers and site admins and only on QAT and below (will not be visible in prod)
[DEV-4293](https://federal-spending-transparency.atlassian.net/browse/DEV-4293)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/screens/296030441
Author: 
Reviewer(s):

DEV-4293: settings navigation box

---

src/_scss/pages/dashboard/_dashboardTabs.scss
src/js/components/dashboard/DashboardTab.jsx

Fixes the tab that links to the historical dashboard in Internet Explorer
* Issue was caused by a link nested under a button (a temporary measure while Active dashboard is dark-released)
[DEV-4625](https://federal-spending-transparency.atlassian.net/browse/DEV-4625)
Author: 
Reviewer(s):

DEV-4625 fix Historical tab link in IE

---

src/_scss/layouts/default/header/_userMenu.scss
src/_scss/pages/modals/modals.scss
src/_scss/pages/modals/settings/_settingsModal.scss
src/js/components/SharedComponents/navigation/NavigationComponent.jsx
src/js/components/SharedComponents/navigation/UserButton.jsx
src/js/components/settings/SettingsModal.jsx

Basic layout for the settings modal
Modal works like all other modals with tabbing/keyboard/mouse/overlay click. Navigation dropdown closes when settings modal is opened.
[DEV-4294](https://federal-spending-transparency.atlassian.net/browse/DEV-4294)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/screens/296030442
Author: 
Reviewer(s):

DEV-4294: settings modal layout

---

src/_scss/pages/dashboard/_dashboardTabs.scss
src/_scss/pages/dashboard/dashboard.scss
src/js/components/dashboard/ActiveDashboard.jsx
src/js/components/dashboard/ActiveDashboardOverview.jsx
src/js/components/dashboard/ErrorLevelTab.jsx
src/js/components/dashboard/impacts/ActiveDashboardImpacts.jsx
src/js/components/dashboard/table/ActiveDashboardTable.jsx
src/js/containers/dashboard/ActiveDashboardImpactsContainer.jsx
src/js/containers/dashboard/graph/SignificanceGraphContainer.jsx
src/js/containers/dashboard/table/ActiveDashboardTableContainer.jsx

Adds the ability to switch the active dashboard between errors and warnings view
- Updates existing containers to ensure a new API call is made with the correct `error_level` param when switching between errors and warnings
- Stores the error level in the `ActiveDashboard` component local state
- Adds whitespace above the filter sidebar and historical dashboard content for consistent vertical alignment
[DEV-4318](https://federal-spending-transparency.atlassian.net/browse/DEV-4318)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/296030448_Active_-_MVP_-_1
Author: 
Reviewer(s):

DEV-4318 Errors & Warnings tabs

---

src/_scss/pages/modals/reviewData/_selectedUsers.scss
src/js/components/reviewData/ReviewDataContent.jsx
src/js/components/reviewData/ReviewDataNotifyModal.jsx

Updating the "Notify Another User" functionality to use an equivalent `mailto`.
N/A
[DEV-4812](https://federal-spending-transparency.atlassian.net/browse/DEV-4812)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-4812: MAILTO Solution to "Notify Another User" (warmfix)

---

src/js/components/dashboard/impacts/ActiveDashboardImpacts.jsx

During demos, it was discovered that the gauges data all pointed to the low impact counts. This properly distinguishes them.
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):

Fix: Update ActiveDashboardImpacts Data per Gauge

---

src/js/components/SharedComponents/SubmissionWarningBanner.jsx

Simply updating the Banner to be more explicit for when users have the option to revert their submission.
N/A
[DEV-4942](https://federal-spending-transparency.atlassian.net/browse/DEV-4942)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-4942: Updating DABS Banner to be more explicit

---

src/js/components/dashboard/graph/active/SignificanceCircle.jsx
src/js/components/dashboard/graph/historical/StackedBar.jsx

Makes elements representing rules in DABS Dashboard graphs (stacked bars for Historical and circles for Active) keyboard accessible, and therefore able to trigger the tooltips via keyboard, in Internet Explorer.
Internet Explorer does not support `tabIndex`, which is our primary method for making otherwise non-interactive elements keyboard accessible. The `focusable` attribute should be added as well for IE. See https://allyjs.io/tutorials/focusing-in-svg.html#browser-compatibility.
[DEV-4316](https://federal-spending-transparency.atlassian.net/browse/DEV-4316) (Failed Test)
Author: 
Reviewer(s):

DEV-4316 Fix Dashboard graph tooltips in IE

---

src/_scss/pages/modals/settings/_impactDropdown.scss
src/_scss/pages/modals/settings/_settingsModal.scss
src/js/components/settings/SettingsModal.jsx
src/js/components/settings/table/ImpactDropdown.jsx
src/js/components/settings/table/SettingsTable.jsx
src/js/containers/settings/SettingsTableContainer.jsx
src/js/redux/actions/settingsActions.js
src/js/redux/reducers/index.js
src/js/redux/reducers/settingsReducer.js
tests/redux/mockData.js
tests/redux/settingsReducer-test.js

Allow users to select an impact of low, medium, or high for each rule from dropdowns in the settings modal table. 
- Uses the `Picker` component from the component library
- Sets up Redux store for the saved settings and staged settings; adds an action for updating the impact of a rule
- Includes unit tests for the reducer
[DEV-4821](https://federal-spending-transparency.atlassian.net/browse/DEV-4821), subtask of [DEV-4297](https://federal-spending-transparency.atlassian.net/browse/DEV-4297)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/296030446_Active_-_Settings_5
Author: 
Reviewer(s):

DEV-4821 settings impact dropdowns

---

src/js/components/history/HistoryTable.jsx
src/js/helpers/submissionListHelper.js

Updating to use new table ID as the key
Just changing which key is being accessed/sent back
[DEV-5143](https://federal-spending-transparency.atlassian.net/browse/DEV-5143)
**Mockup**
N/A
Author: 
-  Verified mobile/tablet/desktop/monitor responsiveness
Reviewer(s):

DEV-5143: publish history table

---

src/js/components/addData/AddDataMeta.jsx
src/js/helpers/agencyHelper.js

Simply making sure the FE doesn't break with the changes to `check_year_quarter`
The quarter functionality still works fine. The monthly aspect of this check will not be implemented until next sprint.
[DEV-5020](https://federal-spending-transparency.atlassian.net/browse/DEV-5020)
**Mockup**
N/A
Author: 
Reviewer(s):

Updating check_year_quarter logic per backend changes

---

src/js/components/reviewData/CertificationModal/ReviewDataCertifyModal.jsx
src/js/helpers/reviewHelper.js

Renaming the endpoint used by the frontend so it keeps working until the frontend work is done
Using the `publish_and_certify_dabs_submission` endpoint instead of the `certify_submission` endpoint because it was renamed
[DEV-5144](https://federal-spending-transparency.atlassian.net/browse/DEV-5144)
**Mockup**
N/A
Author:  …

DEV-5144: separate publish certify

---

webpack/webpack.dev.config.js
webpack/webpack.prod.config.js

This allows environmental settings for the CAS_ROOT setting. 
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):

OPS Fix: Populating Webpack config based on CAS_ROOT environment variable

---

src/js/components/reviewData/ReviewDataContent.jsx

If a monthly submission has been published but not certified, publish & certify button opens certify modal
We only want to certify, not re-publish if they're certifying past the deadline without changes
[DEV-5514](https://federal-spending-transparency.atlassian.net/browse/DEV-5514)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-5514: Publish certify past deadline

---

src/_scss/pages/reviewData/leftSide/leftSide.scss
src/js/components/reviewData/ReviewDataNarrative.jsx
src/js/components/reviewData/ReviewDataNarrativeDropdown.jsx

Making the selected file displayed in the comment file dropdown be the correct one even after a user saves their comments.
- The value of the dropdown is now whatever the current file is in the state of the parent so it's properly reflected everywhere.
- Bonus: Fixed that darn `large_file_icon.png` console error that we kept getting constantly
[DEV-4831](https://federal-spending-transparency.atlassian.net/browse/DEV-4831)
**Mockup**
N/A
Author: 
- Verified that this PR does not create any …

DEV-4831: dabs comment display save

---

src/js/components/history/HistoryHeader.jsx
src/js/containers/generateFiles/GenerateFilesContainer.jsx
tests/containers/generateFiles/GenerateFilesContainer-test.jsx

Updating the displays for reporting period to use P## for monthly submissions.
- Period 2 specifically is P01-P02/YYYY format for periods.
- Swapped to using the actual reporting periods from the submission in the database when generating default D1/D2 dates instead of manually deriving them.
[DEV-5482](https://federal-spending-transparency.atlassian.net/browse/DEV-5482)
[DEV-5534](https://federal-spending-transparency.atlassian.net/browse/DEV-5534)
**Mockup**
N/A
Author: 
- Verified …

DEV-5482/5534: reporting period displays

---

src/js/components/submissionsTable/SubmissionsTable.jsx
tests/containers/submissionsTable/mockSubmissionListHelper.js

Updating keys based on changes to the backend
- Bonus: Fixed the key being sent back to the sort so the sort works on that column now.
[DEV-5846](https://federal-spending-transparency.atlassian.net/browse/DEV-5846)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-5846: submission history date

---

src/_scss/pages/generateDetachedFiles/generateDetachedFiles.scss
src/js/components/generateDetachedFiles/DateSelect.jsx
src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx

Adding checkbox to include FPDS element numbers in detached D1 generation
The technical details can be placed here for the knowledge of other developers. Any detailed caveats or specific deployment steps should be outlined here.
[DEV-5027](https://federal-spending-transparency.atlassian.net/browse/DEV-5027)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-5027: Detached d1 element numbers

---

src/_scss/components/buttons/_primary.scss
src/_scss/pages/addData/_content.scss
src/_scss/pages/addData/fields/_submit.scss
src/js/components/SharedComponents/BannerRow.jsx
src/js/components/SharedComponents/SubmissionWarningBanner.jsx
src/js/components/SharedComponents/autocomplete/Autocomplete.jsx
src/js/components/addData/AddDataMeta.jsx
src/js/components/addData/metadata/DateDropdown.jsx
src/js/components/addData/metadata/DateTypeField.jsx
src/js/components/addData/metadata/SubmissionTypeField.jsx
src/js/components/addData/metadata/SubmitComponent.jsx
src/js/components/dashboard/ActiveDashboardOverview.jsx
src/js/components/dashboard/SelectSubmissionTable.jsx
src/js/components/dashboard/filters/RulesFilter.jsx
src/js/components/dashboard/graph/active/SignificanceCircle.jsx
src/js/components/dashboard/graph/historical/StackedBar.jsx
src/js/components/help/resourcesContent.jsx
src/js/components/login/LoginMax.jsx
src/js/containers/dashboard/graph/SignificanceGraphContainer.jsx
src/js/helpers/dashboardHelper.js

Checking if there are other submissions already published in the period when choosing the submission type in a new DABS upload as opposed to waiting for the user to hit the `Submit` button.
+ Moved the published submission check to change of date or agency (if date has already been selected)
+ Cleaned up a bunch of legacy code in the component to make future updates easier
+ Some more linter cleanup
[DEV-5312](https://federal-spending-transparency.atlassian.net/browse/DEV-5312)
**Mockup**
https://bahdigital.invisionapp.com/share/ETIAEWIPC7X#/screens/296048800
Author: 
Reviewer(s):

DEV-5312: submission type check

---

src/js/components/crossFile/CrossFileOverlay.jsx
src/js/components/uploadFabsFile/UploadFabsFileBox.jsx
src/js/components/validateData/ValidationOverlay.jsx
src/js/containers/addData/AddDataContainer.jsx
src/js/containers/crossFile/CrossFileUploadButtonContainer.jsx
src/js/helpers/util.js

Disable the upload button if a bad file type is staged so the user can't even try to upload it
The backend handles bad file types but it's good practice to also have the frontend just prevent the user from uploading
[DEV-6086](https://federal-spending-transparency.atlassian.net/browse/DEV-6086)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-6086: prevent wrong file type upload

---

src/js/components/crossFile/CrossFileContent.jsx
src/js/components/crossFile/CrossFileOverlay.jsx
src/js/containers/crossFile/CrossFileContentContainer.jsx

Simply adds a blocking error overlay when the cross-file job has failed (copied from the first page's error overlay)
* Like other error overlays, the status is unchanged such that the user can restart the job if they reupload a file.
[DEV-2084](https://federal-spending-transparency.atlassian.net/browse/DEV-2084)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-2084: Cross File Failed Overlay

---

src/js/components/crossFile/components/FileWarning.jsx

Allows users to successfully stage 2 files in the same error/warning cross-file box without breaking the page.
Swapping to a check on componentDidUpdate because the callback wasn't happening at the right time
[DEV-6154](https://federal-spending-transparency.atlassian.net/browse/DEV-6154)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-6154: Staged cross files

---

src/_scss/pages/landing/blocks/_blockItem.scss
src/_scss/pages/landing/blocks/blocks.scss

Fixing what little overflow was left on the `what to submit` link.
Also discovered a visual bug with the boxes at exactly 992px and fixed it.
[DEV-1940](https://federal-spending-transparency.atlassian.net/browse/DEV-1940)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-1940: homepage overflow

---

src/_scss/pages/addData/_content.scss
src/js/components/addData/SubmissionGuideContent.jsx
src/js/components/addData/metadata/SubmissionTypeField.jsx

Adding warnings about test submissions expiring before creating the submission
N/A
[DEV-6222](https://federal-spending-transparency.atlassian.net/browse/DEV-6222)
[DEV-6223](https://federal-spending-transparency.atlassian.net/browse/DEV-6223)
**Mockup**
https://bahdigital.invisionapp.com/share/7TIAF69AWB3#/screens
https://bahdigital.invisionapp.com/share/6CIAF6A7FBZ#/screens
Author: 
- Verified that this PR does not create any *new* accessibility issues …

DEV-6222/6223: Expiring submission warnings

---

src/js/components/landing/recentActivity/DeleteModal.jsx

Disabling the delete button after a user deletes a submission
N/A
[DEV-6180](https://federal-spending-transparency.atlassian.net/browse/DEV-6180)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-6180: Disable delete button on click

---

src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx

Disabling the publish button if the status of the job isn't finished
N/A
[DEV-4418](https://federal-spending-transparency.atlassian.net/browse/DEV-4418)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-4418: check status logic update

---

src/js/components/generateFiles/GenerateFilesContent.jsx

Making the update error functions be able to access the props
Functions couldn't access props because they weren't bound anywhere
[DEV-6470](https://federal-spending-transparency.atlassian.net/browse/DEV-6470)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-6470: Generate D file manual date entry

---

src/_scss/pages/reviewData/narrative/narrative.scss
src/js/components/reviewData/Narrative/ReviewDataNarrativeCollapsed.jsx

Displaying which files have saved comments when the comment box is collapsed.
N/A
[DEV-6653](https://federal-spending-transparency.atlassian.net/browse/DEV-6653)
**Mockup**
https://bahdigital.invisionapp.com/share/5BIAFVXZMV7#/screens/296054060
Author: 
Reviewer(s):

DEV-6653: collapsed comments text change

---

src/js/components/reviewData/Narrative/ReviewDataNarrative.jsx

Removing React Prompt from the comments section
The React Prompt component has a bug where it doesn't change the URL back to the current page if the user hits "cancel."
N/A
**Mockup**
N/A
Author: 
Reviewer(s):

Fix: Remove react prompt

---

src/js/components/reviewData/ReviewDataContent.jsx

Updating the links on the review page to USAS to open as new tabs. Note: only the agency submission file link is still available at this point though the other has been primed to open as a new tab once it's uncommented.   
N/A
[DEV-6869](https://federal-spending-transparency.atlassian.net/browse/DEV-6869)
**Mockup**
N/A
Author: 
Reviewer(s):
- Design review …

DEV-6869: Review Page USAS Submission Links Open in New Tabs

---

src/_scss/pages/reviewData/narrative/narrative.scss
src/js/components/reviewData/Narrative/ReviewDataNarrative.jsx

Adding a warning about unsaved comments at the bottom of the box too
N/A
[DEV-6873](https://federal-spending-transparency.atlassian.net/browse/DEV-6873)
**Mockup**
https://bahdigital.invisionapp.com/share/QTIAG9DYH8W#/screens
Author: 
Reviewer(s):

DEV-6873: Unsaved comments warning bottom

---

src/js/components/reviewData/Narrative/ReviewDataNarrative.jsx
src/js/helpers/util.js
tests/helpers/util-test.js

Adding whitespace doesn't affect equality checks since that gets trimmed on read-in anyway.
Testing against trimmed object contents
[DEV-6874](https://federal-spending-transparency.atlassian.net/browse/DEV-6874)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-6874: Trimmed equality check comments

---

src/_scss/pages/reviewData/_content.scss
src/_scss/pages/reviewData/narrative/narrative.scss
src/js/components/reviewData/Narrative/ReviewDataNarrative.jsx

Adding an error state above the comment box. Also updating the error symbol in both error states to be an exclamation not an X in the red circle
N/A
[DEV-6940](https://federal-spending-transparency.atlassian.net/browse/DEV-6940)
**Mockup**
https://bahdigital.invisionapp.com/share/4DIAG8Y875R
Author: 
Reviewer(s):

DEV-6940: Error message above comments

---

src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx

Allowing the error to actually show on the frontend when a file is uploaded to a submission with an already-running job.
Also cleaning up the file a bit so we don't bind in the render.
[DEV-2378](https://federal-spending-transparency.atlassian.net/browse/DEV-2378)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-2378: Running job error display

---

src/_scss/pages/dashboard/graph/_dashboardGraph.scss
src/js/components/dashboard/graph/DashboardGraph.jsx
src/js/components/dashboard/graph/DashboardGraphTooltip.jsx
src/js/components/dashboard/graph/active/SignificanceGraph.jsx
src/js/components/dashboard/graph/historical/BarChartStacked.jsx
src/js/components/dashboard/graph/historical/HistoricalDashboardTooltip.jsx
src/js/components/dashboard/graph/historical/StackedBarGroup.jsx
src/js/containers/dashboard/graph/WarningsInfoGraphContainer.jsx
tests/containers/dashboard/graph/WarningsInfoGraphContainer-test.jsx
tests/containers/dashboard/graph/mockData.js

Updating basic labels on graph and using periods and `is_quarter` instead of quarters. Also updating tooltip slightly to adjust for new design.
N/A
[DEV-7299](https://federal-spending-transparency.atlassian.net/browse/DEV-7299)
**Mockup**
https://bahdigital.invisionapp.com/share/8UIAH0B9YD7#/screens/296059063
Author: 
Reviewer(s):

DEV-7299: historic dashboard graph endpoint

---

src/_scss/pages/dashboard/graph/_dashboardGraph.scss
src/js/components/dashboard/graph/DashboardGraph.jsx
src/js/components/dashboard/graph/historical/BarChartStacked.jsx
src/js/components/dashboard/graph/historical/StackedBarGroup.jsx

Adding graying out of bars that aren't being hovered over (if one is hovered over)
N/A
[DEV-7298](https://federal-spending-transparency.atlassian.net/browse/DEV-7298)
**Mockup**
https://bahdigital.invisionapp.com/share/8UIAH0B9YD7#/screens/296059063
Author: 
Reviewer(s):

DEV-7298: Gray out historical dashboard bars

---

src/js/components/dashboard/graph/historical/BarChartStacked.jsx

Adds a minimal padding to the historical dashboard bar graph.
* Minor refactor to use `values` data structure instead of recalculating the padding in each function. 
N/A
**Mockup**
N/A
Author: 
Reviewer(s):

Fix: Minimum Bar Padding Historic Dashboard Graph

---

src/js/components/dashboard/graph/BarChartXAxis.jsx
src/js/components/dashboard/graph/DashboardGraphTooltip.jsx
src/js/components/dashboard/graph/historical/BarChartStacked.jsx

Updating the Historical Dashboard Graph's X-axis to be much cleaner by
1. moving years to a separate line below
2. grouping period marks to quarter marks (they still are properly marked in the tooltip)
* Added to the threshold that determines if a tooltip is on the left or right side as some of the tooltips are unviewable on the right side.
[DEV-7295](https://federal-spending-transparency.atlassian.net/browse/DEV-7295)
**Mockup**
https://bahdigital.invisionapp.com/share/8UIAH0B9YD7#/screens/296059058
Author: 
Reviewer(s):

DEV-7295: Historical Dashboard Graph X-Axis Cleanup

---

src/js/components/addData/metadata/SubmissionTypeField.jsx
src/js/components/uploadFabsFile/UploadFabsFileMeta.jsx

Fixing the FABS text for publishable vs test submissions
N/A
[DEV-7570](https://federal-spending-transparency.atlassian.net/browse/DEV-7570)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-7570: fixing text

---

src/js/components/dashboard/graph/historical/HistoricalDashboardTooltip.jsx

Showing percentages less than 0 in the tooltip as `<1%` instead of `0%`
N/A
[DEV-7652](https://federal-spending-transparency.atlassian.net/browse/DEV-7652)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-7652: historic dabs tooltip percent

---

src/js/components/dashboard/graph/BarChartXAxis.jsx
src/js/components/dashboard/graph/historical/BarChartStacked.jsx

With the latest changes to the X-Axis for the Bar Chart, it introduced a major bug with the X-Axis for the Active Dashboard. This recreates the old X-Axis setup for the Active Dashbaord while still keeping the Historic Dashboard X-Axis intact.
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):

Fix: Active Dashboard X-Axis

---

src/js/components/help/RawFilesItem.jsx
src/js/components/help/RawFilesPage.jsx

Adding a special download for agency comments on the raw files page because those are hosted elsewhere and don't have a publish ID
N/A
[DEV-7887](https://federal-spending-transparency.atlassian.net/browse/DEV-7887)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-7887: agency comments raw files

---

src/js/components/generateDetachedFiles/DetachedFileA.jsx
src/js/components/generateDetachedFiles/PeriodButton.jsx
src/js/components/generateDetachedFiles/PeriodButtonWithTooltip.jsx
src/js/components/generateDetachedFiles/PeriodPicker.jsx
src/js/helpers/periodPickerHelper.js
tests/helpers/periodPickerHelper-test.js

Periods in the Detached file A period picker will now show up the day after the month ends.
- Each period shows up the first day of the next month (eg. P03 will appear Jan 1st, P02 will appear Dec 1st, etc)
- Detached file A period dropdown now combines P1/P2 as a selection
N/A
[DEV-7486](https://federal-spending-transparency.atlassian.net/browse/DEV-7486)
**Mockup**
N/A
Author: 
- Verified that this PR does not create any *new* accessibility issues (via …

DEV-7486: file a generation date picker correct quarters

---

Dockerfile

The Broker frontend deploys occasionally fail after Jenkins nodes are patched due to the Broker frontend container taking longer than 3 minutes to initialize. The previous docker image was 2 years old has never been updated. 
This change separates the building of dependencies from the frontend code and does not affect the docker-compose scripts that are used to run the app locally. Run as usual to build the container that pulls the code into it or add the `--target frontend_base` to build dependencies only. This is blocking the work in updating the work in moving the broker frontend deploy to use ECR. 
Jenkins test run: http://jenkins-master-8ca0e1e199b2c8fc.elb.us-gov-west-1.amazonaws.com:8080/job/z-broker-frontend-nonprod-deploy/9/consol …

Update Broker frontend Dockerfile to prevent deploy failures

---

src/_scss/pages/history/history.scss
src/js/components/history/HistoryTable.jsx
src/js/helpers/submissionListHelper.js

Adds a button on the Submission History page to download all the files in a zip.
N/A
[DEV-7091](https://federal-spending-transparency.atlassian.net/browse/DEV-7091)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-7091: Submission History Zip

---

src/js/components/SharedComponents/navigation/NavigationComponent.jsx
src/js/containers/router/ProtectedComponent.jsx
tests/containers/router/ProtectedComponent-test.jsx

Resolving the issue where the Frontend "Logout" button doesn't actually log the user out.
Having the logout button call the backend logout function (and not relying on the session 'loggedout' flag to call that function)
[DEV-8443](https://federal-spending-transparency.atlassian.net/browse/DEV-8443)
**Mockup**
Author: 
Reviewer(s):

DEV-8443: Broker Logout Issue

---

src/js/components/addData/metadata/DateRangeField.jsx
src/js/helpers/util.js
tests/helpers/util-test.js

Defaulting DABS monthly submissions to current period until it closes, at which point it starts defaulting to the next period.
N/A
[DEV-8396](https://federal-spending-transparency.atlassian.net/browse/DEV-8396)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-8396: default dabs period

---

package-lock.json
package.json
webpack/webpack.prod.config.js

Replacing uglify with terser
Uglifier does not work with later versions of webpack/ES and some of the packages that were updated must use later versions of ES. Terser fixes this problem.
N/A
**Mockup**
N/A
Author: 
Reviewer(s):

Package updates

---

src/js/containers/generateFiles/GenerateFilesContainer.jsx

Default the generate D files selections to what the user generated last.
Uses the URL to determine awarding/funding and csv/txt so files from before those were in the name default to awarding/csv but I believe that is still accurate to what they were.
[DEV-4102](https://federal-spending-transparency.atlassian.net/browse/DEV-4102)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-4102: generate files defaults

---

src/js/containers/validateData/ValidationOverlayContainer.jsx
src/js/helpers/uploadHelper.js

Makes sure that the file boxes update even if the user uploads more than one and the others finish before the frontend checks
Reset the status of the validation states when uploading files
[DEV-8158](https://federal-spending-transparency.atlassian.net/browse/DEV-8158)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-8158: File reupload box updates

---

src/js/components/dashboard/DashboardPage.jsx
src/js/components/generateDetachedFiles/DetachedFileA.jsx
src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx

Making sure banners related to DABS submissions show up on the detached file A and D generation pages and on the DABS dashboard
Changing all the types on the relevant pages to "dabs" instead of "all".
[DEV-9220](https://federal-spending-transparency.atlassian.net/browse/DEV-9220)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-9220: Info banner on all pages

---

src/_scss/pages/reviewData/submissionButtons.scss
src/js/containers/SharedContainers/RevalidateContainer.jsx

Simplify disabled revalidate button text. Also cleaning up the disabled notify button visuals
N/A
[DEV-8135](https://federal-spending-transparency.atlassian.net/browse/DEV-8135)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-8135: Revalidate button text overflow

---

src/js/components/SharedComponents/navigation/NavbarTab.jsx
src/js/components/SharedComponents/navigation/NavigationComponent.jsx
src/js/components/addData/AddDataContent.jsx
src/js/components/addData/AddDataMeta.jsx
src/js/components/addData/SubmissionGuideContent.jsx
src/js/components/dashboard/table/DashboardTable.jsx
src/js/components/error/ErrorPage.jsx
src/js/components/generateDetachedFiles/DetachedFileA.jsx
src/js/components/help/helpNav.jsx
src/js/components/help/helpSidebar.jsx
src/js/components/help/helpSidebarItem.jsx
src/js/components/landing/blocks/LandingBlock.jsx
src/js/components/landing/recentActivity/SubmissionLink.jsx
src/js/components/login/LoginMaxLoading.jsx
src/js/components/submissionsTable/HistoryLink.jsx
src/js/components/validateData/ValidateCancellation.jsx

Fixing a bug where React redraws the whole page for every link instead of reloading only parts of it like it should.
Replaces <a>'s with <Link>'s only when applicable.
[DEV-10014](https://federal-spending-transparency.atlassian.net/browse/DEV-10014)
**Mockup**
N/A
Author: 
Reviewer(s):

[DEV-10014] Broker Redraw Fix

---

src/js/components/help/DataSourcesContent.jsx

Adding a blurb to explain the structure of the CD export.
N/A
[DEV-10507](https://federal-spending-transparency.atlassian.net/browse/DEV-10507)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-10507: CD Export Blurb

---

src/_scss/pages/uploadFabsFile/uploadFabsFile.scss
src/js/components/addData/metadata/SubmissionTypeField.jsx
src/js/components/uploadFabsFile/UploadFabsFileMeta.jsx

Preventing upload of publishable FABS for sub tier agency TFVA
The backend also prevents this subtier from making publishable submissions but this is a better user experience overall and adds another layer of security.
[DEV-10922](https://federal-spending-transparency.atlassian.net/browse/DEV-10922)
**Mockup**
N/A
Author: 
Reviewer(s):
- Design review …

DEV-10922: vendor test submission only fabs

---

src/_scss/abstract/variables/colors.scss
src/_scss/components/buttons/_stagedUpload.scss
src/_scss/components/tables/_genericBody.scss
src/_scss/components/tables/_tableHeaders.scss
src/_scss/components/typography/_global.scss
src/_scss/layouts/default/header/_menuBar.scss
src/_scss/layouts/validation/progress/_current.scss
src/_scss/layouts/validation/progress/_done.scss
src/_scss/layouts/validation/progress/_step.scss
src/_scss/pages/addData/uploadPage/_uploadDropzone.scss
src/_scss/pages/crossFile/errorBox/_tabs.scss
src/_scss/pages/crossFile/fileItem/_fileBox.scss
src/_scss/pages/dashboard/filters/_dashboardAgencyFilter.scss
src/_scss/pages/help/_sidebar.scss
src/_scss/pages/modals/settings/_sidebar.scss
src/_scss/pages/rawFiles/rawFiles.scss
src/_scss/pages/reviewData/_content.scss
src/_scss/pages/submissionsTable/_filters.scss
src/_scss/pages/validateData/fileItem/_footer.scss
src/_scss/pages/validateData/fileItem/body/criticalBody.scss
src/_scss/pages/validateData/fileItem/body/warningBody.scss
src/_scss/pages/validateData/fileItem/rightSide/rightSide.scss
src/js/components/validateData/treemap/TreemapCell.jsx
src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx

Updated various colors throughout wherever the 508 scanner failed on color contrast (or links being distinguishable without using color)
* Links surrounded by text (ie. paragraphs/body) are now underlined.
* The DABS progress steps colors have been updated.
* The E/W counts are updated to match the TEST submission text.
* The E/W state text on the right is subdued slightly (to direct more attention to the E/W counts).
* The E/W box colors are updated.
* In general, the blues, table headers, and text (within links, placeholders, grayed-out areas, etc.) are slightly darker.
[DEV-10691](https://federal-spending-transparency.atlassian.net/browse/DEV-10691)
**Mockup**
N/A
The following are ALL required for the PR to be …

DEV-10691: Color Contrast for 508 Compliance

---

package-lock.json
package.json

Updates awesomplete to version 1.1.7 which includes the fix from https://github.com/LeaVerou/awesomplete/pull/17256 (related to `aria-activedescendant`).
N/A
[DEV-11017](https://federal-spending-transparency.atlassian.net/browse/DEV-11017)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-11017: Awesomplete Fix

---

src/_scss/components/datepicker/_calendar-range-datepicker.scss
src/js/components/SharedComponents/CalendarRangeDatePicker.jsx

Fixing a visual issue in Chrome and the default date when months aren't exactly 30 days
Using Moment instead of the built-in Date month subtraction because that actually works
[DEV-11018](https://federal-spending-transparency.atlassian.net/browse/DEV-11018)
**Mockup**
N/A
Author: 
Reviewer(s):

Day Picker Fixes

---

src/js/components/generateFiles/components/DatePicker.jsx

Fixing the month that shows up in the picker
The default month sticks after the first instantiation even if the prop changes so we have to use a function and the month prop instead.
[DEV-11275](https://federal-spending-transparency.atlassian.net/browse/DEV-11275)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-11275: Default date picker

---

src/js/components/addData/SubmissionGuideContent.jsx

Instead of updating the outdated sample file links, we are removing them instead given the GSDM link below includes all the updated sample files.
N/A
[DEV-11912](https://federal-spending-transparency.atlassian.net/browse/DEV-11912)
**Mockup**
N/A
Author: 
Reviewer(s):

DEV-11912: Remove Oudated Sample File Links
