fedspendingtransparency/data-act-broker-web-app

src/js/components/LoginComponents.jsx
- Fixes issue in IE 10+ where they did not allow Buttons in A tags
=> Routing using vanilla javascript instead of nesting tags.

src/js/components/addData/ReviewDataPage.jsx
=> Adding in timer and mounting/unmounting functions.

src/_scss/common.scss, src/_scss/pages/addData.scss, src/js/components/SharedComponents/table/TableComponent.jsx, src/js/components/SharedComponents/table/TableHeaders.jsx, src/js/components/SharedComponents/table/TableSorter.jsx, src/js/components/validateData/ValidateDataContent.jsx, src/js/components/validateData/ValidateDataErrorReport.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/ValidateDataOverlay.jsx, src/js/containers/validateData/ValidateDataContainer.jsx, src/js/helpers/reviewHelper.js
* Shorter refresh timer
* Removal of vestigial code
* Updated CSS/layout
* Populated header error tables, scrollable
* Groundwork for bottom overlays
=> ⏱In Progress: Validate Data page updates

__unittests__/redux/uploadActions-spec.js, package.json, src/_scss/common.scss, src/_scss/custom.scss, src/_scss/pages/addData.scss, src/_scss/pages/help.scss, src/js/components/addData/AddDataHeader.jsx, src/js/components/addData/DropZone.jsx, src/js/components/addData/DropZoneDisplay.jsx, src/js/components/addData/FileComponent.jsx, src/js/components/admin/AdminPageHeader.jsx, src/js/components/error/ErrorPage.jsx, src/js/components/help/helpContent.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/helpSidebar.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/login/LoginIntro.jsx, src/js/components/registration/CompleteRegistrationComponent.jsx, src/js/components/registration/RegistrationPage.jsx, src/js/components/validateData/ValidateDataContent.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/ValidateDataOverlay.jsx, src/js/components/validateData/ValidateDataUploadButton.jsx, src/js/containers/router/RouterRoutes.jsx, src/js/containers/validateData/ValidateDataFileContainer.jsx, src/js/helpers/uploadHelper.js, src/js/redux/reducers/uploadReducer.js
* Resolves conflicts with Destin's CSS changes
* Restores file titles to dropzones
* Initial roundwork for re-uploading on validation page
=> Design + In Progress Validation

src/_scss/pages/addData.scss, src/js/components/addData/DropZone.jsx, src/js/components/addData/DropZoneDisplay.jsx, src/js/containers/addData/AddDataContainer.jsx, src/js/containers/validateData/ValidateDataOverlayContainer.jsx, src/js/containers/validateData/ValidateValuesOverlayContainer.jsx, src/js/helpers/uploadHelper.js
* Local uploads now progress through validation screens
* Support for re-uploading corrected files locally
=> Refactored local uploading

src/js/components/validateData/ValidateCancellation.jsx, src/js/containers/validateData/ValidateDataContainer.jsx
Per @klrBAH, validation screen offers a cancellation button after 5 minutes of "validating..." state. Also the timer invalidation now functions.
=> Offer validation cancellation

README.md
@kevinli-work or @mab6bf -- small change to point folks to the consolidated install docs
=> point users to consolidated install docs

README.md, src/_scss/pages/addData.scss
* Updated README to document changes to `GlobalConstants` files
* Bug fix to enable arrow navigation of the agency name typeahead
=> Readme Update

src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx, src/js/components/validateData/validateValues/ValidateValuesTreemap.jsx, src/js/containers/validateData/ValidateDataContainer.jsx
* Some bug fixes to deal with the real API
=> 🌙 Fixes: better handling of real API

src/js/components/addData/AddDataMeta.jsx, src/js/components/reviewData/ReviewDataContent.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/ValidateLoadingScreen.jsx, src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx, src/js/containers/validateData/ValidateDataContainer.jsx
* Bug fixes to better handle queued files waiting for validation
=> Bug fixes for validation page

README.md
Based on feedback from @kaitlin, add recommend Node.js version to install instructions. 
@mab6bf or @kevinli-work
=> add recommended Node.js version to readme

README.md
In case anyone is feeling a bit YOLO during the install process
=> tell users how to get wip features

src/js/components/addData/AddDataHeader.jsx
updated the add data page with more explanation and links to dummy page.
Right branch this time ...
=> added more explanation based on feedback from Heidis interviews

src/_scss/pages/addData.scss, src/js/components/addData/AddDataHeader.jsx, src/js/components/help/helpContent.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/registration/ConfirmCodeComponent.jsx, src/js/components/registration/RegisterEmailBanner.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx, src/js/helpers/reviewHelper.js
* Corrected error count
* Updated text on registration page about account approvals
* Updated text on sign up page to change "agency administrator" to "DATA Act Broker Helpdesk"
* Updated D file reference to D2
* Changed RSS references to Draft RSS 1.0
* Changed email addresses on Help and added reference to JIRA
=> Content fixes

src/js/components/forgotPassword/ForgotPasswordPage.jsx, src/js/components/registration/ConfirmCodeComponent.jsx, src/js/containers/forgotPassword/ForgotPasswordContainer.jsx, src/js/containers/registration/RegisterEmailContainer.jsx, src/js/containers/router/RouterContainer.jsx, src/js/containers/router/RouterRoutes.jsx
* Only validates dirtied fields in registration page
* Stop showing login errors after navigating to register/forgot password pages
=> Bugfixes: Registration page

src/_scss/pages/admin.scss, src/js/components/admin/AdminPageContent.jsx, src/js/components/registration/RegisterEmailBanner.jsx, src/js/helpers/adminHelper.js
* Admin page refactored to follow API helper approach used on other pages
* Fixed admin table content errors where they did not line up with the column names
* Updated error and success messages on email registration page to match Forgot Password page
=> Refactored Admin page, updated email registration page

src/_scss/pages/login.scss, src/js/components/forgotPassword/SetNewPasswordPanel.jsx, src/js/helpers/loginHelper.js
* Addresses CSS issues on Forgot Password page
* Additional refactoring to use helper pattern and disable submit button during REST call
=> Forgot Password bug fixes

src/js/components/validateData/ValidateNotYours.jsx, src/js/containers/validateData/ValidateDataContainer.jsx, src/js/helpers/reviewHelper.js
=> Frontend: Reject attempts to access submissions uploaded by other users

src/js/components/addData/AddDataPage.jsx, src/js/components/help/helpContent.jsx, src/js/components/reviewData/ReviewDataContent.jsx, src/js/components/validateData/ValidateDataContent.jsx, src/js/components/validateData/validateValues/ValidateValuesContent.jsx
* Bugfix to get autoscroll to work on IE (including help page links)
=> Bugfix: Autoscroll on IE

src/js/components/addData/AddDataContent.jsx, src/js/containers/validateData/ValidateDataContainer.jsx
* Fix submission ownership check
* Turn the upload button blue when not disabled (again!)
=> Hotfix: Missing = Sign

src/_scss/pages/registration.scss, src/js/components/SharedComponents/TextInputComponent.jsx, src/js/components/registration/ConfirmCodeComponent.jsx, src/js/components/registration/SubmitButton.jsx, src/js/helpers/loginHelper.js
* Fixed a bug where registration and reset password attempts would 401 because the frontend did not establish a new session
* Lock icon was missing on registration page, fixed tab indices on registration page, and made the registration blue on active state again
=> Bug Fix: Session handling for Registration and Reset Password

src/js/components/help/helpContent.jsx, src/js/components/help/helpSidebar.jsx
per @lisaam 's edits in PUB-124.
BEFORE MERGING @kevinli-work can you update the RSS link on the help page with the newest version pinned in slack and push to this branch?
=> updated Help Content 

src/js/helpers/uploadHelper.js
* Bug fix where local version of frontend did not post all the required metadata fields to the backend
=> Bug Fix: Metadata in Local Mode

src/js/components/help/helpContent.jsx
added text for DB252, DB370, DB453, DB 458, and updated known issues
=> revised for v1.0

src/js/components/help/helpContent.jsx
Reverts fedspendingtransparency/data-act-broker-web-app#112
=> Revert "revised for v1.0"

src/js/components/help/helpContent.jsx, src/js/components/help/helpSidebar.jsx
As part of deploying sprint 12
=> Update changelog/help in dev-stable

package.json, src/_scss/pages/addData.scss, src/js/components/SharedComponents/Typeahead.jsx, src/js/components/addData/AddDataMeta.jsx, src/js/components/addData/metadata/DateDropdown.jsx, src/js/components/addData/metadata/DateRangeField.jsx, src/js/components/addData/metadata/DateTypeField.jsx, src/js/components/addData/metadata/SubmitComponent.jsx, src/js/helpers/uploadHelper.js
* Fields appear as fade-in transitions
* New date fields
* Typeahead updates parent component state without needing to blur first
* More helpful error messages
=> Redesigned Metadata Page

src/js/components/addData/metadata/DateDropdown.jsx, src/js/components/addData/metadata/DateRangeField.jsx, src/js/helpers/uploadHelper.js, src/js/helpers/util.js, src/js/redux/actions/uploadActions.js
* Quarter dropdowns now return MM/YYYY format to the API
* Consolidated metadata handling into a single shared function used by both local and remote uploads to keep things consistent
* Redux reducers refactored to handle quarter flag
* Updated quarter detection to use the correct fiscal year
* Added utility function to convert quarters to month/year
=> Metadata Date Fields

src/js/components/landing/recentActivity/SubmissionLink.jsx
* Incorrectly capitalized letter in import path caused build process to fail
=> Hotfix: Incorrectly capitalized letter

src/_scss/common.scss, src/_scss/custom.scss, src/_scss/pages/addData.scss, src/_scss/pages/addMetaData.scss, src/_scss/pages/admin.scss, src/_scss/pages/help.scss, src/_scss/pages/landing.scss, src/_scss/pages/login.scss, src/js/components/addData/AddDataHeader.jsx, src/js/components/addData/AddDataMeta.jsx, src/js/components/addData/DropZone.jsx, src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/addData/metadata/DateRangeField.jsx, src/js/components/addData/metadata/DateTypeField.jsx, src/js/components/addData/metadata/SubmitComponent.jsx, src/js/components/admin/AdminPageContent.jsx, src/js/components/admin/AdminPageHeader.jsx, src/js/components/admin/userTable/ModifyBlock.jsx, src/js/components/admin/userTable/ReactivateBlock.jsx, src/js/components/help/helpContent.jsx, src/js/components/help/helpPage.jsx, src/js/components/landing/blocks/LandingRequirementsModal.jsx, src/js/components/login/SignInButton.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/containers/addData/fileTypes.js
Created a new addMetaData.scss file.
Removed block of text within the header on the Add New Data page.
Updated buttons on the admin page.
Fixed radio button on submission guide page (and across site)
=> Many small html/scss updates across the site.

src/js/components/help/helpContent.jsx, src/js/components/help/helpSidebar.jsx
Includes updated nav and help page content for sprint 13
=> Updated help page content

src/_scss/common.scss, src/_scss/pages/landing.scss, src/js/components/SharedComponents/icons/BaseIcon.jsx, src/js/components/SharedComponents/table/TableHeaders.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx, src/js/helpers/recentActivityHelper.js
* Added "Recent Activity for [Agency]" title
* Added Reporting Period and Submitted By columns
* Requires backend tasks in DB-579 to fully populate
* Fixed CSS bugs where table body would be misaligned from table headers
* Table header sorters now vertically center when insufficient width causes header text to wrap
=> Recent Activity Table Updates

src/js/components/admin/userTable/UserModal.jsx, src/js/components/admin/userTable/UserTable.jsx, src/js/components/reviewData/ReviewDataContent.jsx
* Fixed Review Data page
* Updated user admin table and modals to use `agency_name`
=> Agency Name Bug Fixes

src/help/history.md, src/js/components/help/helpContent.jsx, src/js/components/help/helpPage.jsx, src/js/helpers/helpHelper.js
* Add changelog from previous releases to help page
* Added/updated sample help page files with historical changelog
=> Help Page History

src/js/components/landing/recentActivity/SubmissionStatus.jsx
* Status label array needed to be re-ordered
=> Hotfix: Correct recent activity status labels

src/js/components/reviewData/ReviewDataNotifyModal.jsx, src/js/helpers/reviewHelper.js
* Updated API call with revised keys, values
=> Notify Users API Update

src/_scss/pages/addMetaData.scss, src/_scss/pages/help.scss, src/_scss/pages/registration.scss, src/js/components/addData/AddDataMeta.jsx, src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/addData/metadata/DateRangeField.jsx, src/js/components/help/helpPage.jsx, src/js/components/login/Password.jsx, src/js/components/login/Username.jsx, src/js/components/registration/ConfirmCodeComponent.jsx, src/js/components/registration/RegisterEmailBanner.jsx, src/js/containers/addData/SubmissionGuideContainer.jsx, src/js/helpers/util.js
* Username fields have been relabelled Email Address
* Added a message to check your spam folder after entering email address for new user registration
* Added a Back to Top button on the help page
* Second password field on registration page is now labelled Confirm Password
* Added a link to the Submission Guide
* Submission Guide can be viewed (when clicked via link) even if user previously skipped. Skip guide checkbox is prepopulated based on Redux state
* Starting date selector defaults to start of current fiscal year
=> Misc. UI Fixes

package.json, src/_scss/pages/help.scss, src/help/changelog.md, src/help/history.md, src/js/helpers/helpHelper.js
* Help content and HTML parser
=> Promote dev-stable to staging

src/js/helpers/reviewHelper.js
* Fixes a bug that would cause the Upload CSV button to remain perpetually disabled and/or break validation pages due to a change in the `check_status` API route
=> Bug fix: check_status data handling

src/_scss/pages/reviewData.scss, src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/reviewData/ReviewDataContent.jsx, src/js/components/reviewData/ReviewDataNotifyModal.jsx, src/js/components/reviewData/ReviewDataPage.jsx, src/js/components/reviewData/ReviewLoading.jsx, src/js/containers/review/ReviewDataContainer.jsx
* Added link in Submission Guide to validation table in Help page
* Improved Review Data loading UI to better line up with validation screens
* Refactored Review Data to utilize Redux container architecture in a consistent manner as other containers
* Fixed a bug where the notification promise would `catch` on attempting to close the modal because no event object was passed to the close function
=> Misc Frontend Updates

src/js/helpers/reviewHelper.js
=> List Users API update

src/help/changelog.md, src/help/history.md
Includes updates for DB-586, 684, 667, 662, 590, 579, 578. Added Rules A20, B11, B12, C18. Moved June 15 items to history. Did not copy rules table into history.
=> Help page updates for Sprint 15 changes

src/help/changelog.md
Changed date at top, added rules A18, A19, B9, B10
@kaitlin
=> Help page review changes

src/_scss/pages/crossFile.scss, src/js/components/addData/AddDataPage.jsx, src/js/components/crossFile/CrossFileContent.jsx, src/js/components/crossFile/CrossFileItem.jsx, src/js/components/crossFile/CrossFileOverlay.jsx, src/js/components/crossFile/components/ComparisonTable.jsx, src/js/components/crossFile/components/ErrorBox.jsx, src/js/components/crossFile/components/FileComponent.jsx, src/js/components/crossFile/components/FileWarning.jsx, src/js/components/crossFile/components/ReplacementBox.jsx, src/js/components/crossFile/components/ReplacementButton.jsx, src/js/components/validateData/ValidateDataErrorReport.jsx, src/js/components/validateData/ValidateDataUploadButton.jsx, src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx, src/js/containers/crossFile/CrossFileContentContainer.jsx, src/js/containers/crossFile/CrossFileUploadButtonContainer.jsx, src/js/containers/validateData/ValidateDataContainer.jsx, src/js/helpers/reviewHelper.js, src/js/redux/actions/uploadActions.js, src/js/redux/reducers/uploadReducer.js
* API integration
* Now handles uploading corrected files for validated files
* Now warns about the impact that replacing files will have on other cross file pairs, if applicable
* Now displays information about what cross file pair overwrite operation will affect a currently active cross-file pair (inverse of previous bullet)
* Smart loading screen shows cross file loading animation unless file-level validation errors occur, in which the user is sent back to the appropriate file validation page
=> Cross File Errors

src/js/components/SharedComponents/table/FormattedTable.jsx, src/js/components/SharedComponents/table/ScrollableTable.jsx, src/js/components/SharedComponents/table/TableHeaders.jsx, src/js/components/SharedComponents/table/TableSorter.jsx, src/js/components/validateData/treemap/Treemap.jsx, src/js/components/validateData/treemap/TreemapCell.jsx, src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx, src/js/components/validateData/validateValues/ValidateValuesTreemap.jsx, src/js/helpers/adminHelper.js, src/js/helpers/loginHelper.js
* Sortable table headers now highlight the column and directional arrow for the selected sort direction/field
* Refactored treemaps (again) to increase the frequency of re-rendering to restore the ability to resize on window resize events and add the ability to highlight the currently selected cell
* Treemap data sorting has been moved from D3 to the parent React component to prevent cells of equal value from changing positions between renders
* Fixed a bug where number of occurrences was not sorted corrected in the file validation tables
* Helpers now send empty objects instead of null values for POST requests without actual body data
=> Misc Updates

src/js/helpers/reviewHelper.js
* Ignore cross file errors for which no source or target were identified
=> Bug Fix: Only validate against approved cross file pairings

gulpfile.babel.js
* Gulp modified to use `[file].[commitHash].js/css` format
=> Gulp: Override Browser Cache on New JS/CSS

src/js/components/crossFile/components/FileWarning.jsx
* For triggering Jenkins build process and to prevent webpack from breaking in the future
=> Hotfix: Move Space

src/help/history.md
added section for June 29
updated the SQL rules URL to "/master/" instead of "/development/"
=> Update for Sprint 16 - history

src/help/changelog.md, src/help/history.md
=> Promote to staging

src/_scss/common.scss, src/_scss/components/_bottomOverlay.scss, src/_scss/components/_progressBar.scss, src/_scss/custom.scss, src/_scss/global/header.scss, src/_scss/pages/addData.scss, src/_scss/pages/addMetaData.scss, src/_scss/pages/crossFile.scss, src/_scss/pages/landing.scss, src/_scss/pages/login.scss, src/js/components/SharedComponents/table/ScrollableTable.jsx, src/js/components/addData/AddDataMeta.jsx, src/js/components/addData/metadata/DateRangeField.jsx, src/js/components/crossFile/CrossFileItem.jsx, src/js/components/crossFile/CrossFileOverlay.jsx, src/js/components/crossFile/components/ComparisonComponent.jsx, src/js/components/crossFile/components/ErrorBox.jsx, src/js/components/crossFile/components/ReplacementBox.jsx, src/js/components/login/LoginIntro.jsx, src/js/components/reviewData/ReviewDataNotifyModal.jsx, src/js/components/validateData/CorrectButtonFullOverlay.jsx, src/js/components/validateData/ValidateDataErrorReport.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/ValidateDataOverlay.jsx, src/js/components/validateData/ValidateDataUploadButton.jsx, src/js/components/validateData/treemap/TreemapCell.jsx, src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx, src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx, src/js/containers/crossFile/CrossFileUploadButtonContainer.jsx
- Changed “Alpha” mark to “Beta”.
- Changed the color of the icons to green for success and red for fail
or error.
- Fixed the width of the table rows on the validate page.
- fixed the position of the button on the add data modal page.
=> Style Updates

src/js/components/crossFile/CrossFileOverlay.jsx, src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx
* Next button leads to cross file validations
=> Overlay Text Update

src/js/components/landing/recentActivity/SubmissionStatus.jsx, src/js/helpers/recentActivityHelper.js
* To match backend status changes
=> Updated Recent Activity statuses

src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/forgotPassword/ForgotPasswordPanel.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/login/LoginIntro.jsx
* More user name error messages being obfuscated
* Schema is now DAIMS
* Backronymization of DATA Act already implemented in previous sprint
=> Text Updates

src/help/changelog.md
New validations in the HTML table on the help page
=> Updated help file with new validations

src/help/changelog.md
=> more rule updates, fixed styling on word wrap for a few columns

src/_scss/components/_bottomOverlay.scss, src/_scss/pages/addData.scss, src/js/components/validateData/validateValues/ValidateValuesContent.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx, src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx
* Files with warnings display orange icon and "File validated with warnings" message
* Bottom overlay indicates when there are warnings and provides instructions
=> Warning Text

src/js/components/addData/metadata/DateRangeField.jsx
* Fixes a bug where non-default date ranges were not correctly received by parent components and submitted to the API
=> Hotfix: Incorrect metadata date ranges

npm-shrinkwrap.json, src/js/containers/router/RouterContainer.jsx
=> Hotfix: JS syntax error

.travis.yml
It `buildLocal`s against three versions of node
=> Adds a simple travis test script

src/js/containers/generateFiles/GenerateFilesContainer.jsx
* Fixes a bug where single month submission date ranges were not correctly parsed
=> Hotfix: Handle single months

src/help/history.md
=> Sept 8 update

src/help/changelog.md
New topics, edited rules table
=> Update for Sept 8

src/help/changelog.md
Changed date to "9", deleted "What's New..."
=> Changelog.md date

src/help/changelog.md
changed date to Sept 13 for tomorrows release
=> Changelog.md date update

src/help/changelog.md
=> Changelog.md date update to 9/14

src/js/components/SharedComponents/icons/BaseIcon.jsx
* Changes the default icon component state to be valid SVG
=> Bugfix: Prevent Chrome from complaining about invalid SVG attributes

src/_scss/abstract/mixins/logo.scss, src/_scss/layouts/default/header/_menuBar.scss, src/_scss/layouts/login/_centerBanner.scss
=> Remove Beta Leaf

src/js/components/crossFile/components/ErrorBox.jsx
- DB-941 Allowing one pair of files to be corrected at a time
=> Feature crossFileValidation to dev

src/help/changelog.md, src/js/components/help/helpPage.jsx
- Fixing table
- Removing Beta tag
=> Hotfix for validation table in help page

src/help/changelog.md, src/js/components/help/helpPage.jsx
Validation table fix
Beta tag removal
=> Dev stable to staging hotfix

src/js/components/addData/AddDataMeta.jsx, src/js/components/addData/SubmissionComponent.jsx, src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/crossFile/CrossFileOverlay.jsx, src/js/components/landing/LandingContent.jsx
DB-1022 and DB-939
- Fixed spelling errors
- Altered language as per documented corrections
- Corrected instructions where old language was no longer relevant.
=> Content updates

src/js/helpers/reviewHelper.js
Note: This is labeled hotfix, but it's not occurring in staging or prod, so I'm merging into dev per usual.
=> Fixing links to non-cross-file warnings and errors

src/js/helpers/reviewHelper.js
No jira story, front-end support for C-D1 cross-validation pair
=> Adding front-end support for C-D1 validation pair

src/js/components/generateEF/GenerateEFContent.jsx, src/js/components/generateEF/generateItem/GenerateEFItem.jsx
Effectively reverts 9ab913a116226e5c10f6c63190d7e547a404275d as the file F
generation works again
=> Re-activate file F download button

src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/help/helpContent.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/blocks/LandingRequirementsModal.jsx, src/js/components/login/LoginIntro.jsx
- Removing refs to 'Beta Release' throughout the site.
=> Removing references to Beta Release

src/js/components/help/validationRulesTableContent.jsx
=> Adding paragraph as per feedback from Kaitlin

src/js/components/generateFiles/GenerateFilesOverlay.jsx
- Changing wording on overlay
- Animation is already in place
=> DB-928 D1/D2 Generation Overlay

src/_scss/pages/help/_topNav.scss, src/_scss/pages/help/help.scss, src/js/components/help/helpNav.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/resourcesPage.jsx, src/js/components/help/validationRulesTablePage.jsx
DB-1239 
- Updating Help pages to have nav in the top bar
=> Help navigation

src/js/components/generateEF/GenerateEFContent.jsx, src/js/components/generateEF/generateItem/GenerateEFItem.jsx, src/js/containers/generateEF/GenerateEFContainer.jsx
=> Enable File E

src/js/helpers/reviewHelper.js
DB-1257
- Adding B-C crossfile pair
- Reordering pairs alphabetically
- (Not DB-1259, typo on second commit)
=> Bc crossfile

src/_scss/pages/help/help.scss, src/_scss/pages/help/validationTable/_table.scss
Restyled validation table to match other table styles on the site.
=> Restyled Validation Table

src/help/changelog.md
* Fixes a formatting error in the help markdown
=> Hotfix: Help content formatting error

src/js/components/reviewData/ReviewDataContent.jsx, src/js/containers/review/ReviewDataContainer.jsx, src/js/helpers/reviewHelper.js
This PR uses the new get_obligations API route to pull in the total obligations and displays them on the submission review screen.
=> Db 582 display total obligations after submission

src/js/components/help/helpNav.jsx, src/js/components/help/historyPage.jsx
* Fix `key` error in help nav
* Add help navbar to history page
=> Bug fixes: Help page

src/_scss/pages/modals/admin/adminModal.scss, src/js/components/admin/userTable/UserModal.jsx, src/js/components/admin/userTable/UserTable.jsx, src/js/containers/admin/AdminUserTableContainer.jsx, src/js/helpers/adminHelper.js
* Frontend UI and API integration for `delete_users` route
=> Delete Users Admin UI

src/help/changelog.md, src/help/history.md
updated .md files for Oct 31 release
=> Help text changes

src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/crossFile/components/ErrorBox.jsx, src/js/components/generateEF/generateItem/GenerateEFItem.jsx, src/js/components/generateFiles/components/GenerateFileBox.jsx, src/js/components/help/helpContent.jsx, src/js/components/help/practicesProceduresContent.jsx, src/js/components/help/resourcesContent.jsx, src/js/components/help/validationRulesTableContent.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/blocks/LandingRequirementsModal.jsx, src/js/components/login/LoginIntro.jsx, src/js/components/login/LoginTopBar.jsx, src/js/components/validateData/ValidateDataErrorReport.jsx, src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx
* Closes a security flaw where malicious content on a page opened using a `target="_blank"` link could gain access to the originating Broker window/frontend.
=> Noopener security fix

src/js/components/help/resourcesContent.jsx
DB-1255
- Adding new signed URL
- New link on Resources Page
=> Adding new signed URL to Resources Page

src/_scss/layouts/login/_centerBanner.scss, src/_scss/layouts/login/_leftRightPositioning.scss, src/js/components/login/LoginBanner.jsx
* Sets maximum widths on the login page
=> Bugfix: Constrain login width

src/js/components/help/resourcesContent.jsx
Removed the link to Errata under IDD, updated the links to the egg diagrams. Note: links may not work. PR has been submitted to push files to prod on Fedspending but has not been processed.
=> IDD 1.0.1 text changes

src/js/components/help/resourcesContent.jsx
v1.0 to v1.0.1 pls merge soon - Ross and Kevin (Treasury) need to review this afternoon on staging
as always, thanks
=> DAIMS v1.0.1 text change

src/js/components/SharedComponents/ErrorMessage.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/login/LoginIntro.jsx, src/js/components/login/LoginMaxLoading.jsx, src/js/components/login/components/LoginMaxErrorMessage.jsx
- Changed DAIMS version to v1.0.1
- Updated error message component to render HTML to accommodate a link to MAX for login errors
=> Hotfix homepage text changes

src/js/components/help/resourcesContent.jsx
Reverting content changes per the request of @lisaam
=> Reverting resource page content change to commit id 881b65b

src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/historyPage.jsx, src/js/components/help/practicesProceduresPage.jsx, src/js/components/help/resourcesPage.jsx, src/js/components/help/validationRulesTablePage.jsx, src/js/components/login/LoginLinks.jsx, src/js/components/validateData/ValidateDataOverlay.jsx, src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx, src/js/containers/generateEF/GenerateEFContainer.jsx, src/js/containers/help/HelpContainer.jsx, src/js/containers/login/AuthContainer.jsx, src/js/containers/router/RouterRoutes.jsx, src/js/containers/validateData/ValidateDataOverlayContainer.jsx, src/js/containers/validateData/ValidateValuesOverlayContainer.jsx, src/js/helpers/reviewHelper.js, src/js/helpers/uploadHelper.js
- Allowing viewing of help page without sufficient permissions (but still requires MAX login)
- Show unauthorized message when attempting to upload corrected files for a submission without sufficient permissions
- Updating unauthorized message text
=> Update max permissions

src/help/changelog.md
Remove "What's New In This Update" from Header
=> Update changelog.md header change

src/js/helpers/loginHelper.js
Relies on data in fedspendingtransparency/data-act-broker-backend#452
=> Use the website_admin field to determine admin

src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/landing/LandingContent.jsx, src/js/containers/help/HelpContainer.jsx, src/js/containers/login/AuthContainer.jsx, src/js/containers/router/RouterRoutes.jsx, src/js/helpers/loginHelper.js
~~Relies on fedspendingtransparency/data-act-broker-backend#471~~
=> Use affiliations rather than user fields

src/help/changelog.md, src/help/history.md
=> Dev stable -> dev

src/js/components/help/helpContent.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/helpSidebar.jsx
HelpOnly users will have access to a link that directs them to max to increase their permissions.
- Users without HelpOnly permissions will not see any changes on the help page
- Users with HelpOnly permissions will see a link in the sidebar below 'Getting More Help' which autoscrolls to a heading with a link to https://community.max.gov/x/fJwuRQ
=> Db 1602 mk upgrade max permissions

src/_scss/layouts/validation/validation.scss, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx
Added download link. Tested by uploading file and downloading the uploaded file.
=> Db 1624 mk download uploaded files

src/js/components/dashboard/DashboardTable.jsx
Updated submission dashboard table
=> Updated submission Dashboard Table

src/help/changelog.md, src/help/history.md
=> help notes for 2/13

src/js/components/help/historyPage.jsx
isMounted is reserved. switched to isUnmounted which seems to resolvehe issue
=> db-1628 hot fix

src/_scss/pages/dashboard/dashboard.scss, src/_scss/pages/landing/recentActivity/_table.scss, src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/recentActivity/DeleteLink.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx, src/js/helpers/reviewHelper.js
Front End delete link implementation.
=> Db 1635 delete link

src/js/components/generateDetachedFiles/DateSelect.jsx, src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx, src/js/components/generateFiles/GenerateFilesContent.jsx
fixing offset closing tag, generatedetachedfilespage dateselect had outdated date picker props
=> BUG FIX: Date Selector on detached files was outdated

src/js/components/uploadDetachedFiles/UploadDetachedFileMeta.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFilesPage.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx
Fixed FABS visual sync. Removed the context.history console warning about deprecated code. Made sure behaviour from validation, back to data entry, back to validation, and any other combination would continue to work
=> Db 1754 mk bug fix context router

src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx, src/js/containers/dashboard/DashboardContainer.jsx, src/js/helpers/submissionListHelper.js
Added sortability to the front end dashboard
=> Db 1632 sortable submissions

src/_scss/pages/crossFile/crossFile.scss, src/_scss/pages/generateEF/generateEF.scss, src/_scss/pages/generateFiles/generateFiles.scss, src/_scss/pages/reviewData/reviewData.scss, src/_scss/pages/validateData/validateData.scss, src/js/components/SharedComponents/PublishedSubmissionWarningBanner.jsx, src/js/components/reviewData/ReviewDataPage.jsx, src/js/containers/crossFile/CrossFileContentContainer.jsx, src/js/containers/generateEF/GenerateEFContainer.jsx, src/js/containers/generateFiles/GenerateFilesContainer.jsx, src/js/containers/review/ReviewDataContainer.jsx, src/js/containers/validateData/ValidateDataContainer.jsx, src/js/helpers/reviewHelper.js, src/js/redux/actions/uploadActions.js, src/js/redux/reducers/uploadReducer.js
Adds a banner below the progress bar of certified submissions warning the user that changes won't be updated to usaspending until the submission is re-certified.
=> Db 1765 display published status in submission

src/help/changelog.md, src/help/history.md, src/help/technical.md
Updated help page and technical release notes
=> updated help files

src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx
Updating stray call to hideError to updateError which was stopping the page from updating to the correct view.
=> Hotfix: Resolving detached D file generation

src/help/changelog.md, src/help/history.md, src/help/technical.md
Hotfixing detached D file generation
=> Hotfix: Dev stable -> dev

src/js/components/landing/recentActivity/DeleteModal.jsx, src/js/helpers/reviewHelper.js
As an agency user, I need to see a proper warning message when trying to delete a certified submission
Acceptance Criteria:
There is a better warning message on submission dashboard when user tries to delete certified submission
=> db-1764 Add proper delete message

src/js/components/addData/AddDataHeader.jsx, src/js/components/landing/recentActivity/DeleteModal.jsx
Added label to submission details 
Also set a default message for the delete modal error
=> Db 1631 mk reporting period

src/help/validations.csv
Removing rules A20 and A21 from documentation
=> Db 1784 remove a20 a21

src/js/components/help/resourcesContent.jsx, src/js/components/help/validationRulesTableContent.jsx
Updating validation rule file reference
=> Hotfix-Updating rule file reference

src/_scss/components/tables/_submissionTableProgress.scss, src/js/components/dashboard/DashboardContent.jsx, src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx, src/js/components/landing/recentActivity/SubmissionStatus.jsx
-Updated the recent activity table to mark submissions that need recertification with an updated label
-Updated the dashboard to identify submissions that need recertification
=> Submissions are in right table for dashboard and identify subs that need recert

src/help/changelog.md, src/help/history.md, src/help/technicalHistory.md
Formatted and added new changelog and moved current release notes into archive
=> Update Changelog and Archive old notes

src/help/changelog.md, src/help/history.md
pushing release notes and updating history to dev-stable
=> pushing release notes and updating history

src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx
No longer allowing sorting on the "Status" column for the submissiondashboard and recent activity table.
=>  Hotfix: Submission dashboard performance

src/js/components/validateData/CorrectButtonOverlay.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx, src/js/components/validateData/validateValues/ValidateValuesOverlay.jsx, src/js/containers/validateData/ValidateValuesFileContainer.jsx, src/js/redux/actions/uploadActions.js, src/js/redux/reducers/uploadReducer.js
Changed UX so that user must either hit the upload button to upload new files, or must cancel out selected files in order to progress pass the ABC file selection page
=> Db mk 1796 replacement upload notification

src/js/components/SharedComponents/Typeahead.jsx, src/js/containers/SharedContainers/SubTierAgencyListContainer.jsx
Adding sorting by priority to sub tier agency dropdown
=> Db 1704 agency list sort

src/_scss/layouts/validation/progress/progress.scss, src/js/components/SharedComponents/Modal.jsx, src/js/components/SharedComponents/ProgressComponent.jsx, src/js/components/addData/AddDataContent.jsx, src/js/components/addData/AddDataMeta.jsx, src/js/components/crossFile/CrossFilePage.jsx, src/js/components/generateEF/GenerateEFPage.jsx, src/js/components/generateFiles/GenerateFilesPage.jsx, src/js/components/reviewData/ReviewDataPage.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/ValidateDataPage.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx, src/js/helpers/agencyHelper.js
Updated progress bar to act as navigation for all previous steps.
=> Db 1811 broker navigation

src/js/components/help/helpSidebar.jsx
Added Service Desk Link the to the help page sidebar
=> DB 1476 Service Desk Link to help page 

src/js/components/help/resourcesContent.jsx, src/js/components/help/validationRulesTableContent.jsx
Fixing validation rule file names.
Validation file is uploaded to S3 already.
=> Hotfix: Updating download file links

src/js/helpers/util.js
Default quarter goes back two months. so instead of 
Quarter 2: 1, 2, 3 curryear
Quarter 3: 4, 5, 6 curryear
Quarter 4: 7, 8, 9 curryear
Quarter 1: 10, 11, 12 nextyear
it is now
Quarter 2: 3, 4, 5 curryear
Quarter 3: 6, 7, 8 curryear
Quarter 4: 9. 10. 11 curryear
Quarter 1: 12 nextyear 1, 2 curryear
=> DB-1838-default quarter goes back 2 months

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
Merging release notes back down to dev
=> added release and technical notes

src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx
=> DB 1826-Remove End Date hotfix

src/js/helpers/permissionsHelper.js
=> DB-1647-navbar-hotfix

src/js/components/reviewData/ReviewDataContent.jsx
Remove Delete and Download links from Certify Page
=> DB 1879 Remove Delete and Download from Certify

src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/help/validationRulesTableContent.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/blocks/LandingRequirementsModal.jsx
Wording Changes based of e-mail thread. Can Forward if needed
=> DB-0000-Wording-Changes

src/js/components/help/helpContent.jsx
Added page content for Help Page to go to the service desk
=> DB 1476 Help Page Service Desk

src/_scss/components/tables/_submissionTable.scss, src/js/components/dashboard/DashboardTable.jsx
Display the UTC date passed to the frontend as the local time. Added the last certified date to the Certified Submissions dashboard table.
After backend is merged, until this is merged the dates will display incorrectly
=> Db 1846 display certified date

src/js/containers/generateFiles/GenerateFilesContainer.jsx
Removed if statement that allows for D file download on certified/updated submissions
=> Certified/Updated D File generation download

src/js/containers/generateFiles/GenerateFilesContainer.jsx
Possible Options
URL no File Size: Warning Message with no download link
No URL no File Size: Warning Message with no download link
Url with File Size: Works like expected
=> Db 1850 mk critical error d download

src/js/components/SharedComponents/ProgressComponent.jsx, src/js/components/landing/recentActivity/SubmissionLink.jsx, src/js/containers/generateFiles/GenerateFilesContainer.jsx, src/js/containers/review/ReviewDataContainer.jsx, src/js/helpers/submissionGuideHelper.js
Allows for navigation to most current step from all tables, allows for people to go directly to the stage they are at and prevents people from navigating too far
=> Db 1777 mk page navigation

src/js/components/SharedComponents/ProgressComponent.jsx, src/js/components/landing/recentActivity/SubmissionLink.jsx, src/js/containers/review/ReviewDataContainer.jsx, src/js/helpers/submissionGuideHelper.js
Reverts fedspendingtransparency/data-act-broker-web-app#554
=> Revert "Db 1777 mk page navigation"

src/js/components/landing/recentActivity/RecentActivityTable.jsx
Convert date to local date in recent activity table
=> Hotfix: Recent Activity Table Dates

src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx
=> Hotfix recent activity table dates

src/js/components/addData/AddDataMeta.jsx, src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx, src/js/containers/SharedContainers/AgencyListContainer.jsx, src/js/helpers/agencyHelper.js
ability to generate D files seperately
=> DB 1901 Generate Detached D files

src/js/components/crossFile/CrossFileOverlay.jsx, src/js/components/generateEF/GenerateEFOverlay.jsx
Permissions needed to be inverted for EF and crossfile
=> HOTFIX-Generate buttons disabled for EF and crossfile

src/js/components/help/helpContent.jsx
=> Removing old service desk information

src/_scss/layouts/validation/validation.scss, src/_scss/pages/addData/addData.scss, src/_scss/pages/validateData/validateData.scss, src/js/components/addData/AddDataContent.jsx, src/js/containers/addData/AddDataContainer.jsx, src/js/helpers/reviewHelper.js, src/js/helpers/uploadHelper.js
Reverts fedspendingtransparency/data-act-broker-web-app#533
=> Revert "Db 1806 certify submission permissions"

src/js/components/dashboard/DashboardTable.jsx, src/js/containers/addData/AddDataContainer.jsx
Prevent auto nav to 404 page on new submission creation
=> Hotfix new submission 404

src/js/containers/addData/AddDataContainer.jsx
Local upload was overwritten. Fixed
=> HOTFIX-Local upload was overwritten

src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/help/resourcesContent.jsx, src/js/components/landing/blocks/LandingRequirementsModal.jsx
=> DB 1958 Removing sample files and RSS sample/webinars

src/_scss/layouts/validation/validation.scss, src/_scss/pages/addData/addData.scss, src/_scss/pages/validateData/validateData.scss, src/js/components/addData/AddDataContent.jsx
This is to bring back the warning for file upload to not navigate
=> HOTFIX revert removed the warning to not navigate away during upload

src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/help/resourcesContent.jsx, src/js/components/landing/blocks/LandingRequirementsModal.jsx
Reverts fedspendingtransparency/data-act-broker-web-app#582
=> Revert "DB 1958 Removing sample files and RSS sample/webinars"

src/js/containers/validateData/ValidateValuesFileContainer.jsx
Needs to render the validation page of fabs after validation completes rather than hanging. Problem was missing params, added user session and it is not working
=> DB MK 2011 FABS Validation Page

src/js/components/dashboard/DashboardTable.jsx
Users that have read only permissions should see no delete column, users with some permissions above read will have the delete column and will have the delete option for submissions that they have permissions for
=> Db mk 2017 delete submission

src/js/components/landing/recentActivity/RecentActivityTable.jsx
Fixing delete behavior on the recent activity table
=> updated the recent activity table

src/js/components/addData/AddDataHeader.jsx, src/js/components/landing/recentActivity/SubmissionLink.jsx, src/js/components/submission/SubmissionPage.jsx, src/js/containers/router/RouterRoutes.jsx, src/js/containers/submission/SubmissionContainer.jsx
Created a loading page that gets the current state of the submission and redirects once it collects
=> DB 2036 Submission Intermediary Page

src/js/components/landing/recentActivity/DeleteLink.jsx
Have not been able to replicate the error with these changes.
=> Db mk 2037 missing eyes hotfix

src/_scss/pages/help/_daims.scss, src/_scss/pages/help/help.scss, src/js/components/help/daimsMessage.jsx, src/js/components/help/practicesProceduresContent.jsx, src/js/components/help/resourcesContent.jsx, src/js/components/help/validationRulesTableContent.jsx
Notification to users regarding daims and broker v1.1 along with links to the max documentation
Also fixed indets
=> DB-mk-1968 daims resources

src/js/components/SharedComponents/GTASWarningBanner.jsx, src/js/components/generateEF/GenerateEFPage.jsx, src/js/components/reviewData/ReviewDataContent.jsx, src/js/components/reviewData/ReviewDataPage.jsx, src/js/containers/crossFile/CrossFileContentContainer.jsx, src/js/containers/generateEF/GenerateEFContainer.jsx, src/js/containers/generateFiles/GenerateFilesContainer.jsx, src/js/containers/review/ReviewDataContainer.jsx, src/js/containers/validateData/ValidateDataContainer.jsx, src/js/helpers/reviewHelper.js
=> Db mk 1944 gtas window restriction

src/_scss/pages/addData/addData.scss, src/_scss/pages/landing/landing.scss, src/js/components/addData/AddDataPage.jsx, src/js/components/landing/LandingContent.jsx
=> DB 1944 GTAS Window Warning

src/js/components/SharedComponents/GTASWarningBanner.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/blocks/LandingRequirementsModal.jsx
Reformatted the dates for gtas window banner
=> db 1944 GTAS window: Reformat dates

src/js/components/SharedComponents/GTASWarningBanner.jsx, src/js/components/landing/blocks/LandingRequirementsModal.jsx
=> db 1944 GTAS Window

src/js/components/help/daimsMessage.jsx
Daims links were swapped for validation and practices pages
=> DB 1968 Daims Notice

src/js/components/SharedComponents/banners/TestEnvironmentBanner.jsx
=> Fix non prod env banner text

src/js/components/SharedComponents/table/TableHeaders.jsx, src/js/components/dashboard/DashboardTable.jsx, src/js/components/detachedDashboard/DetachedDashboardContent.jsx, src/js/components/detachedDashboard/DetachedDashboardPage.jsx, src/js/components/detachedDashboard/DetachedDashboardTable.jsx, src/js/components/landing/recentActivity/SubmissionLink.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileMeta.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx
Changed the header on the FABS page, added the certified table, and fixed the sorting for this and the dashboard certified tables
=> DB-1927?-FABS-header-certified-table-sorts

src/js/components/SharedComponents/Typeahead.jsx, src/js/components/addData/AddDataMeta.jsx, src/js/components/reviewData/ReviewDataContent.jsx, src/js/components/reviewData/ReviewDataNotifyModal.jsx, src/js/components/submission/SubmissionPage.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileMeta.jsx, src/js/containers/SharedContainers/AgencyListContainer.jsx, src/js/containers/addData/AddDataContainer.jsx, src/js/containers/review/ReviewDataContainer.jsx, src/js/helpers/agencyHelper.js, src/js/helpers/uploadHelper.js, src/js/redux/actions/uploadActions.js
Acceptance Criteria:
- Agencies on the approved list can submit by their FR entity code instead of by their AID code
- MAX groups are created and updated to work the same way for the FR entity reporters
- Validations that use the AID code of the submitting agency are updated
=> DB-1943 report by FREC

src/help/validations.csv, src/js/components/help/resourcesContent.jsx, src/js/components/help/validationRulesTableContent.jsx
Removing rules from table and updating links to downloadable files.
=> Db 2078 1933 remove unnecessary rules

src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/dashboard/DashboardPage.jsx, src/js/components/help/helpNav.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/helpSidebar.jsx, src/js/components/help/helpSidebarItem.jsx, src/js/components/help/historyContent.jsx, src/js/components/help/historyPage.jsx, src/js/components/help/resourcesPage.jsx, src/js/components/help/validationRulesTablePage.jsx, src/js/containers/help/HelpContainer.jsx, src/js/containers/router/RouterRoutes.jsx
Acceptance Criteria:
- Create detached help routes
- Update navigation to stay within FABS when visiting Help page
=> Db xxxx detached help navigation

src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/landing/BlockContent.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/blocks/LandingBlock.jsx, src/js/containers/router/RouterRoutes.jsx
=> Db mk 2092 fabs dabs landing

src/_scss/pages/help/_topNav.scss, src/js/components/dashboard/DashboardPage.jsx, src/js/components/dashboard/DashboardTable.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/historyPage.jsx, src/js/components/help/practicesProceduresPage.jsx, src/js/components/help/resourcesPage.jsx, src/js/components/help/validationRulesTablePage.jsx, src/js/components/history/HistoryPage.jsx, src/js/components/landing/BlockContent.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx, src/js/components/landing/recentActivity/SubmissionLink.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileMeta.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx
Updating to match new AC, teal should cary over to all pages, modal was broken which should be fixed now
=> DB 2081 FABS Pages

src/js/components/help/helpPage.jsx
=> DB MK 2081 Fabs Landing

src/js/components/SharedComponents/Banner.jsx, src/js/components/addData/AddDataPage.jsx, src/js/components/landing/BlockContent.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/blocks/LandingRequirementsBody.jsx, src/js/components/reviewData/ReviewDataContent.jsx, src/js/components/reviewData/ReviewDataPage.jsx, src/js/containers/crossFile/CrossFileContentContainer.jsx, src/js/containers/generateEF/GenerateEFContainer.jsx, src/js/containers/generateFiles/GenerateFilesContainer.jsx, src/js/containers/review/ReviewDataContainer.jsx, src/js/containers/validateData/ValidateDataContainer.jsx, src/js/helpers/reviewHelper.js
Generic messages received from the backend
=> db-2098 Robust window warnings for submission and for gtas

src/js/components/landing/recentActivity/RecentActivityTable.jsx
Using this branch to fix the submission link
=> BD 2098 Robust Warnings

src/js/components/dashboard/DashboardTable.jsx, src/js/components/help/resourcesPage.jsx, src/js/components/landing/BlockContent.jsx, src/js/components/reviewData/ReviewDataContent.jsx
Needed to fix the check for blocked certification on the review/certify page
=> DB-MK-2098 Warning Bar

src/js/components/landing/blocks/LandingRequirementsBody.jsx
Changed validation checklist in the modal on fabs landing to be able to download pdf from s3
=> Validation Checklist link and download files

src/js/components/help/daimsMessage.jsx, src/js/components/help/validationRulesTableContent.jsx
Capitalized DAIMS and updated the link with the new file
=> Hotfix validations file

src/js/components/help/resourcesContent.jsx
=> Updated Validation File

src/js/components/addData/AddDataHeader.jsx, src/js/components/addData/DropZone.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx
Updates the information in the header bar as well as the file information. Header information gets updated on DABS submissions as well
=> DB 1841 Fabs file information

src/js/components/crossFile/components/GeneratedFileModal.jsx, src/js/containers/crossFile/CrossFileGenerateModalContainer.jsx
D file replacement on crossfile is throwing an error. It is now fixed
=> DB 2029 Cross File D file replacement error

src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/addData/AddDataPage.jsx, src/js/components/addData/SubmissionGuidePage.jsx, src/js/components/crossFile/CrossFilePage.jsx, src/js/components/error/ErrorPage.jsx, src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx, src/js/components/generateEF/GenerateEFPage.jsx, src/js/components/generateFiles/GenerateFilesPage.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/historyPage.jsx, src/js/components/help/practicesProceduresPage.jsx, src/js/components/help/resourcesPage.jsx, src/js/components/help/validationRulesTablePage.jsx, src/js/components/history/HistoryPage.jsx, src/js/components/landing/BlockContent.jsx, src/js/components/reviewData/ReviewDataPage.jsx, src/js/components/submission/SubmissionPage.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFilesPage.jsx, src/js/components/validateData/ValidateDataPage.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx, src/js/containers/history/HistoryContainer.jsx, src/js/containers/router/RouterRoutes.jsx, src/js/helpers/permissionsHelper.js
AC:
- Users with F permissions have read-only access to DABS
=> DB 2102 FABS has readonly access to DABS

src/_scss/pages/addData/addData.scss, src/_scss/pages/dashboard/dashboard.scss, src/_scss/pages/help/help.scss, src/_scss/pages/uploadDetachedFiles/uploadDetachedFiles.scss, src/js/components/SharedComponents/Banner.jsx, src/js/components/addData/AddDataPage.jsx, src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/dashboard/DashboardPage.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/practicesProceduresPage.jsx, src/js/components/help/resourcesPage.jsx, src/js/components/help/validationRulesTablePage.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/LandingPage.jsx, src/js/components/reviewData/ReviewDataPage.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileMeta.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx, src/js/containers/crossFile/CrossFileContentContainer.jsx, src/js/containers/generateEF/GenerateEFContainer.jsx, src/js/containers/generateFiles/GenerateFilesContainer.jsx, src/js/containers/review/ReviewDataContainer.jsx, src/js/containers/router/RouterContainer.jsx, src/js/containers/validateData/ValidateDataContainer.jsx
Updated Banner Message to only show relevant warnings and extend banner to all pages. help page should only have site wide messages
=> Db mk 2103 banner message

src/js/components/help/daimsMessage.jsx
Removing the link for validations and updating version number with 1.1
=> HOTFIX Daims Message

src/js/containers/router/RouterRoutes.jsx
AC:
- Users with F permissions have read-only access to DABS
(this PR is just to fix the submissionGuide route navbar, the rest of this branch has merged)
=> DB-2102 FABS has read-only DABS permissions

src/_scss/pages/uploadDetachedFiles/uploadDetachedFiles.scss, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx
Downloadable files in fabs, also header warning files are also available to download for fabs AND dabs
=> Db mk 2110 fabs download

src/js/components/dashboard/DashboardContent.jsx, src/js/components/dashboard/DashboardPage.jsx, src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/BlockContent.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/blocks/LandingRequirementsBody.jsx, src/js/components/uploadDetachedFiles/PublishModal.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFileValidation.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFilesBox.jsx, src/js/containers/validateData/ValidateDataFileContainer.jsx
Updating FABS language as per powerpoint and jira comments https://federal-spending-transparency.atlassian.net/browse/DB-2104
=> Db mk 2104 fabs language

src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx
Should be created by not submitted by
=> DB 2138 Submission Header should be created by not submitted by

sampleGlobalConstants_dev.js, sampleGlobalConstants_local.js, sampleGlobalConstants_prod.js, src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/login/AuthPage.jsx, src/js/components/login/LoginPage.jsx, src/js/containers/router/RouterRoutes.jsx
Adding a prod flag and setting it to false everywhere except the prod environment. Showing main landing page and test environment banner on all non-prod environments
Technical Release Notes:
- New global constant
=> Db 2151 test environment flag

src/js/components/landing/recentActivity/RecentActivityTable.jsx
link should not be disabled ever
=> HOTFIX view link on recent activity is blocked

src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/dashboard/DashboardPage.jsx, src/js/components/help/helpNav.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/helpSidebar.jsx, src/js/components/help/helpSidebarItem.jsx, src/js/components/help/historyPage.jsx, src/js/components/help/practicesProceduresPage.jsx, src/js/components/help/resourcesContent.jsx, src/js/components/help/resourcesPage.jsx, src/js/components/help/validationRulesTablePage.jsx, src/js/components/landing/BlockContent.jsx, src/js/components/landing/LandingContent.jsx, src/js/components/landing/LandingPage.jsx, src/js/components/landing/blocks/LandingRequirementsBody.jsx, src/js/components/landing/recentActivity/SubmissionLink.jsx, src/js/components/uploadDetachedFiles/UploadDetachedFilesPage.jsx, src/js/containers/help/HelpContainer.jsx, src/js/containers/router/RouterRoutes.jsx, src/js/helpers/submissionGuideHelper.js
Refactor routes to use FABS prefix rather than the detachedprefix, went and hunted down what i think are all the detached links
=> Db mk 2149 refactor routes

src/js/components/uploadDetachedFiles/PublishModal.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx
Fixing language to be more clear and less confusing
=> DB 2127 FABS publish language

src/help/changelog.md, src/help/history.md
changed the history.md file and changelog.md
=> release notes for sprint 45

src/js/containers/router/RouterRoutes.jsx
Allowing users in prod to see the real landing page and have easy access to FABS
=> Hotfix allow prod into fabs

src/help/changelog.md, src/help/history.md
=> Release Notes FABS

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
Waiting on information for technical release notes
=> Release notes for sprint 46

src/js/components/landing/blocks/LandingRequirementsBody.jsx
=> DB MK 2205 removal of d2 sample file

src/help/fabs_validations.csv
=> DB-mk-2172 Funding Agency Validations

src/help/fabs_validations.csv
Updating error type for FABS41.5
=> Db 2167 fix ppop zip4 validations

src/help/changelog.md, src/help/history.md
=> history.md and changelog.md sprint 48

src/_scss/components/tables/_genericBody.scss, src/_scss/components/tables/_submissionTableLink.scss, src/_scss/pages/dashboard/_table.scss, src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx, src/js/components/landing/recentActivity/SubmissionLink.jsx
=> Db mk 2112 fabs dashboard

src/js/components/dashboard/DashboardTable.jsx, src/js/components/landing/recentActivity/SubmissionLink.jsx
fixing some realestate problems for the columns
=> DB-MK-2112- Dashboard

src/_scss/components/tables/_submissionTable.scss, src/_scss/components/tables/_submissionTableProgress.scss, src/js/components/dashboard/DashboardTable.jsx
=> DB 2297 sort by publish date

src/js/components/addData/AddDataContent.jsx, src/js/components/addData/AddDataMeta.jsx, src/js/components/addData/AddDataTypeSelector.jsx, src/js/components/crossFile/CrossFileOverlay.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/ValidationOverlay.jsx
Removing CSV from several locations where it doesn't make sense because it might be TXT as well
=> Db 2325 fix error text

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Adding release notes

src/js/components/reviewData/ReviewDataPage.jsx, src/js/containers/review/ReviewDataContainer.jsx
Build failing because of library issues, changing to import from the correct spot
=> DB 1883 Linter Hotfix

src/js/containers/addData/AddDataContainer.jsx
Dabs submission creation was breaking because of a missing param for a function
=> DABS submission creation

src/js/helpers/reviewHelper.js
=> HOTFIX revalidate FABS submissions

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md, src/js/components/addData/AddDataHeader.jsx, src/js/components/crossFile/components/ErrorTabs.jsx, src/js/components/help/daimsMessage.jsx, src/js/components/help/helpSidebar.jsx
Hanlded merge from dev-stable into dev independently
=> Hotfix catch up dev

src/js/helpers/util.js
https://federal-spending-transparency.atlassian.net/browse/DEV-301
- Parser incorrectly read the quarter and as such would not update the year for Q1 submissions
=> DEV-301 Hotfix to fix default date in DABS submission

src/js/components/addData/AddDataMeta.jsx, src/js/components/generateFiles/components/DatePicker.jsx, src/js/helpers/util.js
quarterToYear is passed `quarter` as both string and int. casted to string in order to handle multiple cases
=> Hotfix DABS Associated Quarter

src/help/fabs_validations.csv
Updating fabs_validations to match up to things that were changed in previous PRs
=>  Dev 428 445 440 449 rule catch up

src/help/fabs_validations.csv
Removing rules referring to FiscalYearAndQuarterCorrection since we removed that from FABS!
=> Dev 432 remove old columns

src/help/fabs_validations.csv
Removing LegalEntityAddressLine3 rule for FABS!
=> Dev 434 remove address line 3 fabs

src/help/fabs_validations.csv
[Story Link](https://federal-spending-transparency.atlassian.net/browse/DEV-448)
Updates text for rules:
- 40.2
- 41.2
- 42.2
- 43.3
=> Updating FABS rules 40.2, 41.2, 42.2, 43.3

src/help/fabs_validations.csv
Updating the list of FABSREQ and FABSTYPE rules to include numbers and be ordered the same way as in the DAIMS
=> Dev 450 fabsreq fabstype labels

src/help/fabs_validations.csv
Moving old rules and adding the new one for FABS44
=> FABS44 new rule order change

src/js/components/help/daimsMessage.jsx, src/js/components/help/helpContent.jsx, src/js/components/help/historyContent.jsx, src/js/components/help/resourcesContent.jsx, src/js/components/help/validationRulesTableContent.jsx, src/js/components/landing/blocks/LandingRequirementsBody.jsx
Updating and removing links to update to v1.2
=> Dev 678 update documents

src/help/fabs_validations.csv
Updating rule text for 15.1 given by schema
=> Updating rule 15.1 text to include specific record type

src/help/fabs_validations.csv, src/js/components/help/helpContent.jsx, src/js/components/help/helpSidebar.jsx, src/js/components/help/historyContent.jsx, src/js/components/help/resourcesContent.jsx, src/js/components/help/validationRulesTableContent.jsx, src/js/components/landing/blocks/LandingRequirementsBody.jsx, src/js/helpers/util.js
Many small updates for file urls to link to new v1.2 files.
Update FABS validations table to reflect DAIMS 1.2 document
=> Dev 824 daims 1 2 document updates

src/js/components/help/helpSidebar.jsx
Setting a default for the reportingWindowUrl state
=> Hoftix fix dabs help

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Modifying release notes for sprint 64

src/js/containers/crossFile/CrossFileGenerateModalContainer.jsx, src/js/containers/generateEF/GenerateEFContainer.jsx, src/js/containers/generateFiles/GenerateFilesContainer.jsx, src/js/helpers/generateFilesHelper.js
Updating frontend to use get_file_url where applicable
=> Dev 1209 check generation status file types

src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx, src/js/helpers/reviewHelper.js
Replace `report_url` POST request to a GET.
Replace `report_url` with a GET, apply parameters to the end if they exist.
[DEV-1213](https://federal-spending-transparency.atlassian.net/browse/DEV-1213)
- Unit & integration tests updated with relevant test cases N/A
=> DEV-1213: Change report_url to GET

src/js/components/uploadFabsFile/UploadFabsFileMeta.jsx, src/js/helpers/uploadHelper.js
Move FABS file upload to backend
Aligning frontend process with API process in terms of FABS file upload.
[DEV-1072](https://federal-spending-transparency.atlassian.net/browse/DEV-1072)
=> DEV-1072: Moving FABS upload to backend

README.md, sampleGlobalConstants_dev.js, sampleGlobalConstants_local.js, sampleGlobalConstants_prod.js, src/js/helpers/uploadHelper.js
Move DABS file upload to backend
Aligning frontend process with API process in terms of DABS file upload.
[DEV-1072](https://federal-spending-transparency.atlassian.net/browse/DEV-1072)
=> DEV-1072: Moving DABS upload to backend

src/js/helpers/submissionListHelper.js
Change list_submissions to a post
Changing list_submissions to a POST to reflect backend changes
[DEV-1357](https://federal-spending-transparency.atlassian.net/browse/DEV-1357)
=> Update list_submissions to a post

src/_scss/pages/help/_daims.scss, src/js/components/help/daimsMessage.jsx, src/js/components/help/resourcesContent.jsx, src/js/components/landing/blocks/LandingRequirementsBody.jsx
High level description:
Updated text for Broker resource page and "What you will need to submit" pop-ups.
Technical details:
Updated the HTML
Link to JIRA Ticket:
https://federal-spending-transparency.atlassian.net/browse/DEV-1076
=> Updated text on Broker resource pages and pop-ups

src/_scss/pages/addData/addData.scss, src/_scss/pages/addData/uploadPage/_uploadDropzone.scss, src/graphics/icons.svg, src/js/app.jsx, src/js/components/SharedComponents/icons/BaseIcon.jsx, src/js/components/SharedComponents/icons/Icons.jsx, src/js/components/addData/AddDataContent.jsx, src/js/components/addData/DropZone.jsx, src/js/components/addData/DropZoneDisplay.jsx, src/js/components/addData/SubmissionComponent.jsx, src/js/components/help/validationRulesTableContent.jsx, src/js/components/landing/blocks/LandingRequirementsBody.jsx, src/js/containers/addData/AddDataContainer.jsx
Update the look and feel of the upload message and add an "uploading" loading circle when uploading a file.
- Updates icons when file is in the "upload" state
- Fixes other broken upload states( such as success)  and updates icons accordingly
- Linter based code cleanup
- Added SVG and made styling updates
[DEV-1386](https://federal-spending-transparency.atlassian.net/browse/DEV-1386)
=> Update frontend while uploading files

src/js/components/dashboard/DashboardFilters.jsx, src/js/components/dashboard/filters/FileNameFilter.jsx, src/js/containers/dashboard/DashboardContainer.jsx, src/js/containers/dashboard/FilterBarContainer.jsx
Implements the File Name filter on Submission Dashboards
- Adds the optional File Name filter that accepts multiple free-text string inputs, which are stored in an array in Redux
- Parses the File Names array into Filter Tags for display
[DEV-1365](https://federal-spending-transparency.atlassian.net/browse/DEV-1365)
~Unit & integration tests updated with relevant test cases~ N/A
=> Feature dashboard file name filter

src/js/components/SharedComponents/Typeahead.jsx, src/js/components/dashboard/DashboardTable.jsx, src/js/containers/dashboard/AgencyFilterContainer.jsx
- Resets table to page 1 when filters change
- Clears agency name from input after select
[DEV-1364](https://federal-spending-transparency.atlassian.net/browse/DEV-1364)
=> Dashboard agency filter fixes

pull_request_template.md
Include a PR template that autopopulates the Pull Request contents for Broker Frontend.
The contents of the file should autopopulate future Pull Requests.
N/A
- Merged concurrently with Backend N/A
=> Add PR Template to Github

src/_scss/pages/dashboard/_typeaheadFilter.scss, src/js/components/SharedComponents/DropdownTypeahead.jsx, src/js/components/SharedComponents/DropdownTypeaheadCheckbox.jsx, src/js/components/SharedComponents/Typeahead.jsx, src/js/components/SharedComponents/TypeaheadWarning.jsx, src/js/components/dashboard/DashboardContent.jsx, src/js/components/dashboard/DashboardFilters.jsx, src/js/components/dashboard/DashboardTable.jsx, src/js/components/dashboard/filters/AgencyFilter.jsx, src/js/components/dashboard/filters/CreatedByFilter.jsx, src/js/components/dashboard/filters/FilterBar.jsx, src/js/components/dashboard/filters/TagItem.jsx, src/js/containers/dashboard/AgencyFilterContainer.jsx, src/js/containers/dashboard/CreatedByContainer.jsx, src/js/containers/dashboard/DashboardContainer.jsx, src/js/containers/dashboard/FilterBarContainer.jsx, src/js/helpers/createdByHelper.js, src/js/redux/actions/agencyActions.js, src/js/redux/actions/createdByActions.js, src/js/redux/reducers/createdByReducer.js, src/js/redux/reducers/index.js
Adds a "Created By" dropdown filter in the Broker Dashboard that allows the user to filter the table. 
- `CreatedByContainer` makes a call to the `list_all_submissions` endpoint, removes duplicate names, and passes the remaining values to populate the dropdown of an [Awesomeplete](https://www.npmjs.com/package/awesomplete) Typeahead component.
- `DropdownTypeahead` gets the value typed into the [Awesomeplete](https://www.npmjs.com/package/awesomplete) Typeahead component, and created an unchecked checkbox. 
- Upon Clicking the Checkbox, the staged `CreatedBy` filter tags are processed for display
- Processes applied `CreatedBy` filters and adds them to the `list_submissions` `filters` request param …
=> Filter dropdown

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Sprint 71 Release Notes

src/js/components/SharedComponents/DropdownTypeahead.jsx, src/js/components/dashboard/DashboardContent.jsx, src/js/components/dashboard/DashboardFilters.jsx, src/js/components/dashboard/filters/CreatedByFilter.jsx, src/js/components/dashboard/filters/FilterBar.jsx, src/js/containers/dashboard/CreatedByContainer.jsx, src/js/containers/dashboard/FilterBarContainer.jsx
Adds a more UX friendly message for duplicate names
Checks to see if the name is already selected/in a checkbox, then uses the `TypeaheadWarning` component to show an appropriate error. 
Also cleans up unneeded code
[DEV-1366](https://federal-spending-transparency.atlassian.net/browse/DEV-1366)
=> Created By Dropdown - better duplication message

src/_scss/pages/help/_content.scss, src/_scss/pages/help/_sidebar.scss, src/help/changelog.md, src/help/technical.md, src/js/components/help/helpContent.jsx, src/js/components/help/helpSidebar.jsx
High level description:
Adds a sign-up box to the help page and some style changes.
Technical details:
- Adds a sign-up box that opens up the email client for users to sign-up
- CSS changes
Link to JIRA Ticket:
[DEV-1588](https://federal-spending-transparency.atlassian.net/browse/DEV-1588)
=> Sign-up Box and Style Changes

src/_scss/components/typeahead/_typeahead.scss, src/_scss/pages/dashboard/_filters.scss, src/_scss/pages/dashboard/_typeaheadFilter.scss, src/js/components/SharedComponents/DropdownTypeahead.jsx, src/js/components/SharedComponents/DropdownTypeaheadCheckbox.jsx, src/js/containers/dashboard/CreatedByContainer.jsx, src/js/helpers/createdByHelper.js
- Updated Created By dropdown to close on clicking outside the menu
- Better name searching 
- Updated API endpoints and value handling
- Cleaned up excess code
[DEV-1366](https://federal-spending-transparency.atlassian.net/browse/DEV-1366)
=> Created By Filter Dropdown

.babelrc, README.md, gulpfile.babel.js, package.json, src/js/containers/dashboard/DashboardContainer.jsx, tests/containers/dashboard/DashboardContainer-test.jsx, tests/containers/dashboard/mockData.js, tests/containers/dashboard/mockSubmissionListHelper.js, tests/helpers/util-test.js, tests/redux/dashboard/dashboardFilterReducer-test.js
Introduces unit testing using Jest and Enzyme. Implements initial unit tests for one of each type of file:
- Container (DashboardContainer.jsx)
- Reducer (dashboardFilterReducer.js)
- Helper (util.js)
- Updates various dependencies
- Removed code related to an unused/earlier test process, additional code cleanup in the gulpfile
[DEV-1481](https://federal-spending-transparency.atlassian.net/browse/DEV-1481)
=> Initial Unit Tests

src/_scss/pages/uploadFabsFile/uploadFabsFile.scss, src/js/components/SharedComponents/CalendarRangeDatePicker.jsx, src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx, src/js/containers/dashboard/LastDateModifiedContainer.jsx
Moves the details of a published submission, such as the date and time of publication out side of the button and changes button language to be more descriptive
[DEV-1536](https://federal-spending-transparency.atlassian.net/browse/DEV-1536)
=> FABS publishing screen button text changes

src/js/components/help/helpSidebar.jsx
Updating reporting window URL and text
Updating reporting window URL and text
[DEV-2004](https://federal-spending-transparency.atlassian.net/browse/DEV-2004)
=> DEV-2004: Update submission calendar

src/js/components/help/resourcesContent.jsx
Brings dev branch up to date with hotfixed links (#978), while preserving changes made in #975 
[DEV-2008](https://federal-spending-transparency.atlassian.net/browse/DEV-2008)
=> Demote update treasury links

src/js/components/help/resourcesContent.jsx
Updated links that had the wrong URL.
Updated links.
[DEV-1455](https://federal-spending-transparency.atlassian.net/browse/DEV-1455)
=> Hotfix Resource Page Links

src/_scss/components/tooltip/_tooltips.scss, src/_scss/pages/uploadFabsFile/uploadFabsFile.scss, src/_scss/pages/validateData/fileItem/rightSide/rightSide.scss, src/js/components/uploadFabsFile/UploadFabsFileError.jsx, src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx
Adds a helpful tooltip for FABS published files and updates copy
[DEV-1536](https://federal-spending-transparency.atlassian.net/browse/DEV-1536)
**Link to Mockup**
https://bahdigital.invisionapp.com/share/JKIA8I0XDUP#/screens
=> Hotfix update fabs publishing screen

src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx
Fixes in a typo in description about the differences between the published fabs file and the submitted file.
[DEV-1536](https://federal-spending-transparency.atlassian.net/browse/DEV-1536)
=> Hotfix to update text in FABS publishing tooltip

src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx
Fixes in a typo in description about the differences between the published fabs file and the submitted file.
[DEV-1536](https://federal-spending-transparency.atlassian.net/browse/DEV-1536)
=> Hotfix FABS tooltip text

sampleGlobalConstants_dev.js, sampleGlobalConstants_local.js, sampleGlobalConstants_prod.js
Fixed GlobalConstants files to work with current Dev branch
ES6 module syntax fix. Changed GlobalConstants module's export method from a Default export to Named export to work with current codebase. 
=> Fixed default configuration files to work with current dev branch

src/js/components/help/helpSidebar.jsx, src/js/components/help/resourcesContent.jsx
Updating links per request.
Updated `href` values to new strings
[DEV-2269](https://federal-spending-transparency.atlassian.net/browse/DEV-2269)
- N/A Merged concurrently with Backend
=> [DEV-2269] Updating links on Resources Page and Help Side Bar

src/js/components/addData/metadata/DateDropdown.jsx, src/js/components/addData/metadata/DateRangeField.jsx, src/js/helpers/util.js, tests/helpers/util-test.js
Returning the previous quarter correctly.
Fixing the logic for getting the quarter for the dropdown. Fixed the actual quarter calculation logic and updated the name of the function to clarify we wanted the previous quarter.
[DEV-1768](https://federal-spending-transparency.atlassian.net/browse/DEV-1768)
=> DEV-1768: Fix currentquarter logic

src/js/helpers/uploadHelper.js
Update Front End to use new endpoint for FABS submission
update API call
[DEV-1890](https://federal-spending-transparency.atlassian.net/browse/DEV-1890)
=> update submit_detached_file endpoint to publish_fabs_file

src/js/helpers/uploadHelper.js
update API endpoint for submitting FABS files
Update `submit_detached_file` to `publish_fabs_file`
[DEV-1890](https://federal-spending-transparency.atlassian.net/browse/DEV-1890)
=> Hotfix Publish fabs file

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md, src/js/components/help/helpContent.jsx
Release notes for March 25, 2019
N/A
N/A
=> Hotfix: Release Notes March 25, 2019

src/js/helpers/util.js, tests/helpers/util-test.js
Accounting for if a non-int is passed to quarterToMonth
See Above
N/A
=> Hotfix: Fixing default dates for D files

src/_scss/pages/help/_content.scss
Fixes spacing between sections of the Help pages. See where the mockup linked below indicates "Reduced spacing".
N/A
**Mockup**
https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/screens/295997419_BFS_USAS_Broker_DABS-FABS_Help_02A
[DEV-2198](https://federal-spending-transparency.atlassian.net/browse/DEV-2198) (Failed Test)
=> Hotfix help pages spacing

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
Sprint 80 Release Notes
N/A
N/A
=> Hotfix: Sprint 80 Release Notes

src/js/components/dashboard/DashboardTable.jsx
Users can sort the reporting period column for the certified submissions table in DABS.
* remove reporting period column from unsortable array
[DEV-2481](https://federal-spending-transparency.atlassian.net/browse/DEV-2481)
=> Dev-2481 Sort Reporting Period Column for Certified Submissions in DABS

src/help/changelog.md, src/help/technical.md
=> Hotfix: Sprint 82 Release Notes (updated language)

src/js/helpers/reviewHelper.js, src/js/helpers/submissionListHelper.js, src/js/helpers/uploadHelper.js, tests/helpers/agencyHelper-test.js, tests/helpers/createdByHelper-test.js, tests/helpers/generateFilesHelper-test.js, tests/helpers/helpHelper-test.js, tests/helpers/lastDateModifiedHelper-test.js, tests/helpers/loginHelper-test.js, tests/helpers/permissionsHelper-test.js, tests/helpers/reviewHelper-test.js, tests/helpers/sessionSuperagent-test.js, tests/helpers/submissionGuideHelper.js, tests/helpers/submissionListHelper-test.js, tests/helpers/uploadHelper-test.js, tests/helpers/util-test.js
Adds unit tests for every exported helper function. Added a test file for each helper file for read-ability and to acknowledge possible additional tests.
Trying to test the scenario for each distinct return value.
[DEV-2536](https://federal-spending-transparency.atlassian.net/browse/DEV-2536)
=> [DEV-2536] Adding Unit tests for helper methods that are (1) not REST requests & (2) exported

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
(see title)
N/A
**Mockup**
N/A
- Merged concurrently with Broker
- Passes linter
=> Hotfix: Sprint 83 Release Notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
(see title)
N/A
**Mockup**
N/A
- Merged concurrently with Broker
- Passes linter
=> Hotfix: Sprint 83 Release Notes (Production)

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
(see title)
N/A
**Mockup**
N/A
- Passes linter
=> Master Hotfix: Sprint 84 Release Notes

package-lock.json, package.json, src/js/app.jsx
=> Master Hotfix IE bug

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
(see title)
N/A
**Mockup**
N/A
- Passes linter
=> Sprint 85 Release Notes (staging)

src/js/components/generateDetachedFiles/DateSelect.jsx, src/js/components/generateFiles/GenerateFilesContent.jsx
Update Generate File D Date Placeholder Text
* updated on detached generate D
* updated on generate file generate D step
[DEV-2361](https://federal-spending-transparency.atlassian.net/browse/DEV-2361)
=> Dev-2361 Update Generate File D Date Placeholder Text

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
Release notes for Sprint 86.
(see above)
N/A
**Mockup**
=> Hotfix: Sprint 86 Release Notes

src/js/components/landing/recentActivity/DeleteModal.jsx
Updating delete modal text to match the ticket
See above
[DEV-2869](https://federal-spending-transparency.atlassian.net/browse/DEV-2869)
**Mockup**
N/A
=> DEV-2869: Delete submission modal text

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Master Hotfix: Sprint 87 Release Notes

src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx, src/js/containers/submission/SubmissionContainer.jsx
=> Demote Hotfix from staging to dev

src/js/components/uploadFabsFile/UploadFabsFilePage.jsx, src/js/containers/submission/SubmissionContainer.jsx
=> Demote Hotfix from staging -> dev

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Hotfix: Sprint 89 Release Notes

src/js/components/reviewData/ReviewDataContent.jsx, src/js/helpers/util.js, tests/helpers/util-test.js
Fixing the logic behind the total file size display so it actually displays correct numbers.
Also moved the function to a helper.
[DEV-2554](https://federal-spending-transparency.atlassian.net/browse/DEV-2554)
**Mockup**
N/A
=> DEV-2554: file size display

src/_scss/pages/reviewData/narrative/narrative.scss, src/js/components/reviewData/ReviewDataNarrative.jsx, src/js/helpers/reviewHelper.js
Simple download button for submission comments file on the review page.
- Used `saveState` area to notify user if the submission file doesn't exist.
- Added `errorMessage` state to `ReviewDataNarrative` to be more detailed in error messages.
[DEV-3250](https://federal-spending-transparency.atlassian.net/browse/DEV-3250)
**Mockup**
N/A
- N/A Design review (if applicable)
- N/A Unit tests added (if applicable)
=> DEV-3250: Download Submission Comments File

src/js/components/reviewData/ReviewDataNarrative.jsx, src/js/helpers/reviewHelper.js
Updating comments endpoints to use the newly made endpoints
N/A
[DEV-3367](https://federal-spending-transparency.atlassian.net/browse/DEV-3367)
**Mockup**
N/A
=> DEV-3367: Submission comment endpoint

package-lock.json, package.json
Updates a couple of dependencies.
Also adds `npm run errors` to see linter errors without warnings.
N/A - tech debt/ maintenance 
=> Update dependencies & add errors script

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Sprint 90 Release Notes (staging)

src/js/components/addData/SubmissionGuideContent.jsx, src/js/components/generateDetachedFiles/DetachedFileA.jsx, src/js/components/landing/blocks/LandingRequirementsBody.jsx
Updating DAIMS URLs to use the current one
Also fixed a linter warning
[DEV-2397](https://federal-spending-transparency.atlassian.net/browse/DEV-2397)
**Mockup**
N/A
=> DEV-2397: Update daims links

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title, mistyped the branch name)
(see title)
N/A
**Mockup**
N/A
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …
=> Hotfix: Sprint 91 Release Notes (staging)

src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/landing/BlockContent.jsx, src/js/components/reviewData/CertificationModal/ReviewDataCertifyModal.jsx, src/js/components/submissionsTable/SubmissionsTablePage.jsx, src/js/containers/router/RouterRoutes.jsx
Switches naming convention from plural `Submissions Table` to singular `Submission Table`
Follow up for [DEV-3609](https://federal-spending-transparency.atlassian.net/browse/DEV-3609)
=> Hotfix DEV-3609 submission table naming convention

src/js/helpers/periodPickerHelper.js, tests/helpers/periodPickerHelper-test.js
Reworked mostRecentPeriod logic after reviewing it with the GTAS window in mind.
N/A
[DEV-3758](https://federal-spending-transparency.atlassian.net/browse/DEV-3758)
**Mockup**
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in …
=> DEV-3758 Hotfix: mostRecentPeriod logic, accounting for GTAS window gap

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
Release notes for Sprint 92.
N/A
N/A
**Mockup**
N/A
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339)
- Link to this PR in JIRA ticket
=> Sprint 92 Release Notes (Staging)

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item …
=> Hotfix: Sprint 93 Release Notes (Staging)

package-lock.json, package.json, src/_scss/abstract/mixins.scss, src/_scss/abstract/mixins/errors.scss, src/_scss/components/autocomplete/_errorMessage.scss, src/_scss/components/autocomplete/autocomplete.scss, src/_scss/pages/dashboard/_filterSidebar.scss, src/_scss/pages/dashboard/filters/_rulesFilter.scss, src/_scss/pages/dashboard/filters/_selectedFilters.scss, src/js/app.jsx, src/js/components/SharedComponents/autocomplete/Autocomplete.jsx, src/js/components/SharedComponents/autocomplete/Suggestion.jsx, src/js/components/SharedComponents/autocomplete/SuggestionHolder.jsx, src/js/components/SharedComponents/autocomplete/Warning.jsx, src/js/components/dashboard/DashboardPage.jsx, src/js/components/dashboard/filters/RulesFilter.jsx, src/js/components/dashboard/filters/SelectedRules.jsx, src/js/components/dashboard/filters/ShownValue.jsx, src/js/containers/dashboard/filters/RulesFilterContainer.jsx, src/js/helpers/dashboardHelper.js, src/js/redux/actions/dashboard/dashboardFilterActions.js, src/js/redux/reducers/dashboard/dashboardFiltersReducer.js, tests/containers/dashboard/filters/RulesFilterContainer-test.jsx, tests/containers/dashboard/filters/mockFilters.js, tests/redux/dashboard/dashboardFiltersReducer-test.js
Adds the autocomplete rules filter to the dashboard page.
- Reuses multiple components from USAspending, including `Autocomplete` and `ShownValue`
- This filter is disabled until a File is selected. The chosen file is passed as a parameter to the `get_rule_labels` API call 
- Filtering the results by search string is performed on the frontend 
- Adds [FontAwesome icons](https://fontawesome.com/icons?d=gallery) as a dependency
[DEV-3660](https://federal-spending-transparency.atlassian.net/browse/DEV-3660) (rules filter) & [DEV-3876](https://federal-spending-transparency.atlassian.net/browse/DEV-3876) (FontAwesome)
**Mockup**
https://bahdigital.invisionapp.com/share/AXIABX6G347#/screens/296024131
**Testing**
1. On …
=> DEV-3660 rules filter

src/js/containers/dashboard/filters/FileFilterContainer.jsx
Adds colons to the cross file filter labels. 
[DEV-3659](https://federal-spending-transparency.atlassian.net/browse/DEV-3659)
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/296021488_Historical-Search-Monthly-Single-No-Data
=> DEV-3659 fix cross file labels

src/_scss/pages/dashboard/_chooseFilters.scss, src/_scss/pages/dashboard/dashboard.scss, src/js/app.jsx, src/js/components/dashboard/ChooseFiltersMessage.jsx, src/js/components/dashboard/DashboardContent.jsx, src/js/components/dashboard/DashboardPage.jsx, src/js/containers/dashboard/DashboardContentContainer.jsx
Adding a message to select filters before any have been selected
- Creates a reusable component so we can have this message again
- If the filters aren't empty the box will go away
[DEV-3871](https://federal-spending-transparency.atlassian.net/browse/DEV-3871)
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/screens
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …
=> DEV-3871: Choose filters box

src/js/components/uploadFabsFile/PublishModal.jsx
Adds the disabled property to the No Valid Rows button.
https://federal-spending-transparency.atlassian.net/browse/DEV-3921
**Mockup**
N/A
- [N/A] Scheduled Demo including Design/Testing/Front-end OR Provided Instructions for Local Testing above and in JIRA (if applicable)
- [N/A] Tagged Designer in `#br-frontend` Slack Channel in the thread under the Post from Github for their SA
- [N/A] Merged concurrently with [Backend#1234](https://github.com/fedspendingtransparency/data-act-broker-backend/pull/1234)
- [N/A] All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …
=> Bug No Valid Rows Button CSS

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
N/A
N/A
**Mockup**
N/A
=> Sprint 94 Release Notes (staging)

src/js/components/dashboard/graph/BarChartLegend.jsx, src/js/components/dashboard/graph/BarChartLegendItem.jsx, src/js/components/dashboard/graph/BarChartStacked.jsx, src/js/components/dashboard/graph/WarningsInfoGraph.jsx, src/js/containers/dashboard/graph/WarningsInfoGraphContainer.jsx, src/js/dataMapping/dashboard/fileLabels.js, src/js/helpers/stackedBarChartHelper.js, tests/containers/dashboard/graph/WarningsInfoGraphContainer-test.jsx, tests/containers/dashboard/graph/mockData.js, tests/helpers/stackedBarChartHelper-test.js
Adds the legend to the Dashboard graph visualization.
- Adds padding to the right of the graph for the legend
- Creates an SVG element for each rule
- Adds a data-mapping for 508 contrast compliant color order
- Adds helpers for building the legend array and centering it on the y-axis
[DEV-3884](https://federal-spending-transparency.atlassian.net/browse/DEV-3884) (subtask of [DEV-3664](https://federal-spending-transparency.atlassian.net/browse/DEV-3664))
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/296021489_Historical-Search-Monthly-Single-Data
=> DEV-3884 dashboard legend

src/js/components/help/helpSidebar.jsx
Updating reporting schedule link
N/A
[DEV-3679](https://federal-spending-transparency.atlassian.net/browse/DEV-3679)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-3679: Update reporting window schedule

src/_scss/pages/dashboard/table/_dashboardTable.scss, src/js/components/dashboard/table/DashboardTable.jsx, src/js/components/dashboard/table/DashboardTableHeader.jsx, src/js/components/dashboard/table/DashboardTableSorter.jsx, src/js/containers/dashboard/table/DashboardTableContainer.jsx, tests/containers/dashboard/table/DashboardTableContainer-test.jsx
Sorting for the historical dashboard table
- Clicking on the sort buttons sorts the table
- The current active sort is a different color
[DEV-3665](https://federal-spending-transparency.atlassian.net/browse/DEV-3665)
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/screens/296021489
Author: 
Reviewer(s):
=> DEV-3665 dashboard table sorting

src/js/components/dashboard/graph/WarningsInfoGraph.jsx
Cleaning up/fixing the logic behind the special states for graphs. There was a minor bug that still displayed the graphs even though there were no results.
N/A
N/A
**Mockup**
Author: 
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant …
=> Fix: Graph No Results Logic

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
Release notes for Sprint 95 to staging.
N/A
N/A
**Mockup**
N/A
Author: 
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA …
=> Warmfix: Sprint 95 Release Notes

.eslintrc, babel.config.js, package-lock.json, package.json, src/js/app.jsx
Fixes a bug that prevented the site from loading in Internet Explorer. 
- Added `babel-polyfill` to handle newer JS features such as the [Symbol primitive](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol). 
Reviewer(s):
=> Warmfix IE bug

.eslintrc, babel.config.js, package-lock.json, package.json, src/js/app.jsx
Copying the IE fix (#1216) to master.
N/A
[DEV-4087](https://federal-spending-transparency.atlassian.net/browse/DEV-4087)
**Mockup**
N/A
Author: 
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …
=> Hotfix: IE White Screen Fix (master)

src/js/components/SharedComponents/navigation/NavigationComponent.jsx
Adds the Dashboard link to DABS navigation. 
[DEV-3964](https://federal-spending-transparency.atlassian.net/browse/DEV-3964)
**Mockup**
https://bahdigital.invisionapp.com/share/7GIABMNX8MV#/296021488_Historical-Search-Monthly-Single-No-Data
Author: 
- Verified mobile/tablet/desktop/monitor responsiveness - created [DEV-4101](https://federal-spending-transparency.atlassian.net/browse/DEV-4101) to address a mobile navigation bug outside the scope of this story
Reviewer(s):
=> DEV-4042 release dashboard MVP

src/_scss/pages/reviewData/_content.scss, src/_scss/pages/reviewData/bottomSide/bottomSide.scss, src/js/components/reviewData/ReviewDataContent.jsx
Making the DABS monthly certify error text not overlap with the buttons and fixing the buttons so they don't expand like crazy for monthly submissions
N/A
[DEV-2335](https://federal-spending-transparency.atlassian.net/browse/DEV-2335)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-2335: Monthly dabs certify page cleanup

src/js/components/submissionsTable/filters/SubmissionIdFilter.jsx
Changing the submission ID input to a number type and fixing an accessibility issue
N/A
[DEV-2123](https://federal-spending-transparency.atlassian.net/browse/DEV-2123)
**Mockup**
N/A
Author: 
- All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339)
Reviewer(s):
- Design …
=> DEV-2123: Submission table id filter

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
- All componentWillReceiveProps in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339) …
=> Sprint 96 Release Notes

src/js/helpers/periodPickerHelper.js
Changeover the fiscal year on the same date that period 2 becomes available.
[DEV-4011](https://federal-spending-transparency.atlassian.net/browse/DEV-4011)
Author: 
Reviewer(s):
=> Fix DEV-4011 FY picker

src/_scss/pages/dashboard/table/_dashboardTable.scss
Moving the margin so the scroll bar is flush with the content of the table
N/A
[DEV-4159](https://federal-spending-transparency.atlassian.net/browse/DEV-4159)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-4159: Dashboard table spacing

src/help/changelog.md
DABS Reporting Schedule for 2020, not 2019
=> Hotfix - Release Notes Typo

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
(see title)
N/A
**Mockup**
N/A
Author: 
- All componentWillReceiveProps in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339)
Reviewer(s):
-  Design review completed
=> Sprint 97 Release Notes (master)

src/js/containers/router/ProtectedComponent.jsx, src/js/containers/router/RouterRoutes.jsx, tests/containers/router/ProtectedComponent-test.jsx, tests/containers/router/ProtectedRoute-test.jsx, tests/containers/router/RouterRoutes-test.jsx, tests/containers/router/mockLoginHelper.js, tests/containers/router/mockLoginHelper2.js, tests/containers/router/mockProps.js
Adds unit tests for the components `RouterRoutes`, `ProtectedRoute`, and `ProtectedComponent`
[DEV-3857](https://federal-spending-transparency.atlassian.net/browse/DEV-3857)
**Testing**
No impact to end user.
Author: 
Reviewer(s):
=> DEV-3857 router unit tests

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
(see title)
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Sprint 99 Release Notes (warmfix)

src/js/components/history/HistoryPage.jsx, src/js/components/reviewData/CertificationModal/ReviewDataCertifyModal.jsx
- Resolves a conflict between `master` and `staging`
- Demotes hotfixes from `master` to `staging`
1. Branched `resolve-merge-conflicts` off of `staging`
2. Merged `master` into `resolve-merge-conflicts`
3. Resolved ensuing conflicts
4. This PR merges `resolve-merge-conflicts` into `staging`, demoting the hotfixes and preventing future conflicts when we promote `staging` to `master`
Reviewer(s):
=> Resolve merge conflicts

src/js/components/dashboard/DashboardPage.jsx, src/js/components/dashboard/filters/CreatedByFilter.jsx, src/js/containers/dashboard/filters/CreatedByFilterContainer.jsx, src/js/redux/reducers/dashboard/dashboardFiltersReducer.js, tests/containers/dashboard/filters/CreatedByFilterContainer-test.jsx, tests/containers/dashboard/filters/mockFilters.js
Adds a "Created By" filter to the Active dashboard. 
- Uses the existing `Autocomplete` component
- Updates Redux to store both the name and user id
[DEV-4288](https://federal-spending-transparency.atlassian.net/browse/DEV-4288)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/296030436_Active_-_MVP_-_Entry_5
Author: 
Reviewer(s):
=> DEV-4288 Created By filter

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
Author: 
Reviewer(s):
=> Sprint 99 Release Notes

src/_scss/pages/dashboard/_filterSidebar.scss, src/_scss/pages/dashboard/filters/_dashboardAgencyFilter.scss, src/_scss/pages/dashboard/filters/_lastModified.scss, src/_scss/pages/dashboard/filters/_selectedFilters.scss, src/_scss/pages/dashboard/filters/_submissionIdFilter.scss, src/js/components/dashboard/DashboardPage.jsx, src/js/components/dashboard/filters/SubmissionIdFilter.jsx, src/js/containers/dashboard/filters/SubmissionIdFilterContainer.jsx, tests/containers/dashboard/filters/LastModifiedFilterContainer-test.jsx, tests/containers/dashboard/filters/SubmissionIdFilterContainer-test.jsx
Adds a Submission ID filter to the Active Dashboard page.
* The "Add" button (not included in mock) references the Submissions Table Submission ID filter
* Includes styling updates to the Last Modified filter for consistent treatment of input text
[DEV-4290](https://federal-spending-transparency.atlassian.net/browse/DEV-4290)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/296030432_Active_-_MVP_-_Entry_1
Author: 
Reviewer(s):
=> DEV-4290 Submission ID filter

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
Sprint 100 Release Notes
N/A
N/A
Author: 
Reviewer(s):
=> Warmfix: Sprint 100 Release Notes (staging)

src/js/GlobalConstants.js, webpack/webpack.dev.config.js, webpack/webpack.prod.config.js
Adding `PUBLIC_FILES` to the GlobalConstants.
N/A
[DEV-4427](https://federal-spending-transparency.atlassian.net/browse/DEV-4472)
**Mockup**
N/A
Author: 
Reviewer(s):
=> Updating GlobalConstants.js to include PUBLIC_FILES from the environment

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Warmfix: Sprint 101 Release Notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Warmfix: Sprint 102 Release Notes

src/js/components/dashboard/NoResultsMessage.jsx, src/js/containers/dashboard/ActiveDashboardContainer.jsx, src/js/helpers/dashboardHelper.js
- Adds an error message when there is a request error, instead of showing the no results message
- Updated the API request helper to provide a more detailed error message
Author: 
Reviewer(s):
=> Active Dashboard Error Message

src/_scss/pages/modals/dashboard/_dashboardModal.scss, src/js/components/dashboard/table/ActiveDashboardTableModal.jsx, src/js/containers/dashboard/table/ActiveDashboardTableContainer.jsx
Adding in the modal for the active dashboard table
N/A
[DEV-1234](https://federal-spending-transparency.atlassian.net/browse/DEV-1234)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/screens/296030452
Author: 
Reviewer(s):
=> DEV-4308: active dashboard table modal

src/_scss/pages/dashboard/dashboard.scss, src/js/components/dashboard/ActiveDashboard.jsx, src/js/components/dashboard/ActiveDashboardOverview.jsx, src/js/containers/dashboard/ActiveDashboardContainer.jsx
Adds a button to go back to the submission selection table
- Button doesn't exist if there was only one result and therefore no submission table to select from
[DEV-4319](https://federal-spending-transparency.atlassian.net/browse/DEV-4319)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/screens/296030448
Author: 
Reviewer(s):
=> DEV-4319: active dashboard back button

src/js/containers/dashboard/table/ActiveDashboardTableContainer.jsx
Update default sort order for active dashboard table
Nothing has changed except the default sort order so most of the PR checklist shouldn't matter
[DEV-4846](https://federal-spending-transparency.atlassian.net/browse/DEV-4846)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-4846: Active dashboard table default sort

src/_scss/pages/dashboard/graph/_categoryButtons.scss, src/js/components/dashboard/graph/CategoryButton.jsx, src/js/components/dashboard/graph/DashboardGraph.jsx, src/js/components/dashboard/graph/SignificanceGraph.jsx
Allows filtering rules out of the graph based on category by clicking buttons in the graph legend. 
- Maintain an array of categories the user is currently viewing, and pass a subset of the rules data to the graph
- Disable the button if no rules of that category exist in the original dataset 
[DEV-4315](https://federal-spending-transparency.atlassian.net/browse/DEV-4315)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/296030449_Active_-_MVP_-_2
Author: 
Reviewer(s):
=> DEV-4315 filter significance graph

src/_scss/pages/dashboard/_dashboardViz.scss, src/_scss/pages/dashboard/dashboard.scss, src/_scss/pages/dashboard/impacts/_impacts.scss, src/js/components/SharedComponents/ErrorMessageOverlay.jsx, src/js/components/SharedComponents/LoadingBars.jsx, src/js/components/SharedComponents/LoadingMessage.jsx, src/js/components/dashboard/ActiveDashboardOverview.jsx, src/js/components/dashboard/impacts/ActiveDashboardImpacts.jsx, src/js/components/dashboard/impacts/DashboardImpactsModal.jsx, src/js/components/dashboard/impacts/ImpactGauge.jsx, src/js/containers/dashboard/ActiveDashboardImpactsContainer.jsx, src/js/containers/dashboard/ActiveDashboardOverviewContainer.jsx
Updating Active Dashboard Overview and Impacts visualizations for Error, None, Impact states
* Modified the Error Message and Loading Message overlays to be more customizable
[DEV-4320](https://federal-spending-transparency.atlassian.net/browse/DEV-4320)
**Mockup**
Author: 
Reviewer(s):
=> DEV-4320: Error, None, Loading States for Active Dashboard (Overview, Impacts)

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
Release Notes for Sprint 104
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Sprint 104 Release Notes (warmfix)

src/js/components/dashboard/ActiveDashboard.jsx, src/js/components/dashboard/ActiveDashboardOverview.jsx, src/js/components/dashboard/table/ActiveDashboardTable.jsx
* Default to the errors tab
* Format number of instances in the summary section and in the table
=> Active dashboard updates

src/js/components/SharedComponents/SubmissionWarningBanner.jsx, src/js/components/dashboard/graph/active/SignificanceCircle.jsx, src/js/components/dashboard/graph/historical/StackedBar.jsx
=> Demote warmfix qat -> dev

src/_scss/components/alerts/_alerts.scss, src/_scss/components/messages/_messages.scss, src/_scss/pages/dashboard/graph/_dashboardGraph.scss, src/_scss/pages/modals/settings/_messages.scss, src/_scss/pages/modals/settings/_ruleSettings.scss, src/_scss/pages/modals/settings/_saveStatus.scss, src/_scss/pages/modals/settings/_settingsModal.scss, src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/dashboard/ChooseFiltersMessage.jsx, src/js/components/settings/SaveSettingsButton.jsx, src/js/components/settings/SettingsModal.jsx, src/js/components/settings/table/SettingsTable.jsx, src/js/containers/dashboard/DashboardContentContainer.jsx, src/js/containers/settings/SettingsTableContainer.jsx, src/js/dataMapping/dashboard/fileLabels.js, src/js/helpers/dndHelper.js, src/js/helpers/settingsHelper.js, src/js/helpers/settingsTableHelper.js, tests/helpers/dndHelper-test.js, tests/helpers/settingsTableHelper-test.js
Allow users to save changes to their agency's settings. Includes styled loading, error, and no results messages.
[DEV-4299](https://federal-spending-transparency.atlassian.net/browse/DEV-4299)
**Mockup**
https://bahdigital.invisionapp.com/share/QEIACQKF2JW#/296031034_Active_-_Settings_7
Also see attachment in JIRA for success message mockup
Author: 
Reviewer(s):
=> DEV-4299 save settings

src/js/components/SharedComponents/navigation/UserButton.jsx
Allow the settings navigation link to appear in production. 
[DEV-4360](https://federal-spending-transparency.atlassian.net/browse/DEV-4360)
Author: 
Reviewer(s):
=> DEV-4360 Enable the settings modal in prod

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Hotfix: Sprint 105 Release Notes

src/js/components/help/resourcesContent.jsx
Simply updating the Help page links for DAIMS 1.4.
N/A
[DEV-3626](https://federal-spending-transparency.atlassian.net/browse/DEV-3626)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-3626: Update DAIMS Rules and P&P links for DAIMS 1.4 (warmfix)

src/js/components/history/HistoryHeader.jsx, src/js/components/history/HistoryTable.jsx, src/js/components/uploadFabsFile/UploadFabsFileHeader.jsx, src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx, src/js/containers/reviewData/ReviewDataContainer.jsx, tests/containers/generateFiles/mockReviewHelper.js
Fixing several dates to show as local time rather than UCT
Dates altered:
- Created and Last Validated dates in the certification history page
- Publish date within a FABS submission
- Created date on the review page of a DABS submission
Also fixed spacing in the certify history page finally
[DEV-2771](https://federal-spending-transparency.atlassian.net/browse/DEV-2771)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-2771: fabs date

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Warmfix: Sprint 106 Release Notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
(see title)
N/A
**Mockup**
N/A
Author: 
-  Linked to this PR in JIRA ticket
Reviewer(s):
=> Sprint 107 Release Notes (warmfix)

package-lock.json, src/js/containers/dashboard/filters/FyFilterContainer.jsx, src/js/containers/dashboard/filters/QuarterFilterContainer.jsx, src/js/helpers/dashboardHelper.js, tests/containers/dashboard/ActiveDashboardContainer-test.jsx
Updating based on changes in backend ticket so things don't break
- Renaming `last_certification_period` endpoint
- Dividing by 3 to get the quarter since we're receiving period now on the frontend
[DEV-5019](https://federal-spending-transparency.atlassian.net/browse/DEV-5019)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-5019: period submission windows

package-lock.json, src/js/components/addData/AddDataMeta.jsx, src/js/components/history/HistoryTable.jsx, src/js/containers/dashboard/filters/FyFilterContainer.jsx, src/js/containers/dashboard/filters/QuarterFilterContainer.jsx, src/js/helpers/agencyHelper.js, src/js/helpers/dashboardHelper.js, src/js/helpers/submissionListHelper.js, tests/containers/dashboard/ActiveDashboardContainer-test.jsx
All the changes from CARES that we've been putting in a separate branch
See previous PRs
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> daims 2.0 cares updates

src/_scss/pages/modals/modals.scss, src/_scss/pages/modals/sharedModal.scss, src/js/components/SharedComponents/Modal.jsx, src/js/components/addData/AddDataMeta.jsx, src/js/components/addData/AddDataPage.jsx, src/js/components/addData/metadata/DateRangeField.jsx, src/js/helpers/agencyHelper.js, src/js/helpers/uploadHelper.js, src/js/redux/actions/uploadActions.js
Updated check for published submissions after specifying agency/period/fy.
* Updated sharedModal to be more dynamic in case we want other confirming submissions with more options.
[DEV-5218](https://federal-spending-transparency.atlassian.net/browse/DEV-5218)
**Mockup**
https://bahdigital.invisionapp.com/share/U2IADY6D4N8#/screens/296037785
Author: 
Reviewer(s):
=> DEV-5218: Published Submission Modal Updates

package-lock.json, src/_scss/pages/history/history.scss, src/js/components/history/HistoryTable.jsx, src/js/helpers/submissionListHelper.js
Adding a `Publish History` section to the submission history page
N/A
[DEV-5314](https://federal-spending-transparency.atlassian.net/browse/DEV-5314)
**Mockup**
https://bahdigital.invisionapp.com/share/3GIADWAYQTZ#/screens
Author: 
Reviewer(s):
=> DEV-5314: split submission history

src/js/components/SharedComponents/SubmissionWarningBanner.jsx, src/js/components/addData/AddDataPage.jsx
Updating the DABS banners given the changes to the workflow.
* Updated the warning banner when creating submissions
[DEV-5316](https://federal-spending-transparency.atlassian.net/browse/DEV-5316)
**Mockup**
https://bahdigital.invisionapp.com/share/KSIADYNPUW9#/screens/296037790
Author: 
Reviewer(s):
=> DEV-5316: Updating DABS Banners

src/js/components/history/HistoryTable.jsx
We don't always want to check certifications, sometimes we're looking at publications now
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Hotfix: publish history page bug

src/js/components/help/resourcesContent.jsx
Updating the DAIMS links on the DAIMS resources page.
N/A
[DEV-5539](https://federal-spending-transparency.atlassian.net/browse/DEV-5539)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-5539: Updating DAIMS links to DAIMS 2.0 (warmfix)

src/js/components/crossFile/components/ComparisonTable.jsx
Replacing "Error Message" with "Rule Message"
N/A
[DEV-5328](https://federal-spending-transparency.atlassian.net/browse/DEV-5328)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-5328: Rule error message

src/js/components/reviewData/ReviewDataNotifyModal.jsx
Fixing the header in the notify user modal
N/A
[DEV-5223](https://federal-spending-transparency.atlassian.net/browse/DEV-5223)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-5223: Notify user modal update

src/js/components/landing/BlockContent.jsx
(see title)
N/A
[DEV-5566](https://federal-spending-transparency.atlassian.net/browse/DEV-5566)
**Mockup**
N/A (see JIRA ticket comment)
Author: 
Reviewer(s):
=> DEV-5566: Update front page DABS description (warmfix)

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Sprint 110 Release Notes (hotfix)

src/js/components/reviewData/ReviewDataContent.jsx
Including submitter permissions in the revalidate allowance
Don't forget to check for submitters
[DEV-5889](https://federal-spending-transparency.atlassian.net/browse/DEV-5889)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-5889: Revalidate submission permissions

src/js/components/addData/AddDataContent.jsx, src/js/components/uploadFabsFile/UploadFabsFileMeta.jsx
"these make take longer" -> "these may take longer"
N/A
[DEV-5999](https://federal-spending-transparency.atlassian.net/browse/DEV-5999)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-5999: Minor typo in Upload Disclaimers

src/js/containers/router/RouterRoutes.jsx
Redirecting users to login page when they reach the Dashboard without logging in. 
N/A
[DEV-4989](https://federal-spending-transparency.atlassian.net/browse/DEV-4989)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-4989: Dashboard redirect when not logged in

src/js/containers/submissionsTable/FilterBarContainer.jsx
Making sure to actually check that the key exists
N/A
[DEV-6104](https://federal-spending-transparency.atlassian.net/browse/DEV-6104)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6104: Submission table filter error

src/js/components/crossFile/components/ErrorBox.jsx, src/js/components/crossFile/components/FileComponent.jsx, src/js/components/generateEF/GenerateEFOverlay.jsx, src/js/components/generateEF/generateItem/GenerateEFItem.jsx, src/js/components/generateFiles/GenerateFilesContent.jsx, src/js/components/generateFiles/GenerateFilesOverlay.jsx, src/js/components/reviewData/ReviewDataContent.jsx, src/js/components/reviewData/ReviewDataNarrative.jsx, src/js/components/validateData/ValidateDataErrorReport.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx, src/js/components/validateData/validateValues/ValidateValuesFileComponent.jsx
Adding "publishing" status to the blocks that exist for "reverting" status on DABS submissions
Adding same blocks to the publishing status that the reverting status has
[DEV-6084](https://federal-spending-transparency.atlassian.net/browse/DEV-6084)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6084: DABS publishing state

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Sprint 115 Release Notes

src/js/components/help/helpContent.jsx
Updating text in the help section to not include mention of a "sandbox session"
N/A
[DEV-2243](https://federal-spending-transparency.atlassian.net/browse/DEV-2243)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-2243: remove sandbox session reference

src/_scss/pages/generateFiles/generateItem/_download.scss, src/js/components/generateDetachedFiles/DetachedFileA.jsx, src/js/components/generateDetachedFiles/DownloadFile.jsx
Disabling file download for file A while regenerating the file
N/A
[DEV-2716](https://federal-spending-transparency.atlassian.net/browse/DEV-2716)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-2716: File A download disabled

src/help/history.md, src/help/technicalHistory.md
Removing all the non-working links from the release history page
- Also removing all the excess technical sections from the technical history since there's no reason to have multiple sections with the same name
[DEV-2236](https://federal-spending-transparency.atlassian.net/browse/DEV-2236)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-2236: Release notes archive cleanup

src/js/components/landing/recentActivity/RecentActivityTable.jsx
Cleaning up Recent Activity Table contents and alignment
Adjusting some of the content to match the submission table so they're consistent
- Changed `Start` and `End` in the FABS date range to `Earliest` and `Latest`
- Changed `Submission ID` column header in DABS to `View` for consistency
- Left aligned all the contents of the table other than the delete button and the FABS submission ID
[DEV-1234](https://federal-spending-transparency.atlassian.net/browse/DEV-1234)
**Mockup**
N/A
Author: 
- Verified …
=> DEV-1922: Agency table header alignment

src/_scss/pages/modals/reviewData/_selectedUsers.scss, src/js/app.jsx, src/js/components/reviewData/ReviewDataSelectedUser.jsx
Updating CSS of button to make it align better and actually fill with the proper color
N/A
[DEV-2235](https://federal-spending-transparency.atlassian.net/browse/DEV-2235)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-2235: Misaligned icon send notification

src/_scss/pages/generateDetachedFiles/_periodPicker.scss, src/js/components/generateDetachedFiles/PeriodButton.jsx, src/js/components/generateDetachedFiles/PeriodButtonWithTooltip.jsx, src/js/components/generateDetachedFiles/PeriodPicker.jsx
Fixing the spacing in the tooltip and the hover for the dropdown
N/A
[DEV-2482](https://federal-spending-transparency.atlassian.net/browse/DEV-2482)
**Mockup**
https://bahdigital.invisionapp.com/share/5SIAF4WPFUA#/screens/296050005
Author: 
Reviewer(s):
=> DEV-2482: File A generation tooltip dropdown

src/js/components/addData/metadata/DateRangeField.jsx
Updating the default start and end dates for monthly submissions to include the P01/P02 combo correctly
N/A
[DEV-6200](https://federal-spending-transparency.atlassian.net/browse/DEV-6200)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6200: DABS monthly default

src/js/components/help/helpSidebar.jsx
Adding the link for the FY21 reporting schedule
N/A
[DEV-6208](https://federal-spending-transparency.atlassian.net/browse/DEV-6208)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6208: FY21 reporting schedule

src/_scss/pages/history/history.scss
Preventing two publish/certify records from showing on the same line in submission history
N/A
[DEV-5669](https://federal-spending-transparency.atlassian.net/browse/DEV-5669)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-5669: Submission history alignment

Dockerfile
adding verbosity to npm install. This should allow the output of where exactly over the internet NPM is reaching out to to pull down the various packages in package.json. 
We will also see the pre and post install steps for any NPM packages and their output.
=> adding verbosity to npm install

src/_scss/pages/reviewData/narrative/narrative.scss, src/js/components/reviewData/ReviewDataNarrative.jsx
Adding a note to make sure agencies know that comments are available on USAS after publishing.
N/A
[DEV-6303](https://federal-spending-transparency.atlassian.net/browse/DEV-6303)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6303: DABS commenting publish note

src/js/components/help/helpSidebar.jsx
Removing the FY20 reporting schedule link
N/A
[DEV-6227](https://federal-spending-transparency.atlassian.net/browse/DEV-6227)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6227: Remove FY20 schedule link

src/js/components/addData/metadata/DateDropdown.jsx, src/js/components/landing/recentActivity/RecentActivityTable.jsx, src/js/components/submission/SubmissionHeader.jsx, src/js/components/submissionsTable/SubmissionsTable.jsx
Updating displays for DABS reporting period selection and adding a couple of labels to other reporting periods on the site
N/A
[DEV-6549](https://federal-spending-transparency.atlassian.net/browse/DEV-6549)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6549: reporting period label displays

src/js/helpers/periodPickerHelper.js
Updating dates for the periods in FY21
N/A
[DEV-6556](https://federal-spending-transparency.atlassian.net/browse/DEV-6556)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6556: Most recent period start dates

src/js/containers/router/RouterRoutes.jsx
Adding editfabs as a user that can upload new fabs files
N/A
[DEV-4486](https://federal-spending-transparency.atlassian.net/browse/DEV-4486)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-4486: editfabs user upload

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Sprint 123 Release Notes

src/_scss/pages/reviewData/narrative/narrative.scss, src/js/components/reviewData/Narrative/ReviewDataNarrative.jsx
=> Design review update

package-lock.json, package.json, src/_scss/pages/reviewData/_content.scss, src/_scss/pages/reviewData/narrative/narrative.scss, src/js/components/reviewData/Narrative/ReviewDataNarrative.jsx, src/js/components/reviewData/Narrative/ReviewDataNarrativeCollapsed.jsx, src/js/components/reviewData/Narrative/ReviewDataNarrativeTextfield.jsx, src/js/components/reviewData/RevertToCertified.jsx, src/js/components/reviewData/ReviewDataContent.jsx
Provide a visual warning when there are unsaved changes and a popup warning if the user tries to navigate away from the page while there are unsaved changes. It also warns the user if there are non-ascii characters in the comments boxes (they can still save the files)
N/A
[DEV-6650](https://federal-spending-transparency.atlassian.net/browse/DEV-6650)
[DEV-6542](https://federal-spending-transparency.atlassian.net/browse/DEV-6542)
**Mockup**
https://bahdigital.invisionapp.com/share/5BIAFVXZMV7#/screens/296054062
Author: 
Reviewer(s):
=> DEV-6650/6542: unsaved/invalid comment warnings

src/js/components/addData/AddDataMeta.jsx, src/js/components/addData/metadata/SubmissionTypeField.jsx, src/js/helpers/util.js, tests/helpers/util-test.js
Forcing quarterly submissions starting in FY22 onward to be tests via the frontend.
N/A
[DEV-6734](https://federal-spending-transparency.atlassian.net/browse/DEV-6734)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6734: fy22 quarterly submissions test only

src/js/components/reviewData/ReviewDataContent.jsx
Fixing which URL is commented out.
N/A
[DEV-6757](https://federal-spending-transparency.atlassian.net/browse/DEV-6757)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6757: Remove right link

src/js/components/help/historyContent.jsx
Adding a note about old links to the release notes archives page
N/A
[DEV-6245](https://federal-spending-transparency.atlassian.net/browse/DEV-6245)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6245: invalid link warning release notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Sprint 128 Release Notes

src/js/components/landing/recentActivity/RecentActivityTable.jsx, src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx
Adding the FABS banner to the "no such submission" or "this is a DABS submission" page on FABS.
N/A
[DEV-3731](https://federal-spending-transparency.atlassian.net/browse/DEV-3731)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-3731: fabs banner no submission

src/_scss/layouts/default/header/_menuBar.scss
Fix the view when a read-only user is logged in and viewing submissions
Displaying none on the "after" of the list
[DEV-6959](https://federal-spending-transparency.atlassian.net/browse/DEV-6959)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6959: Read only css fixes

src/js/containers/submissionsTable/SubmissionsTableContainer.jsx
Removing data rows before reloading a table
N/A
[DEV-2372](https://federal-spending-transparency.atlassian.net/browse/DEV-2372)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-2372: Gathering your data table message

package-lock.json, package.json
Simply running an `npm audit fix` to resolve any security concerns.
* Didn't update `superagent-use` as updating that would require further code changes.
[DEV-7081](https://federal-spending-transparency.atlassian.net/browse/DEV-7081)
[DEV-7082](https://federal-spending-transparency.atlassian.net/browse/DEV-7082)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-7081/DEV-7082: Security Update

package-lock.json, package.json, src/js/components/SharedComponents/table/ScrollableTable.jsx, src/js/components/validateData/validateValues/ValidateValuesErrorReport.jsx
Fixing the sorting on the error/warning boxes in the initial file upload pages. Also removing the sort capability for the field names column.
N/A
[DEV-4421](https://federal-spending-transparency.atlassian.net/browse/DEV-4421)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-4421 error warning rule sorting

src/_scss/pages/crossFile/crossFile.scss, src/_scss/pages/generateDetachedFiles/detachedFileA.scss, src/_scss/pages/generateDetachedFiles/generateDetachedFiles.scss, src/_scss/pages/generateEF/generateEF.scss, src/_scss/pages/generateFiles/generateFiles.scss, src/_scss/pages/reviewData/reviewData.scss, src/_scss/pages/validateData/validateData.scss, src/js/components/generateDetachedFiles/DetachedFileA.jsx, src/js/components/generateDetachedFiles/GenerateDetachedFilesPage.jsx, src/js/components/help/helpPage.jsx, src/js/components/help/resourcesPage.jsx, src/js/components/reviewData/ReviewDataPage.jsx, src/js/components/submission/SubmissionPage.jsx, src/js/containers/crossFile/CrossFileContentContainer.jsx, src/js/containers/generateEF/GenerateEFContainer.jsx, src/js/containers/generateFiles/GenerateFilesContainer.jsx, src/js/containers/validateData/ValidateDataContainer.jsx
Adding DABS/FABS/ALL announcement banners to all pages they are missing from. Also rearranged how they sit in DABS while fixing a positioning issue with them.
N/A
[DEV-3684](https://federal-spending-transparency.atlassian.net/browse/DEV-3684)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-3684: missing banners

src/js/components/reviewData/ReviewDataContent.jsx
Uncommenting the link to the About the Data table
N/A
[DEV-6758](https://federal-spending-transparency.atlassian.net/browse/DEV-6758)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-6758: Add about the data link

src/js/components/reviewData/ReviewDataContent.jsx
See title
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Updating name of ASSP to be consistent with messaging

src/_scss/pages/dashboard/_dashboardViz.scss, src/_scss/pages/dashboard/dashboard.scss, src/_scss/pages/dashboard/table/_dashboardTable.scss, src/js/components/dashboard/HistoricalDashboard.jsx, src/js/components/dashboard/filters/DashboardAgencyFilter.jsx, src/js/components/dashboard/graph/DashboardGraph.jsx, src/js/components/dashboard/table/DashboardTable.jsx, src/js/containers/dashboard/ActiveDashboardContainer.jsx, src/js/containers/dashboard/filters/DashboardAgencyFilterContainer.jsx, src/js/containers/dashboard/graph/WarningsInfoGraphContainer.jsx, src/js/containers/dashboard/table/DashboardTableContainer.jsx, src/js/redux/reducers/dashboard/dashboardFiltersReducer.js, tests/containers/dashboard/filters/DashboardAgencyFilterContainer-test.jsx, tests/containers/dashboard/graph/WarningsInfoGraphContainer-test.jsx, tests/containers/dashboard/table/DashboardTableContainer-test.jsx, tests/redux/dashboard/dashboardFiltersReducer-test.js
Removing individual table/graph headers and updating the main header to better express what users are looking at
N/A
[DEV-7285](https://federal-spending-transparency.atlassian.net/browse/DEV-7285)
**Mockup**
https://bahdigital.invisionapp.com/share/SDIAGOGWQXA#/screens/296059059
Author: 
Reviewer(s):
=> DEV-7285: historic dashboard header updates

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Hotfix: Sprint 133 Release Notes

src/_scss/pages/dashboard/graph/_dashboardGraph.scss, src/js/components/dashboard/graph/DashboardGraph.jsx, src/js/components/dashboard/graph/DashboardGraphTooltip.jsx, src/js/components/dashboard/graph/historical/BarChartStacked.jsx, src/js/components/dashboard/graph/historical/HistoricalDashboardTooltip.jsx, src/js/components/dashboard/graph/historical/StackedBar.jsx, src/js/components/dashboard/graph/historical/StackedBarGroup.jsx
Updating the historical dashboard graph tooltip to match the new design.
N/A
[DEV-7297](https://federal-spending-transparency.atlassian.net/browse/DEV-7297)
**Mockup**
https://bahdigital.invisionapp.com/share/8UIAH0B9YD7#/screens/296059063
Author: 
Reviewer(s):
=> DEV-7297: historical dashboard graph tooltip

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Hotfix: Sprint 135 Release Notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Downmerge to Staging: Sprint 135 Release Notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Downmerge to QAT: Sprint 135 Release Notes

src/js/components/dashboard/graph/DashboardGraph.jsx, src/js/components/dashboard/graph/DashboardGraphTooltip.jsx, src/js/components/dashboard/graph/active/SignificanceCircle.jsx, src/js/components/dashboard/graph/active/SignificanceGraph.jsx, src/js/components/dashboard/graph/historical/BarChartStacked.jsx, src/js/components/dashboard/graph/historical/StackedBarGroup.jsx
Adjusting the X axis scaling, tooltips, and bar widths to account for various widths based on the min/max and quarters/periods.
N/A
[DEV-7300](https://federal-spending-transparency.atlassian.net/browse/DEV-7300)
**Mockup**
https://bahdigital.invisionapp.com/share/SDIAGOGWQXA#/screens/296059058
Author: 
Reviewer(s):
=> DEV-7300: X Axis Bar Widths

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
(see title)
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Hotfix: Sprint 136 Release Notes

src/_scss/pages/uploadFabsFile/uploadFabsFile.scss, src/js/components/addData/metadata/SubmissionTypeField.jsx, src/js/components/submissionsTable/SubmissionsTableFilters.jsx, src/js/components/uploadFabsFile/UploadFabsFileMeta.jsx, src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx, src/js/helpers/uploadHelper.js
Allowing FABS to be test submissions as well.
N/A
[DEV-7570](https://federal-spending-transparency.atlassian.net/browse/DEV-7570)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-7570: fabs test submission

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Sprint 137 Release Notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Sprint 137 Release Notes (QAT)

src/js/components/help/helpSidebar.jsx
Add link to FY22 DABS reporting schedule
N/A
[DEV-7812](https://federal-spending-transparency.atlassian.net/browse/DEV-7812)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-7812: FY22 Broker Schedule Link

src/js/components/uploadFabsFile/PublishModal.jsx
Adding more clarifying text to the FABS publish modal.
N/A
[DEV-7921](https://federal-spending-transparency.atlassian.net/browse/DEV-7921)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-7921 fabs publish modal text

src/js/components/help/DataSourcesItem.jsx
Adding the word "about" in the "updated" date on the data sources page
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Fix: add about to data sources

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Sprint 141 Release Notes (master)

src/js/components/help/DataSourcesItem.jsx
Assuming all date values for Data Sources coming from the DB are in UTC and adjusting them to local time
N/A
[DEV-8093](https://federal-spending-transparency.atlassian.net/browse/DEV-8093)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8093: data sources utc local time

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Hotfix: Sprint 142 Release Notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Hotfix Downmerge: Sprint 142 Release Notes

src/_scss/pages/validateData/fileItem/body/textBody.scss, src/_scss/sharedComponents/_progressBar.scss, src/_scss/sharedComponents/sharedComponents.scss, src/js/components/SharedComponents/ProgressBar.jsx, src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx, src/js/components/validateData/ValidateDataFileComponent.jsx, src/js/components/validateData/ValidationContent.jsx, src/js/containers/validateData/ValidateDataContainer.jsx, src/js/containers/validateData/ValidateDataFileContainer.jsx, src/js/containers/validateData/ValidationOverlayContainer.jsx
Adding progress bars to FABS/DABS initial validations
Adding a shared progress bar component that can be used across the site.
[DEV-7980](https://federal-spending-transparency.atlassian.net/browse/DEV-7980)
**Mockup**
https://bahdigital.invisionapp.com/share/TCIAHRSVZH2#/screens/296066421
Author: 
Reviewer(s):
=> DEV-7980: validation progress bars

src/js/components/help/helpSidebar.jsx
Removing FY21 reporting window schedule link
N/A
[DEV-7813](https://federal-spending-transparency.atlassian.net/browse/DEV-7813)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-7813: Remove fy21 submission schedule

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> (Hotfix) Sprint 143 Release Notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> (Staging) Sprint 143 Release Notes

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> (QAT) Sprint 143 Release Notes

src/js/components/SharedComponents/ProgressBar.jsx, src/js/components/crossFile/CrossFileContent.jsx, src/js/containers/crossFile/CrossFileContentContainer.jsx
Adding a progress bar to the cross-file validation page
- Also changing the default number of decimal places for the progress bar
- Adding a percent sign to the progress bar
N/A
[DEV-8137](https://federal-spending-transparency.atlassian.net/browse/DEV-8137)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8137: cross file validation progress bar

src/js/components/history/HistoryTable.jsx, src/js/helpers/util.js
Adding a timestamp for publish/certify dates in the DABS history table
N/A
[DEV-7263](https://federal-spending-transparency.atlassian.net/browse/DEV-7263)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-7263: dabs publish history full timestamp

src/js/components/generateDetachedFiles/DetachedFileA.jsx
Updating detached a note text
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Fix: update detached a note text

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Warmfix: Sprint-144 release notes

src/js/components/help/helpContent.jsx
Simply updating an outdated statement regarding the Service Desk on the Help Page.
N/A
[DEV-8337](https://federal-spending-transparency.atlassian.net/browse/DEV-8337)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8337: Updating Service Desk Statement on Help Page

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Sprint 145 Release Notes (Prod)

src/js/helpers/loginHelper.js, webpack/webpack.dev.config.js, webpack/webpack.prod.config.js
Using "active_user" instead of "current_user" on the FE.
N/A
[DEV-8246](https://federal-spending-transparency.atlassian.net/browse/DEV-8246)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8246: Current User -> Active User

src/_scss/pages/addData/_content.scss, src/js/components/addData/metadata/DateDropdown.jsx, src/js/components/addData/metadata/DateRangeField.jsx, src/js/components/addData/metadata/DateTypeField.jsx
Prevent the user from creating quarterly submissions later than FY21
N/A
[DEV-8252](https://federal-spending-transparency.atlassian.net/browse/DEV-8252)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8252: prevent fy22 quarterly submissions

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
N/A
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Sprint 146 Release Notes (Staging)

src/js/components/help/resourcesContent.jsx
Updating links for Resources on the Help page
N/A
[DEV-8391](https://federal-spending-transparency.atlassian.net/browse/DEV-8391)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8391: DAIMS document links

src/_scss/layouts/login/loginForm/loginForm.scss, src/js/components/SharedComponents/ErrorMessage.jsx
Adding alert CSS back to login page
Replacing our SVG with font awesome in a continued effort to update them all
[DEV-8466](https://federal-spending-transparency.atlassian.net/browse/DEV-8466)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8466: login failure css

src/js/components/help/resourcesContent.jsx
Updating help page links to newest versions
N/A
[DEV-8656](https://federal-spending-transparency.atlassian.net/browse/DEV-8656)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8656: daims 2.1 links

src/js/components/settings/SettingsModal.jsx, src/js/containers/settings/SettingsAgencySelectContainer.jsx, tests/containers/settings/SettingsAgencySelectContainer-test.jsx, tests/containers/settings/mockProps.js
Fixing the agency selection in the settings modal
Updating to expect the object like other sections that use this component.
[DEV-8570](https://federal-spending-transparency.atlassian.net/browse/DEV-8570)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8570: settings agency dropdown

src/js/containers/SharedContainers/RevalidateContainer.jsx
Making sure the button text doesn't spill over when a user has read-only permissions.
N/A
[DEV-7133](https://federal-spending-transparency.atlassian.net/browse/DEV-7133)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-7133: read only permission button text

src/js/helpers/createdByHelper.js, src/js/helpers/reviewHelper.js
Renaming `d2_submission` to `is_fabs` in all relevant locations
N/A
[DEV-2022](https://federal-spending-transparency.atlassian.net/browse/DEV-2022)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-2022: Rename d2 column submission

src/js/components/help/resourcesContent.jsx
Updating description text in the help section for Practices & Procedures
N/A
[DEV-2866](https://federal-spending-transparency.atlassian.net/browse/DEV-2866)
**Mockup**
N/A
Author: 
Reviewer(s):
=> Dev-2866: practice procedure description update

src/js/components/reviewData/ReviewDataContent.jsx
Updating link to agency submission files section
N/A
[DEV-8893](https://federal-spending-transparency.atlassian.net/browse/DEV-8893)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8893: Agency submission files link

src/_scss/layouts/default/header/_menuBar.scss, src/_scss/layouts/default/header/_userMenu.scss, src/_scss/layouts/default/header/header.scss, src/js/components/SharedComponents/navigation/NavigationComponent.jsx, src/js/components/landing/LandingContent.jsx
Navigation bar at the top of the screen no longer jumps to an inaccessible position when the screen shrinks.
N/A
[DEV-7085](https://federal-spending-transparency.atlassian.net/browse/DEV-7085)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-7085: top navigation bar shift

src/help/technical.md
Forgot to fix a date in the last release notes
=> Sprint 157 Release Notes Fix

src/js/components/generateDetachedFiles/DetachedFileA.jsx
Add note about GTASStatus column to file A generation page
N/A
[DEV-9078](https://federal-spending-transparency.atlassian.net/browse/DEV-9078)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-9078: New file a column cert status

src/js/components/help/helpSidebar.jsx
Removing FY22 DABS reporting schedule
N/A
[DEV-9124](https://federal-spending-transparency.atlassian.net/browse/DEV-1234)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-9124: Remove 2022 dabs schedule

src/js/components/addData/metadata/DateRangeField.jsx
Lower the year by 1 if the FY is higher than the actual year
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> Fix: Default year start

package-lock.json, package.json, src/_scss/site/_globalFooter.scss, src/js/app.jsx, src/js/components/SharedComponents/FooterComponent.jsx, src/js/components/SharedComponents/LeaveSiteModal.jsx
Adding links to GitHub and USAS in Broker footer.
N/A
[DEV-4221](https://federal-spending-transparency.atlassian.net/browse/DEV-4221)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-4221: footer links

src/js/helpers/submissionListHelper.js
Renaming the `get_certified_file` endpoint
N/A
[DEV-8851](https://federal-spending-transparency.atlassian.net/browse/DEV-8851)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-8851: rename get certified file endpoint

src/js/components/help/DataSourcesContent.jsx
Updating data sources page for city and county updates
N/A
[DEV-9767](https://federal-spending-transparency.atlassian.net/browse/DEV-9767)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-9767: Update city county location source

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Sprint-172 Release Notes (staging)

src/js/components/help/helpSidebar.jsx
Adding FY24 submission calendar link to the help page
N/A
[DEV-10117](https://federal-spending-transparency.atlassian.net/browse/DEV-10117)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10117: fy24 submission calendar link

src/js/components/help/helpContent.jsx, src/js/components/help/helpPage.jsx, src/js/components/landing/BlockContent.jsx, src/js/components/login/LoginCaia.jsx, src/js/components/login/LoginCaiaErrorMessage.jsx, src/js/components/login/LoginCaiaLoading.jsx, src/js/containers/login/AuthContainer.jsx, src/js/containers/login/LoginContainer.jsx, src/js/helpers/loginHelper.js
Removing and renaming all instances of MAX on the frontend
N/A
[DEV-9866](https://federal-spending-transparency.atlassian.net/browse/DEV-9866)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-9866: Remove MAX

src/js/components/help/helpSidebar.jsx
Fixing the typo in the help page url
N/A
[DEV-10289](https://federal-spending-transparency.atlassian.net/browse/DEV-10289)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10289: fabs release notes link

src/_scss/pages/addData/uploadPage/_uploadDropzone.scss, src/js/components/addData/DropZoneGenerated.jsx, src/js/components/addData/FileComponent.jsx, src/js/components/addData/SubmissionComponent.jsx, src/js/containers/addData/AddDataContainer.jsx, src/js/containers/addData/DropZoneContainer.jsx, src/js/helpers/util.js
Preventing file A upload on the DABS submission creation page
N/A
[DEV-9270](https://federal-spending-transparency.atlassian.net/browse/DEV-9270)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-9270: prevent initial file a upload

src/js/components/help/DataSourcesContent.jsx
Updating Country data information on the Help page
N/A
[DEV-9954](https://federal-spending-transparency.atlassian.net/browse/DEV-9954)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-9954: country code loader

src/js/components/help/resourcesContent.jsx
Fixing some text
N/A
[DEV-10254](https://federal-spending-transparency.atlassian.net/browse/DEV-10254)
**Mockup**
N/A
Author: 
Reviewer(s):
=> Fix: testing fix

src/js/components/help/helpSidebar.jsx
Removing FY23 submission calendar link
N/A
[DEV-10118](https://federal-spending-transparency.atlassian.net/browse/DEV-10118)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10118: fy23 submission calendar link removal

src/js/components/help/resourcesContent.jsx
Updating GSDM link and description in P&P
N/A
[DEV-10434](https://federal-spending-transparency.atlassian.net/browse/DEV-10434)
**Mockup**
N/A
Author: 
Reviewer(s):
=> Dev-10434: GSDM P&P Link

src/js/components/help/resourcesContent.jsx
Forgot a "the" and a space
N/A
[DEV-10434](https://federal-spending-transparency.atlassian.net/browse/DEV-10434)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10434: gsdm pp link

src/js/components/help/DataSourcesContent.jsx
Updating the information on the data sources page
N/A
[DEV-10687](https://federal-spending-transparency.atlassian.net/browse/DEV-10687)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10687: data sources content update

src/js/components/landing/recentActivity/RecentActivityTable.jsx, src/js/helpers/submissionListHelper.js, tests/containers/dashboard/filters/mockFilters.js, tests/helpers/submissionListHelper-test.js
Fixing sort for agency column in FABS recent activity
N/A
[DEV-9898](https://federal-spending-transparency.atlassian.net/browse/DEV-9898)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-9898: Recent activity fabs sort

src/js/components/help/DataSourcesContent.jsx
Adding another link to the DEFC source
N/A
[DEV-10773](https://federal-spending-transparency.atlassian.net/browse/DEV-10773)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10773: defc data source update

src/_scss/pages/dashboard/filters/_fiscalYears.scss, src/_scss/pages/submissionsTable/_typeaheadFilter.scss, src/js/components/SharedComponents/CalendarRangeDatePicker.jsx, src/js/components/SharedComponents/DropdownTypeahead.jsx, src/js/components/SharedComponents/SubmissionTypeFilterDropdown.jsx, src/js/components/dashboard/filters/FiscalYear.jsx, src/js/components/dashboard/filters/FiscalYearFilter.jsx, src/js/components/history/HistoryTable.jsx
Updated several unordered lists to only contain list items per 508-compliance
* "Created By" Submission Table Filer (DABS/FABS)
* Submission History Publication Lists
* Fiscal Years in the Historical DABS Dashboard 
N/A
[DEV-10695](https://federal-spending-transparency.atlassian.net/browse/DEV-10695)
**Mockup**
Author: 
Reviewer(s):
=> DEV-10695: 508 Fix Unordered Lists

src/js/components/SharedComponents/table/ScrollableTable.jsx, src/js/components/dashboard/table/DashboardTable.jsx, src/js/components/reviewData/CertificationModal/CertifyDisclaimer.jsx, src/js/components/reviewData/CertificationModal/PublishDisclaimer.jsx
Updated several scrollable sections to be focusable per 508-compliance
* DABS FABS Error/Warnings
* Publish/Certify Disclaimers
* Rule Descriptions in the Historical DABS Dashboard 
N/A
[DEV-10692](https://federal-spending-transparency.atlassian.net/browse/DEV-10692)
**Mockup**
Author: 
Reviewer(s):
=> DEV-10692: 508 Keyboard-Accessable Scrollable Sections

src/js/components/addData/metadata/DateDropdown.jsx
Addressing the 508 compliance check for the upload DABS select.
N/A
[DEV-10697](https://federal-spending-transparency.atlassian.net/browse/DEV-10697)
Author: 
Reviewer(s):
=> DEV-10697: Adding title to DABS Upload Date Select

src/js/components/SharedComponents/DropdownTypeahead.jsx, src/js/components/SharedComponents/DropdownTypeaheadCheckbox.jsx, src/js/components/SharedComponents/autocomplete/Autocomplete.jsx
Per 508 Compliance, adding titles to inputs in the Created By sections of both DABS/FABS Dashboard Filters and the Historical DABS Dashboard.
N/A
[DEV-10694](https://federal-spending-transparency.atlassian.net/browse/DEV-10694)
**Mockup**
Author: 
Reviewer(s):
=> DEV-10694: Adding Titles to Inputs

src/js/components/help/resourcesContent.jsx
Updating the P&P file link to a more generic one
N/A
[DEV-10881](https://federal-spending-transparency.atlassian.net/browse/DEV-10881)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10881: pnp link update

src/js/components/SharedComponents/ProgressBar.jsx, src/js/components/uploadFabsFile/UploadFabsFileValidation.jsx
Cleaning up aria properties where possible
N/A
[DEV-10693](https://federal-spending-transparency.atlassian.net/browse/DEV-10693)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10693: clean up aria properties

src/js/components/validateData/ValidateDataFileComponent.jsx
Cleaning up a missed Aria property that we can fix
N/A
[DEV-10693](https://federal-spending-transparency.atlassian.net/browse/DEV-10693)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10693: aria properties

src/js/components/SharedComponents/revalidate/RevalidateDataModal.jsx, src/js/components/crossFile/components/ReplacementButton.jsx
Cleaning up a couple of places we forgot to label buttons
N/A
[DEV-10696](https://federal-spending-transparency.atlassian.net/browse/DEV-10696)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10696: Buttons must have discernable text

src/js/components/help/DataSourcesContent.jsx
Replacing links for city and county data sources
N/A
[DEV-11041](https://federal-spending-transparency.atlassian.net/browse/DEV-11041)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11041: Switch county loader

src/js/containers/generateDetachedFiles/DetachedFilesFYPContainer.jsx
Updating the text on the GTAS BOC page.
N/A
[DEV-11127](https://federal-spending-transparency.atlassian.net/browse/DEV-11127)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11127: gtas boc page description

src/js/components/help/DataSourcesContent.jsx
Adding BOC data link to data sources page
N/A
[DEV-11228](https://federal-spending-transparency.atlassian.net/browse/DEV-11228)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11228: gtas boc data sources

src/js/components/help/helpSidebar.jsx
Adding the FY25 submission window calendar to the help page
N/A
[DEV-11239](https://federal-spending-transparency.atlassian.net/browse/DEV-11239)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11239: fy25 submission calendar

src/js/containers/generateDetachedFiles/DetachedFilesFYPContainer.jsx
Missed one capitalization fix
N/A
[DEV-11316](https://federal-spending-transparency.atlassian.net/browse/DEV-11316)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11316: data broker rebrand (fix)

src/js/components/SharedComponents/CalendarDateRangePicker.jsx, src/js/components/generateFiles/components/CalendarDatePicker.jsx, src/js/components/generateFiles/components/GenerateFileBox.jsx, src/js/containers/submissionsTable/LastDateModifiedContainer.jsx
Renaming calendar components to better reflect what they actually are/do
N/A
[DEV-11276](https://federal-spending-transparency.atlassian.net/browse/DEV-11276)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11276: calendar dropdown renames

src/js/containers/generateDetachedFiles/DetachedFilesFYPContainer.jsx
Updating frontend text for GTAS Comparison Report PYA
N/A
[DEV-10986](https://federal-spending-transparency.atlassian.net/browse/DEV-10986)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-10986: GTAS comparison report pya

src/js/components/landing/BlockContent.jsx, src/js/components/landing/blocks/LandingBlock.jsx
Fixing how external links work in block content
N/A
[DEV-11360](https://federal-spending-transparency.atlassian.net/browse/DEV-11360)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11360: request access link

src/js/containers/generateDetachedFiles/DetachedFilesFYPContainer.jsx
Updating text for GTAS Comparison Report generation page to explain that invalid values are filtered out
N/A
[DEV-11554](https://federal-spending-transparency.atlassian.net/browse/DEV-11554)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11554: boc filter gtas report

src/js/components/help/helpSidebar.jsx, src/js/components/help/resourcesContent.jsx
* Updated the validation rules file from 1.0 -> 1.1
* Removed FY24 calendar
N/A
[DEV-11861](https://federal-spending-transparency.atlassian.net/browse/DEV-11861)
[DEV-11903](https://federal-spending-transparency.atlassian.net/browse/DEV-11903)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11861/11903:  Minor Help/Resource page updates

src/js/components/help/helpSidebar.jsx
This resolves minor typos in the sign up email template.
N/A
[DEV-9808](https://federal-spending-transparency.atlassian.net/browse/DEV-9808)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-9808: Help Email Typos

README.md
Fixing a README link and adding some more details for running tests/lint
N/A
N/A
**Mockup**
N/A
Author: 
Reviewer(s):
=> ISSUE-1364: fix contributing link

src/js/components/help/DataSourcesContent.jsx
Updating subaward data source information
N/A
[DEV-12449](https://federal-spending-transparency.atlassian.net/browse/DEV-12449)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-12449: Data source subaward update

src/js/components/help/DataSourcesContent.jsx
Adding PARK to Data Sources Page. Fixing a linter warning
N/A
[DEV-11943](https://federal-spending-transparency.atlassian.net/browse/DEV-11943)
**Mockup**
N/A
Author: 
Reviewer(s):
=> DEV-11943: PARK data source

tests/components/AddDataPage-test.jsx, tests/components/LandingPage-test.jsx, tests/components/ValidationContent-test.jsx
This PR adds test suites for several of our high level pages and components.  These tests ensure that the pages render and that the content appears on the page.  
[DEV-12327](https://federal-spending-transparency.atlassian.net/browse/DEV-12327)
Author: 
Reviewer(s):
=> [DEV-12327] - Adding RTL tests

src/help/changelog.md, src/help/history.md, src/help/technical.md, src/help/technicalHistory.md
=> Sprint 203 Release Notes

.github/workflows/cancel-running-workflow.yaml, .github/workflows/pull-request-checks.yaml, .github/workflows/test-install.yaml, .github/workflows/test-unit.yaml, .travis.yml, package.json
Setup to replace Travis for PR checks.
N/A
[DEV-11990](https://federal-spending-transparency.atlassian.net/browse/DEV-11990)
Author: 
Reviewer(s):
[DEV-11990]: https://federal-spending-transparency.atlassian.net/browse/DEV-11990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-11990] Github Actions Integration

src/js/components/generateEF/GenerateEFContent.jsx
Simply removing an additional reference to FSRS as File F and replacing it with SAM.
N/A
[DEV-12762](https://federal-spending-transparency.atlassian.net/browse/DEV-12762)
**Mockup**
Author: 
Reviewer(s):
[DEV-12762]: https://federal-spending-transparency.atlassian.net/browse/DEV-12762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-12762] Fix File F Description

src/js/components/SharedComponents/DropdownTypeahead.jsx
Fixing the "created by" filter in the submission tables
N/A
[DEV-13154](https://federal-spending-transparency.atlassian.net/browse/DEV-13154)
**Mockup**
N/A
Author: 
Reviewer(s):
[DEV-13154]: https://federal-spending-transparency.atlassian.net/browse/DEV-13154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
=> DEV-13154: Submission table created by

src/js/components/dashboard/DashboardPage.jsx, src/js/containers/submission/SubmissionContainer.jsx
Fixing history issues with dashboard and submission pages
N/A
[DEV-13134](https://federal-spending-transparency.atlassian.net/browse/DEV-13134)
**Mockup**
N/A
Author: 
Reviewer(s):
[DEV-13134]: https://federal-spending-transparency.atlassian.net/browse/DEV-13134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> DEV-13134: DABS dashboard history
